(disable-packages! undo-tree
                   2048-game
                   ace-link
                   desktop
                   doc-view
                   erc
                   fancy-battery
                   golden-ratio
                   helm-cscope
                   helm-games
                   jabber
                   open-junk-file
                   paradox
                   rcirc
                   ruby-test-mode
                   selectric-mode
                   slack
                   smex
                   sudoku
                   tetris
                   typit
                   xcscope
                   xkcd
                   zoom-frm
                   xt-mouse
                   mouse
                   undo-fu-session
                   wdired
                   ranger
                   drag-stuff
                   evil-collection-ibuffer
                   evil-traces
                   )
