;;; +proof-general.el -*- lexical-binding: t; no-byte-compile: t; -*-
;;-- Header
;; File Commentary:
;;
;;
;; See footer for licenses/metadata/notes as applicable
;;-- end Header

(defun coq-init-smie ()
  (smie-setup coq-smie-grammar #'coq-smie-rules
              :forward-token #'coq-smie-forward-token
              :backward-token #'coq-smie-backward-token)
  )

;; name abbreviation expansion
(defvar jg-coq-vernac
  (append '( ;; Axioms
            ("Local Axiom" nil "Local Axiom # : #" t "Local\\s-+Axiom")
            ("Local Axioms" nil "Local Axioms # , #: #" t "Local\\s-+Axioms")
            ("Axiom" "ax" "Axiom # : #" t "Axiom")
            ("Axioms" "axs" "Axioms # , #: #" t "Axioms")
            )
          '( ;; Variables
            ("Global Variable" "gv" "Global Variable #: #." t "Global\\s-+Variable")
            ("Global Variables" "gvs" "Global Variables # , #: #." t "Global\\s-+Variables")
            ("Variable" "v" "Variable #: #." t "Variable")
            ("Variables" "vs" "Variables # , #: #." t "Variables")
            ("Parameter" "par" "Parameter #: #" t "Parameter")
            ("Parameters" "par" "Parameters #: #" t "Parameters")
            )
          '( ;; hints
            ("Hint Constructors" "hc" "Hint Constructors # : #." t "Hint\\s-+Constructors")
            ("Hint Extern" "he" "Hint Extern @{cost} @{pat} => @{tac} : @{db}." t "Hint\\s-+Extern")
            ("Hint Mode" "hm" "Hint Mode # @{mode...} : @{db}." t "Hint\\s-+Mode")
            ("Hint Immediate" "hi" "Hint Immediate # : @{db}." t "Hint\\s-+Immediate")
            ("Hint Resolve" "hr" "Hint Resolve # : @{db}." t "Hint\\s-+Resolve")
            ("Hint Rewrite ->" "hrw" "Hint Rewrite -> @{t1,t2...} using @{tac} : @{db}." t "Hint\\s-+Rewrite")
            ("Hint Rewrite <-" "hrw" "Hint Rewrite <- @{t1,t2...} using @{tac} : @{db}." t)
            ("Hint Unfold" "hu" "Hint Unfold # : #." t "Hint\\s-+Unfold")
            )
          '( ;; Hypotheses
            ("Hypothesis" "hyp" "Hypothesis #: #" t "Hypothesis")
            ("Hypotheses" "hyp" "Hypotheses #: #" t "Hypotheses")
            ("Conjecture" "conj" "Conjecture #: #." t "Conjecture")
            ("Context" nil "Context #, (# : #)." t "Context")
            )
          '( ;; coercion
            ("Local Coercion" nil "Local Coercion @{id} : @{typ1} >-> @{typ2}." t "Local\\s-+Coercion")
            ("Coercion" "coerc" "Coercion @{id} : @{typ1} >-> @{typ2}." t "Coercion")
            )
          '( ;; modules
            ("Declare Module : :=" "dm" "Declare Module # : # := #." t "Declare\\s-+Module")
            ("Declare Module <: :=" "dm2" "Declare Module # <: # := #." t)
            ("Declare Module Import : :=" "dmi" "Declare Module # : # := #." t)
            ("Declare Module Import <: :=" "dmi2" "Declare Module # <: # := #." t)
            ("Declare Module Export : :=" "dme" "Declare Module # : # := #." t)
            ("Declare Module Export <: :=" "dme2" "Declare Module # <: # := #." t)
            )
          '( ;; definition
            ("Local Definition" nil "Local Definition #:# := #." t "Local\\s-+Definition")
            ("Definition" "def" "Definition #:# := #." t "Definition")
            ("Definition (2 args)" "def2" "Definition # (# : #) (# : #):# := #." t)
            ("Definition (3 args)" "def3" "Definition # (# : #) (# : #) (# : #):# := #." t)
            ("Definition (4 args)" "def4" "Definition # (# : #) (# : #) (# : #) (# : #):# := #." t)
            ("CoFixpoint" "cfix" "CoFixpoint # (#:#) : # :=\n#." t "CoFixpoint")
            ("CoInductive" "coindv" "CoInductive # : # :=\n|# : #." t "CoInductive")
            ("Fixpoint" "fix" "Fixpoint # (#:#) {struct @{arg}} : # :=\n#." t "Fixpoint")
            ("Let" "Let" "Let # : # := #." t "Let")
            )
          '( ;; Ltac2
            ("Local Ltac2" nil "Local Ltac2 # := #." t "Local\\s-+Ltac2")
            ("Ltac2 Type" "lt2rty" "Ltac2 Type rec # := #." t "Ltac2 Type rec")
            ("Ltac2 Type" "lt2ty" "Ltac2 Type # := #." t "Ltac2 Type")
            ("Ltac2 Type" "lt2oty" "Ltac2 Type # ::= #." t "Ltac2 Type")
            ("Ltac2 Type" "lt2wty" "Ltac2 Type #." t "Ltac2 Type")
            ("Ltac2" "lt2mr" "Ltac2 mutable rec # := #." t "Ltac2 mutable rec")
            ("Ltac2" "lt2m" "Ltac2 mutable # := #." t "Ltac2 mutable")
            ("Ltac2" "lt2r" "Ltac2 rec # := #." t "Ltac2 rec")
            ("Ltac2" "lt2s" "Ltac2 Set # := #." t "Ltac2 Set")
            ("Ltac2" "lt2" "Ltac2 # := #." t "Ltac2")
            ("Ltac2 Notation" "lt2n" "Ltac2 Notation # := #." t "Ltac2 Notation")
            ("Ltac2 Eval" "lt2e" "Ltac2 Eval #." nil "Ltac2 Eval")
            )
          '( ;; Ltac
            ("Local Ltac" nil "Local Ltac # := #." t "Local\\s-+Ltac")
            ("Ltac" "ltac" "Ltac # := #." t "Ltac")
            )
          '( ;; Module
            ("Module :=" "mo" "Module # : # := #." t)
            ("Module <: :=" "mo2" "Module # <: # := #." t)
            ("Module Import :=" "moi" "Module Import # : # := #." t)
            ("Module Import <: :=" "moi2" "Module Import # <: # := #." t)
            ("Module Export :=" "moe" "Module Export # : # := #." t)
            ("Module Export <: :=" "moe2" "Module Export# <: # := #." t)
            )
          '( ;; Record
            ("Record" "rec" "Record # : # := {\n# : #;\n# : # }" t "Record")
            ("Structure" "str" "Structure # : # := {\n# : #;\n# : # }" t "Structure")
            )
          '( ;; Notation
            ("Notation (assoc)" "notas" "Notation \"#\" := # (at level #, # associativity)." t)
            ("Notation (at assoc)" "notassc" "Notation \"#\" := # (at level #, # associativity) : @{scope}." t)
            ("Notation (at at scope)" "notasc" "Notation \"#\" := # (at level #, # at level #) : @{scope}." t)
            ("Notation (at at)" "nota" "Notation \"#\" := # (at level #, # at level #)." t)
            ("Notation (only parsing)" "notsp" "Notation # := # (only parsing)." t)
            ("Local Notation" "lnots" "Local Notation # := #." t "Local\\s-+Notation")
            ("Local Notation (only parsing)" "lnotsp" "Local Notation # := # (only parsing)." t)
            ("Notation (simple)" "nots" "Notation # := #." t "Notation")
            ("Infix" "inf" "Infix \"#\" := # (at level #) : @{scope}." t "Infix")
            ("Reserved Infix" nil "Reserved Infix" t "Reserved\\s-+Infix")
            ("Reserved Notation" nil "Reserved Notation" t "Reserved\\s-+Notation")
            )
          '( ;; Typeclasses
            ("Class" "class" "Class [ # ] := \n# : #;\n# : #." t "Class")
            ("Typeclasses Opaque" nil "Typeclasses Opaque #." t "Typeclasses\\s-+Opaque")
            ("Typeclasses eauto" nil "Typeclasses eauto := #." t "Typeclasses\\s-+eauto")
            )
          '( ;; add
            ("Add Morphism" "addmor" "Add Morphism @{f} : @{id}" t "Add\\s-+Morphism")
            ("Add Parametric Morphism" nil "Add Parametric Morphism : " t "Add\\s-+Parametric\\s-+Morphism")
            ("Add Parametric Relation" nil "Add Parametric Relation : " t "Add\\s-+Parametric\\s-+Relation")
            ("Add Abstract Ring" nil "Add Abstract Ring #." t "Add\\s-+Abstract\\s-+Ring")
            ("Add Abstract Semi Ring" nil "Add Abstract Semi Ring #." t "Add\\s-+Abstract\\s-+Semi\\s-+Ring")
            ("Add Field" nil "Add Field #." t "Add\\s-+Field")
            ("Add LoadPath" nil "Add LoadPath #." t "Add\\s-+LoadPath")
            ("Add ML Path" nil "Add ML Path #." t "Add\\s-+ML\\s-+Path")
            ("Add Printing" nil "Add Printing #." t "Add\\s-+Printing")
            ("Add Printing If" nil "Add Printing If #." t "Add\\s-+Printing\\s-+If")
            ("Add Printing Let" nil "Add Printing Let #." t "Add\\s-+Printing\\s-+Let")
            ("Add Rec LoadPath" nil "Add Rec LoadPath #." t "Add\\s-+Rec\\s-+LoadPath")
            ("Add Rec ML Path" nil "Add Rec ML Path #." t "Add\\s-+Rec\\s-+ML\\s-+Path")
            ("Add Ring" nil "Add Ring #." t "Add\\s-+Ring")
            ("Add Semi Ring" nil "Add Semi Ring #." t "Add\\s-+Semi\\s-+Ring")
            ("Add Setoid" nil "Add Setoid #." t "Add\\s-+Setoid")
            )
          '( ;; print
            ("Print Coercions" nil "Print Coercions." nil "Print\\s-+Coercions")
            ("Print Hint" nil "Print Hint." nil "Print\\s-+Hint" coq-PrintHint)
            ("Print Ltac2" "lt2p" "Print Ltac2 #." nil "Print Ltac2")
            ("Print" "p" "Print #." nil "Print") ("Pwd" nil "Pwd." nil "Pwd")
            )
          '( ;; inspecting
            ("About" nil "About #." nil "About") ("Check" nil "Check" nil "Check")
            ("Compute" nil "Compute" nil "Compute") ("Fail" nil "Fail" nil "Fail")
            ("Inspect" nil "Inspect #." nil "Inspect")
            ("Locate File" nil "Locate File \"#\"." nil "Locate\\s-+File")
            ("Locate Library" nil "Locate Library #." nil "Locate\\s-+Library")
            ("Locate Notation" nil "Locate Notation (#) #" nil "Locate\\s-+Notation")
            ("Locate" nil "Locate" nil "Locate")
            ("Search" nil "Search #" nil "Search")
            ("SearchPattern" nil "SearchPattern (#)" nil "SearchPattern")
            ("SearchRewrite" nil "SearchRewrite #" nil "SearchRewrite")
            ("Show" nil "Show #." nil "Show")
            ("Test" nil "Test" nil "Test" nil t)
            )
          '( ;; scope
            ("Arguments Scope" "argsc" "Arguments Scope @{id} [ @{_} ]" t "Arguments\\s-+Scope")
            ("Bind Scope" "bndsc" "Bind Scope @{scope} with @{type}" t "Bind\\s-+Scope")
            ("Local Close Scope" "lclsc" "Local Close Scope #" t "Local\\s-+Close\\s-+Scope")
            ("Close Scope" "clsc" "Close Scope #" t "Close\\s-+Scope")
            ("Delimit Scope" "delsc" "Delimit Scope @{scope} with @{id}." t "Delimit\\s-+Scope")
            ("Local Open Scope" nil "Local Open Scope #" t "Local\\s-+Open\\s-+Scope")
            ("Open Local Scope" nil "Open Local Scope #" t "Open\\s-+Local\\s-+Scope")
            ("Open Scope" "opsc" "Open Scope #" t "Open\\s-+Scope")
            )
          '( ;; set
            ("Set Asymmetric Patterns" nil "Set Asymmetric Patterns" t "Set Asymmetric\\s-+Patterns")
            ("Set Atomic Load" nil "Set Atomic Load" t "Set Atomic\\s-+Load")
            ("Set Automatic Coercions Import" nil "Set Automatic Coercions Import" t "Set Automatic\\s-+Coercions\\s-+Import")
            ("Set Automatic Introduction" nil "Set Automatic Introduction" t "Set Automatic\\s-+Introduction")
            ("Set Boolean Equality Schemes" nil "Set Boolean Equality Schemes" t "Set Boolean\\s-+Equality\\s-+Schemes")
            ("Set Bracketing Last Introduction Pattern" nil "Set Bracketing Last Introduction Pattern" t "Set Bracketing\\s-+Last\\s-+Introduction\\s-+Pattern")
            ("Set Bullet Behavior" nil "Set Bullet Behavior" t "Set Bullet\\s-+Behavior")
            ("Set Case Analysis Schemes" nil "Set Case Analysis Schemes" t "Set Case\\s-+Analysis\\s-+Schemes")
            ("Set Compat Notations" nil "Set Compat Notations" t "Set Compat\\s-+Notations")
            ("Set Congruence Depth" nil "Set Congruence Depth" t "Set Congruence\\s-+Depth")
            ("Set Congruence Verbose" nil "Set Congruence Verbose" t "Set Congruence\\s-+Verbose")
            ("Set Contextual Implicit" nil "Set Contextual Implicit" t "Set Contextual\\s-+Implicit")
            ("Set Debug Auto" nil "Set Debug Auto" t "Set Debug\\s-+Auto")
            ("Set Debug Eauto" nil "Set Debug Eauto" t "Set Debug\\s-+Eauto")
            ("Set Debug RAKAM" nil "Set Debug RAKAM" t "Set Debug\\s-+RAKAM")
            ("Set Debug Tactic Unification" nil "Set Debug Tactic Unification" t "Set Debug\\s-+Tactic\\s-+Unification")
            ("Set Debug Trivial" nil "Set Debug Trivial" t "Set Debug\\s-+Trivial")
            ("Set Debug Unification" nil "Set Debug Unification" t "Set Debug\\s-+Unification")
            ("Set Decidable Equality Schemes" nil "Set Decidable Equality Schemes" t "Set Decidable\\s-+Equality\\s-+Schemes")
            ("Set Default Clearing Used Hypotheses" nil "Set Default Clearing Used Hypotheses" t "Set Default\\s-+Clearing\\s-+Used\\s-+Hypotheses")
            ("Set Default Goal Selector" nil "Set Default Goal Selector" t "Set Default\\s-+Goal\\s-+Selector")
            ("Set Default Proof Mode" nil "Set Default Proof Mode" t "Set Default\\s-+Proof\\s-+Mode")
            ("Set Default Proof Using" nil "Set Default Proof Using" t "Set Default\\s-+Proof\\s-+Using")
            ("Set Default Timeout" nil "Set Default Timeout" t "Set Default\\s-+Timeout")
            ("Set Dependent Propositions Elimination" nil "Set Dependent Propositions Elimination" t "Set Dependent\\s-+Propositions\\s-+Elimination")
            ("Set Discriminate Introduction" nil "Set Discriminate Introduction" t "Set Discriminate\\s-+Introduction")
            ("Set Dump Bytecode" nil "Set Dump Bytecode" t "Set Dump\\s-+Bytecode")
            ("Set Elimination Schemes" nil "Set Elimination Schemes" t "Set Elimination\\s-+Schemes")
            ("Set Equality Scheme" nil "Set Equality Scheme" t "Set Equality\\s-+Scheme")
            ("Set Extraction AccessOpaque" nil "Set Extraction AccessOpaque" t "Set Extraction\\s-+AccessOpaque")
            ("Set Extraction AutoInline" nil "Set Extraction AutoInline" t "Set Extraction\\s-+AutoInline")
            ("Set Extraction Conservative Types" nil "Set Extraction Conservative Types" t "Set Extraction\\s-+Conservative\\s-+Types")
            ("Set Extraction File Comment" nil "Set Extraction File Comment" t "Set Extraction\\s-+File\\s-+Comment")
            ("Set Extraction Flag" nil "Set Extraction Flag" t "Set Extraction\\s-+Flag")
            ("Set Extraction KeepSingleton" nil "Set Extraction KeepSingleton" t "Set Extraction\\s-+KeepSingleton")
            ("Set Extraction Optimize" nil "Set Extraction Optimize" t "Set Extraction\\s-+Optimize")
            ("Set Extraction SafeImplicits" nil "Set Extraction SafeImplicits" t "Set Extraction\\s-+SafeImplicits")
            ("Set Extraction TypeExpand" nil "Set Extraction TypeExpand" t "Set Extraction\\s-+TypeExpand")
            ("Set Firstorder Depth" nil "Set Firstorder Depth" t "Set Firstorder\\s-+Depth")
            ("Set Hide Obligations" nil "Set Hide Obligations" t "Set Hide\\s-+Obligations")
            ("Set Implicit Arguments" nil "Set Implicit Arguments" t "Set Implicit\\s-+Arguments")
            ("Set Info Auto" nil "Set Info Auto" t "Set Info\\s-+Auto")
            ("Set Info Eauto" nil "Set Info Eauto" t "Set Info\\s-+Eauto")
            ("Set Info Level" nil "Set Info Level" t "Set Info\\s-+Level")
            ("Set Info Trivial" nil "Set Info Trivial" t "Set Info\\s-+Trivial")
            ("Set Injection L2R Pattern Order" nil "Set Injection L2R Pattern Order" t "Set Injection\\s-+L2R\\s-+Pattern\\s-+Order")
            ("Set Injection On Proofs" nil "Set Injection On Proofs" t "Set Injection\\s-+On\\s-+Proofs")
            ("Set Inline Level" nil "Set Inline Level" t "Set Inline\\s-+Level")
            ("Set Intuition Iff Unfolding" nil "Set Intuition Iff Unfolding" t "Set Intuition\\s-+Iff\\s-+Unfolding")
            ("Set Intuition Negation Unfolding" nil "Set Intuition Negation Unfolding" t "Set Intuition\\s-+Negation\\s-+Unfolding")
            ("Set Kernel Term Sharing" nil "Set Kernel Term Sharing" t "Set Kernel\\s-+Term\\s-+Sharing")
            ("Set Keyed Unification" nil "Set Keyed Unification" t "Set Keyed\\s-+Unification")
            ("Set Loose Hint Behavior" nil "Set Loose Hint Behavior" t "Set Loose\\s-+Hint\\s-+Behavior")
            ("Set Maximal Implicit Insertion" nil "Set Maximal Implicit Insertion" t "Set Maximal\\s-+Implicit\\s-+Insertion")
            ("Set Nonrecursive Elimination Schemes" nil "Set Nonrecursive Elimination Schemes" t "Set Nonrecursive\\s-+Elimination\\s-+Schemes")
            ("Set Parsing Explicit" nil "Set Parsing Explicit" t "Set Parsing\\s-+Explicit")
            ("Set Primitive Projections" nil "Set Primitive Projections" t "Set Primitive\\s-+Projections")
            ("Set Printing All" nil "Set Printing All" t "Set\\s-+Printing\\s-+All")
            ("Set Printing Coercions" nil "Set Printing Coercions" t "Set\\s-+Printing\\s-+Coercions")
            ("Set Printing Compact Contexts" nil "set Printing Compact Contexts" t "set\\s-+Printing\\s-+Compact\\s-+Contexts")
            ("Set Printing Depth" nil "Set Printing Depth" t "Set\\s-+Printing\\s-+Depth")
            ("Set Printing Existential Instances" nil "Set Printing Existential Instances" t "Set\\s-+Printing\\s-+Existential\\s-+Instances")
            ("Set Printing Goal Tags" nil "Set Printing Goal Tags" t "Set\\s-+Printing\\s-+Goal\\s-+Tags")
            ("Set Printing Goal Names" nil "Set Printing Goal Names" t "Set\\s-+Printing\\s-+Goal\\s-+Names")
            ("Set Printing Implicit" nil "Set Printing Implicit" t "Set\\s-+Printing\\s-+Implicit")
            ("Set Printing Implicit Defensive" nil "Set Printing Implicit Defensive" t "Set\\s-+Printing\\s-+Implicit\\s-+Defensive")
            ("Set Printing Matching" nil "Set Printing Matching" t "Set\\s-+Printing\\s-+Matching")
            ("Set Printing Notations" nil "Set Printing Notations" t "Set\\s-+Printing\\s-+Notations")
            ("Set Printing Primitive Projection Compatibility" nil "Set Printing Primitive Projection Compatibility" t "Set\\s-+Printing\\s-+Primitive\\s-+Projection\\s-+Compatibility")
            ("Set Printing Primitive Projection Parameters" nil "Set Printing Primitive Projection Parameters" t "Set\\s-+Printing\\s-+Primitive\\s-+Projection\\s-+Parameters")
            ("Set Printing Projections" nil "Set Printing Projections" t "Set\\s-+Printing\\s-+Projections")
            ("Set Printing Records" nil "Set Printing Records" t "Set\\s-+Printing\\s-+Records")
            ("Set Printing Synth" nil "Set Printing Synth" t "Set\\s-+Printing\\s-+Synth")
            ("Set Printing Unfocused" nil "Set Printing Unfocused" t "Set\\s-+Printing\\s-+Unfocused")
            ("Set Printing Universes" nil "Set Printing Universes" t "Set\\s-+Printing\\s-+Universes")
            ("Set Printing Width" nil "Set Printing Width" t "Set\\s-+Printing\\s-+Width")
            ("Set Printing Wildcard" nil "Set Printing Wildcard" t "Set\\s-+Printing\\s-+Wildcard")
            ("Set Program Mode" nil "Set Program Mode" t "Set Program\\s-+Mode")
            ("Set Proof Using Clear Unused" nil "Set Proof Using Clear Unused" t "Set Proof\\s-+Using\\s-+Clear\\s-+Unused")
            ("Set Record Elimination Schemes" nil "Set Record Elimination Schemes" t "Set Record\\s-+Elimination\\s-+Schemes")
            ("Set Refine Instance Mode" nil "Set Refine Instance Mode" t "Set Refine\\s-+Instance\\s-+Mode")
            ("Set Regular Subst Tactic" nil "Set Regular Subst Tactic" t "Set Regular\\s-+Subst\\s-+Tactic")
            ("Set Reversible Pattern Implicit" nil "Set Reversible Pattern Implicit" t "Set Reversible\\s-+Pattern\\s-+Implicit")
            ("Set Rewriting Schemes" nil "Set Rewriting Schemes" t "Set Rewriting\\s-+Schemes")
            ("Set Short Module Printing" nil "Set Short Module Printing" t "Set Short\\s-+Module\\s-+Printing")
            ("Set Shrink Obligations" nil "Set Shrink Obligations" t "Set Shrink\\s-+Obligations")
            ("Set SimplIsCbn" nil "Set SimplIsCbn" t "Set SimplIsCbn")
            ("Set Standard Proposition Elimination Names" nil "Set Standard Proposition Elimination Names" t "Set Standard\\s-+Proposition\\s-+Elimination\\s-+Names")
            ("Set Strict Proofs" nil "Set Strict Proofs" t "Set Strict\\s-+Proofs")
            ("Set Strict Universe Declaration" nil "Set Strict Universe Declaration" t "Set Strict\\s-+Universe\\s-+Declaration")
            ("Set Strongly Strict Implicit" nil "Set Strongly Strict Implicit" t "Set Strongly\\s-+Strict\\s-+Implicit")
            ("Set Suggest Proof Using" nil "Set Suggest Proof Using" t "Set Suggest\\s-+Proof\\s-+Using")
            ("Set Tactic Compat Context" nil "Set Tactic Compat Context" t "Set Tactic\\s-+Compat\\s-+Context")
            ("Set Tactic Evars Pattern Unification" nil "Set Tactic Evars Pattern Unification" t "Set Tactic\\s-+Evars\\s-+Pattern\\s-+Unification")
            ("Set Tactic Pattern Unification" nil "Set Tactic Pattern Unification" t "Set Tactic\\s-+Pattern\\s-+Unification")
            ("Set Transparent Obligations" nil "Set Transparent Obligations" t "Set Transparent\\s-+Obligations")
            ("Set Typeclass Resolution After Apply" nil "Set Typeclass Resolution After Apply" t "Set Typeclass\\s-+Resolution\\s-+After\\s-+Apply")
            ("Set Typeclass Resolution For Conversion" nil "Set Typeclass Resolution For Conversion" t "Set Typeclass\\s-+Resolution\\s-+For\\s-+Conversion")
            ("Set Typeclasses Debug" nil "Set Typeclasses Debug" t "Set Typeclasses\\s-+Debug")
            ("Set Typeclasses Dependency Order" nil "Set Typeclasses Dependency Order" t "Set Typeclasses\\s-+Dependency\\s-+Order")
            ("Set Typeclasses Depth" nil "Set Typeclasses Depth" t "Set Typeclasses\\s-+Depth")
            ("Set Typeclasses Modulo Eta" nil "Set Typeclasses Modulo Eta" t "Set Typeclasses\\s-+Modulo\\s-+Eta")
            ("Set Typeclasses Strict Resolution" nil "Set Typeclasses Strict Resolution" t "Set Typeclasses\\s-+Strict\\s-+Resolution")
            ("Set Typeclasses Unique Instances" nil "Set Typeclasses Unique Instances" t "Set Typeclasses\\s-+Unique\\s-+Instances")
            ("Set Typeclasses Unique Solutions" nil "Set Typeclasses Unique Solutions" t "Set Typeclasses\\s-+Unique\\s-+Solutions")
            ("Set Universal Lemma Under Conjunction" nil "Set Universal Lemma Under Conjunction" t "Set Universal\\s-+Lemma\\s-+Under\\s-+Conjunction")
            ("Set Universe Minimization ToSet" nil "Set Universe Minimization ToSet" t "Set Universe\\s-+Minimization\\s-+ToSet")
            ("Set Universe Polymorphism" nil "Set Universe Polymorphism" t "Set Universe\\s-+Polymorphism")
            ("Set Verbose Compat Notations" nil "Set Verbose Compat Notations" t "Set Verbose\\s-+Compat\\s-+Notations")
            ("Set Function_debug" nil "Set Function_debug" t "Set Function_debug")
            ("Set Function_raw_tcc" nil "Set Function_raw_tcc" t "Set Function_raw_tcc")
            ("Set Functional Induction Rewrite Dependent" nil "Set Functional Induction Rewrite Dependent" t "Set Functional\\s-+Induction\\s-+Rewrite\\s-+Dependent")
            ("Set Hyps Limit" nil "Set Hyps Limit" t "Set Hyps\\s-+Limit")
            ("Set Ltac Debug" nil "Set Ltac Debug" t "Set Ltac\\s-+Debug")
            ("Set Silent" nil "Set Silent" t "Set Silent")
            ("Set Undo" nil "Set Undo" t "Set Undo")
            ("Set Search Blacklist" nil "Set Search Blacklist" t "Set Search\\s-+Blacklist")
            ("Set Printing Coercion" nil "Set Printing Coercion" t "Set\\s-+Printing\\s-+Coercion")
            ("Set Printing If" nil "Set Printing If" t "Set\\s-+Printing\\s-+If")
            ("Set Printing Let" nil "Set Printing Let" t "Set\\s-+Printing\\s-+Let")
            ("Set Printing Record" nil "Set Printing Record" t "Set\\s-+Printing\\s-+Record")
            ("Set Printing Constructor" nil "Set Printing Constructor" t "Set\\s-+Printing\\s-+Constructor")
            )
          )
  )
(defvar jg-coq-tactics-ltac
  (append  '(
             ("-- Ltac")
             ("absurd (ltac)" "abs" "absurd " t "absurd")
             ("apply  (ltac)" "ap" "apply " t "apply")
             ("assert by (ltac)" "assb" "assert ( # : # ) by #" t "assert")
             ("assert (ltac)" "ass" "assert ( # : # )" t)
             ;;     ("assumption" "as" "assumption" t "assumption")
             ("auto with arith (ltac)" "awa" "auto with arith" t)
             ("auto with (ltac)" "aw" "auto with @{db}" t)
             ("auto (ltac)" "a" "auto" t "auto")
             ("autorewrite with in using (ltac)" "arwiu" "autorewrite with @{db,db...} in @{hyp} using @{tac}" t)
             ("autorewrite with in (ltac)" "arwi" "autorewrite with @{db,db...} in @{hyp}" t)
             ("autorewrite with using (ltac)" "arwu" "autorewrite with @{db,db...} using @{tac}" t)
             ("autorewrite with (ltac)" "ar" "autorewrite with @{db,db...}" t "autorewrite")
             )
           '(
             ("case (ltac)" nil "case " t "case")
             ("case_eq (ltac)" "ceq" "case_eq " t "case_eq")
             ("case_type (ltac)" "cty" "case_type " t "case_type")
             ("cbn (ltac)" "c" "cbn" t "cbn")
             ("cbn (with flags) (ltac)" "cbn" "cbn beta delta [#] iota zeta" t "cbn")
             ("cbv (ltac)" "cbv" "cbv beta delta [#] iota zeta" t "cbv")
             ("change in (ltac)" "chi" "change # in #" t)
             ("change with in (ltac)" "chwi" "change # with # in #" t)
             ("change with (ltac)" "chw" "change # with" t)
             ("change (ltac)" "ch" "change " t "change")
             ("clear (ltac)" "cl" "clear" t "clear")
             ("clear dependent (ltac)" "cldep" "clear dependent" t "clear\\s-+dependent")
             ("clearbody (ltac)" "cl" "clearbody" t "clearbody")
             ("cofix (ltac)" "cof" "cofix" t "cofix")
             ("coinduction (ltac)" "coind" "coinduction" t "coinduction")
             ("compare (ltac)" "cmpa" "compare # #" t "compare")
             ("compute (ltac)" "cmpu" "compute" t "compute")
             ;;     ("congruence (ltac)" "cong" "congruence" t "congruence")
             ("constructor (ltac)" "cons" "constructor" t "constructor")
             ;;     ("contradiction (ltac)" "contr" "contradiction" t "contradiction")
             ("cut (ltac)" "cut" "cut" t "cut")
             ("cutrewrite (ltac)" "cutr" "cutrewrite -> # = #" t "cutrewrite")
             )
           '(
             ;;     ("decide equality (ltac)" "deg" "decide equality" t "decide\\s-+equality")
             ("decide_right (ltac)" "decr" "decide_right" t "decide\\s-+right")
             ("decide_left (ltac)" "decl" "decide_left" t "decide\\s-+left")
             ("decide (ltac)" nil "decide" t "decide")
             ("decompose record (ltac)" "decr" "decompose record #" t "decompose\\s-+record")
             ("decompose sum (ltac)" "decs" "decompose sum #" t "decompose\\s-+sum")
             ("decompose (ltac)" "dec" "decompose [#] #" t "decompose")
             ("dependent inversion (ltac)" "depinv" "dependent inversion" t "dependent\\s-+inversion")
             ("dependent inversion with (ltac)" "depinvw" "dependent inversion # with #" t)
             ("dependent inversion_clear (ltac)" "depinvc" "dependent inversion_clear" t "dependent\\s-+inversion_clear")
             ("dependent inversion_clear with (ltac)" "depinvw" "dependent inversion_clear # with #" t)
             ("dependent rewrite -> (ltac)" "depr" "dependent rewrite -> @{id}" t "dependent\\s-+rewrite")
             ("dependent rewrite <- (ltac)" "depr<" "dependent rewrite <- @{id}" t)
             ("destr_eq (ltac)" "deseq" "destr_eq " t  "destr_eq")
             ("destruct as (ltac)" "desa" "destruct # as #" t)
             ("destruct using (ltac)" "desu" "destruct # using #" t)
             ("destruct (ltac)" "des" "destruct " t  "destruct")
             ("destruct_with_eqn (ltac)" "deswe" "destruct_with_eqn " t  "destruct_with_eqn")
             ("destruct_all (ltac)" "desall" "destruct_all " t  "destruct_all")
             ;;     ("discriminate (ltac)" "dis" "discriminate" t "discriminate")
             ("discrR (ltac)" "discrR" "discrR" t "discrR")
             ("double induction (ltac)" "dind" "double induction # #" t "double\\s-+induction")
             )
           '(
             ("eapply (ltac)" "eap" "eapply #" t "eapply")
             ("eauto with arith (ltac)" "eawa" "eauto with arith" t)
             ("eauto with (ltac)" "eaw" "eauto with @{db}" t)
             ("eauto (ltac)" "ea" "eauto" t "eauto")
             ("econstructor (ltac)" "econs" "econstructor" t "econstructor")
             ("edestruct (ltac)" "edes" "edestruct " t  "edestruct")
             ("eexists (ltac)" "eex" "eexists" t "eexists")
             ("eleft (ltac)" "eleft" "eleft" t "eleft")
             ("elim using (ltac)" "elu" "elim # using #" t)
             ("elim (ltac)" "e" "elim #" t "elim")
             ("elimtype (ltac)" "elt" "elimtype" t "elimtype")
             ("enough (ltac)" "eng" "enough (#: #).\n{ #\n}" t "enough")
             ("erewrite (ltac)" "er" "erewrite #" t "erewrite")
             ("eright (ltac)" "erig" "eright" "eright")
             ("esplit (ltac)" "esp" "esplit" t "esplit")
             ("etransitivity (ltac)" "etr" "etransitivity" t "etransitivity")
             ;;     ("exact (ltac)" "exa" "exact" t "exact")
             ("exfalso (ltac)" "exf" "exfalso" t "exfalso")
             ("exists (ltac)" "ex" "exists #" t "exists")
             )
           '(
             ;;     ("fail (ltac)" "fa" "fail" nil)
             ("field (ltac)" "field" "field" t "field")
             ("false_hyp (ltac)" nil "false_hyp @{H} @{G}" t "false_hyp")
             ("firstorder (ltac)" "fsto" "firstorder" t "firstorder")
             ("firstorder with (ltac)" "fsto" "firstorder with #" t)
             ("firstorder with using (ltac)" "fsto" "firstorder # with #" t)
             ("fold (ltac)" "fold" "fold #" t "fold")
             ;;     ("fourier (ltac)" "four" "fourier" t "fourier")
             ("functional induction (ltac)" "fi" "functional induction @{f} @{args}" t "functional\\s-+induction")
             ("functional inversion (ltac)" "finv" "functional inversion @{H}" t "functional\\s-+inversion")
             )
           '(
             ("generalize dependent (ltac)" "gd" "generalize dependent #" t "generalize\\s-+dependent")
             ("generalize (ltac)" "g" "generalize #" t "generalize")
             )
           '(
             ("hnf (ltac)" "hnf" "hnf" t "hnf")
             )
           '(
             ("idtac (ltac)" "id" "idtac" nil "idtac") ; also in tacticals with abbrev id
             ("idtac \" (ltac)" "id\"" "idtac \"#\"")  ; also in tacticals
             )
           '(
             ("induction (ltac)" "ind" "induction #" t "induction")
             ("induction using (ltac)" "indu" "induction # using #" t)
             ("injection (ltac)" "inj" "injection #" t "injection")
             ("instantiate (ltac)" "inst" "instantiate" t "instantiate")
             ("intro (ltac)" "i" "intro" t "intro")
             ("intro after (ltac)" "ia" "intro # after #" t)
             ("intros (ltac)" "is" "intros #" t "intros")
             ("intros! (guess names) (ltac)" nil "intros #" nil nil coq-insert-intros)
             ("intros until (ltac)" "isu" "intros until #" t)
             ("intuition (ltac)" "intu" "intuition #" t "intuition")
             ("inversion (ltac)" "inv" "inversion #" t "inversion")
             ("inversion in (ltac)" "invi" "inversion # in #" t)
             ("inversion using (ltac)" "invu" "inversion # using #" t)
             ("inversion using in (ltac)" "invui" "inversion # using # in #" t)
             ("inversion_clear (ltac)" "invcl" "inversion_clear" t "inversion_clear")
             )
           '(
             ("lapply (ltac)" "lap" "lapply" t "lapply")
             ("lazy (ltac)" "lazy" "lazy beta delta [#] iota zeta" t "lazy")
             ("lazymatch with (ltac)" "lazym" "lazymatch # with\n| # => #\nend")
             ("lazy_match! with (ltac)" "lazy_m" "lazy_match! # with\n| # => #\nend")
             ("left (ltac)" "left" "left" t "left")
             ("lia (ltac)" nil "lia" t "lia")
             ("linear (ltac)" "lin" "linear" t "linear")
             ("load (ltac)" "load" "load" t "load")
             ("lra (ltac)" nil "lra" t "lra")
             )
           '(
             ("move after (ltac)" "mov" "move # after #" t "move")
             ("multimatch with (ltac)" "mm" "multimatch # with\n| # => #\nend")
             ("multi_match! with (ltac)" "multi_m" "multi_match! # with\n| # => #\nend")
             )
           '(
             ("native_compute (ltac)" "nac" "native_compute" t "native_compute")
             ("nia (ltac)" nil "nia" t "nia")
             ("now_show (ltac)" nil "now_show" t "now_show")
             ("nra (ltac)" nil "nra" t "nra")
             ("nsatz (ltac)" nil "nsatz" t "nsatz")
             )
           '(
             ("omega (ltac)" "o" "omega" t "omega")
             )
           '(
             ("pattern (ltac)" "pat" "pattern" t "pattern")
             ("pattern(s) (ltac)" "pats" "pattern # , #" t)
             ("pattern at (ltac)" "pata" "pattern # at #" t)
             ("pose (ltac)" "po" "pose ( # := # )" t "pose")
             ("prolog (ltac)" "prol" "prolog" t "prolog")
             ("psatz (ltac)" nil "psatz" t "psatz")
             )
           '(
             ("quote (ltac)" "quote" "quote" t "quote")
             ("quote [] (ltac)" "quote2" "quote # [#]" t)
             )
           '(
             ("red (ltac)" "red" "red" t "red")
             ("rapply (ltac)" "rap" "rapply #" t "rapply")
             ("refine (ltac)" "ref" "refine" t "refine")
             ;;      ("reflexivity (ltac)" "refl" "reflexivity #" t "reflexivity")
             ("remember (ltac)" "rem" "remember # as #" t "remember")
             ("rename into (ltac)" "ren" "rename # into #" t "rename")
             ("replace with (ltac)" "rep" "replace # with #" t "replace")
             ("replace with in (ltac)" "repi" "replace # with # in #" t)
             ("revert dependent (ltac)" "r" "revert dependent" t "revert\\s-+dependent")
             ("revert (ltac)" "r" "revert" t "revert")
             ("rewrite_all (ltac)" nil "rewrite_all" t "rewrite_all")
             ("rewrite_all <- (ltac)" nil "rewrite_all" t "rewrite_all")
             ("rewrite <- in (ltac)" "ri<" "rewrite <- # in #" t)
             ("rewrite <- (ltac)" "r<" "rewrite <- #" t)
             ("rewrite in (ltac)" "ri" "rewrite # in #" t)
             ("rewrite (ltac)" "r" "rewrite #" t "rewrite")
             ("right (ltac)" "rig" "right" t "right")
             ;;      ("ring (ltac)" "ring" "ring #" t "ring")
             ("romega (ltac)" nil "romega" t "romega")
             )
           '(
             ("set in * |- (ltac)" "seth" "set ( # := #) in * |-" t)
             ("set in * (ltac)" "set*" "set ( # := #) in *" t)
             ("set in |- * (ltac)" "setg" "set ( # := #) in |- *" t)
             ("set in (ltac)" "seti" "set ( # := #) in #" t)
             ("set (ltac)" "set" "set ( # := #)" t "set")
             ("setoid_replace with (ltac)" "strep2" "setoid_replace # with #" t "setoid_replace")
             ("setoid replace with (ltac)" "strep" "setoid replace # with #" t "setoid\\s-+replace")
             ("setoid_rewrite (ltac)" "strew" "setoid_rewrite #" t "setoid_rewrite")
             ("setoid rewrite (ltac)" "strew" "setoid rewrite #" t "setoid\\s-+rewrite")
             ("simpl (ltac)" "s" "simpl" t "simpl")
             ("simpl at (ltac)" "sa" "simpl # at #" t)
             ("simpl (all flags) (ltac)" "simpl" "simpl beta delta [#] iota zeta" t)
             ("simple destruct (ltac)" "sdes" "simple destruct" t "simple\\s-+destruct")
             ("simple inversion (ltac)" "sinv" "simple inversion" t "simple\\s-+inversion")
             ("simple induction (ltac)" "sind" "simple induction" t "simple\\s-+induction")
             ("simplify_eq (ltac)" "simeq" "simplify_eq @{hyp}" t "simplify_eq")
             ("specialize (ltac)" "spec" "specialize" t "specialize")
             ("split (ltac)" "sp" "split" t "split")
             ("split_Rabs (ltac)" "spra" "splitRabs" t "split_Rabs")
             ("split_Rmult (ltac)" "sprm" "splitRmult" t "split_Rmult")
             ("stepl (ltac)" "stl" "stepl #" t "stepl")
             ("stepl by (ltac)" "stlb" "stepl # by #" t)
             ("stepr (ltac)" "str" "stepr #" t "stepr")
             ("stepr by (ltac)" "strb" "stepr # by #" t)
             ("subst (ltac)" "su" "subst #" t "subst")
             ("symmetry (ltac)" "sy" "symmetry" t "symmetry")
             ("symmetry in (ltac)" "syi" "symmetry in #" t)
             )
           '(
             ;;    ("tauto (ltac)" "ta" "tauto" t "tauto")
             ("transitivity (ltac)" "trans" "transitivity #" t "transitivity")
             ("trivial (ltac)" "t" "trivial" t "trivial")
             ("trivial with (ltac)" "tw" "trivial with @{db}" t)
             )
           '(
             ("unfold (ltac)" "u" "unfold #" t "unfold")
             ("unfold(s) (ltac)" "us" "unfold # , #" t)
             ("unfold in (ltac)" "unfi" "unfold # in #" t)
             ("unfold at (ltac)" "unfa" "unfold # at #" t)
             )
           '(
             ("vm_compute (ltac)" "vmc" "vm_compute." t "vm_compute")
             )
           )
  )

(defvar jg-coq-tactics-ssreflect
  (append '(
            ("-- SSReflect")
            ("nat_congr (ssr)"    "ncongr"    "nat_congr" t "nat_congr")
            ("nat_norm (ssr)"     "nnorm"      "nat_norm" t "nat_norm")
            ("bool_congr (ssr)"   "bcongr"   "bool_congr" t "bool_congr")
            ("prop_congr (ssr)"   "prcongr"  "prop_congr" t "prop_congr")
            ("move (ssr)"         "m"              "move" t "move")
            ("pose (ssr)"         "po"             "pose # := #" t "pose")
            ("set (ssr)"          "set"             "set # := #" t "set")
            ("have (ssr)"         "hv" "have # : #" t "have")
            ("congr (ssr)"        "con" "congr #" t "congr")
            ("wlog (ssr)"         "wlog" "wlog : / #" t "wlog")
            ("without loss (ssr)" "wilog" "without loss #" t "without loss")
            ("unlock (ssr)"       "unlock" "unlock #" t "unlock")
            ("suffices (ssr)"     "suffices" "suffices # : #" t "suffices")
            ("suff (ssr)"         "suff" "suff # : #" t "suff")
            ("zify (ssr)" nil     "zify" t "zify")
            )
          )
  )

(defvar jg-coq-tactics-ltac2
  (append '(
            ("-- Ltac2")
            ("printf (ltac2)" "printf")
            )
          )
  )

(defvar jg-coq-tactics-mtac2
  (append '(
            ("-- Mtac2")

            )
          )
  )

(defvar jg-coq-tacticals
  (append '(
            ("jg")
            ("info" nil "info #" nil "info")
            ("first" nil "first [ # | # ]" nil "first")
            ("abstract" nil "abstract @{tac} using @{name}." nil "abstract")
            ("do" nil "do @{num} @{tac}" nil "do")
            ("idtac" nil "idtac")
            ("fail" "fa" "fail" nil "fail")
            ("repeat" nil "repeat #" nil "repeat")
            ("try" nil "try #" nil "try")
            ("tryif" "tryif" "tryif # then # else #" nil "tryif")
            ("progress" nil "progress #" nil "progress")
            ("|" nil "[ # | # ]" nil)
            ("||" nil "# || #" nil)
            ("last" "lst" nil t "last")
            )
          )
  )

(use-package! company-coq
  :after coq-mode
  :hook (coq-mode . company-coq-mode)
  :config
  (setq company-coq-disabled-features '(hello company-defaults spinner))

  (define-key coq-mode-map [remap company-complete-common] #'company-indent-or-complete-common)
  ;; `company-coq''s company defaults impose idle-completion on folks, so
  ;; we'll set up company ourselves. See
  ;; https://github.com/cpitclaudel/company-coq/issues/42
  (add-to-list 'company-coq-disabled-features 'company)
  )

(setq-hook! 'coq-mode-hook
  tab-width proof-indent
  comment-line-break-function nil
  code-shy-fold-patterns (list "%s-- %s %s" "%s-- %s %s")
  code-shy-block-depth 1
  )

(add-hook! 'coq-mode-hook
             #'coq-init-smie
             #'librarian-insert-minor-mode
             )

(speckler-setq! coq ()
  coq-prog-name "rocq"
  coq-prog-args '("repl")
  coq-compile-before-require t
  coq-accept-proof-using-suggestion 'never
  coq-tactics-db (append jg-coq-tactics-ltac
                         jg-coq-tactics-ssreflect
                         jg-coq-tactics-ltac2
                         jg-coq-tactics-mtac2
                         )
  coq-tacticals-db jg-coq-tacticals
  coq-commands-db (append jg-coq-vernac)
  )
(speckler-add! popup ()
  '(coq
    ("^\\*\\(?:response\\|goals\\)\\*" :ignore t)
    )
  )
(speckler-add! doc-lookup ()
  `(company-coq-mode
    :definition    #'company-coq-jump-to-definition
    :references    #'company-coq-grep-symbol
    :documentation #'company-coq-doc
    )
  )
(speckler-add! auto-modes ()
  '(coq
    ("\\.v\\'" . coq-mode)
    )
  )

(speckler-add! fold ()
  `(coq
    :modes coq-mode
    :priority 25
    :triggers (:close     #'outline-hide
               :close-all #'jg-fold-outline-hide-sublevels
               :open      #'outline-toggle-children
               :open-all  #'jg-fold-outline-show-children
               :open-rec  #'outline-show-subtree
               :toggle    #'outline-toggle-children
               )
    )
  )
(speckler-add! rotate-text ()
  '(coq-mode
    :symbols (("Set" "Unset")
              ("Import" "Export")
              ("Module" "Section" "End")
              ("Set" "Prop" "Type" "Sort")
              )
    )
  )
;;-- Footer
;; Copyright (C) 2024 john
;;
;; Author:     john <https://github.com/jgrey4296>
;; Maintainer: john <john@john-UM700>
;; Created:    September 09, 2024
;; Modified:   September 09, 2024
;; Version: 0.0.1
;; Keywords:
;; Homepage: https://github.com/jgrey4296
;; Package-Requires: ((emacs "24.3"))
;; Package written on: ((emacs 29.1))
;;
;; This file is not part of GNU Emacs.
;;
;;-- end Footer
;;; +proof-general.el ends here
