(package! acab-ide :recipe `(:local-repo ,(expand-file-name  "~/github/python/acab/emacs") :files ("*.el" "data-struct/*.el" "modes/*.el" "util/*.el")))
(package! cl-lib :built-in t)
(package! font-lock+ :recipe (:host github :repo "emacsmirror/font-lock-plus"))
(package! helm)
(package! parsec)
