(package! parsec)
(package! font-lock+ :recipe (:host github :repo "emacsmirror/font-lock-plus"))
(package! helm)
(package! cl-lib)
(package! acab-mode :recipe (:local-repo "~/.doom.d/packages/acab-mode"))
