verbosity                = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"

[tool.doot]
say-on-exit   = false
glob_ignores  = ['.git', '.DS_Store', "__pycache__"]
subtask-sleep = 1
batch-sleep   = 1

[tool.doot.directories]
modules  = "modules"
packages = "packages"
temp     = ".temp"
org      = "org"
tools    = "terminal/tool_configs"
cron     = "terminal/cron"
brew     = "terminal/brew"
bash     = "terminal/bash_setup"
