verbosity               = 2

[tool.doot]
say-on-exit = false
glob_ignores = ['.git', '.DS_Store', "__pycache__"]

[tool.doot.directories]
src     = "src"
codegen = "_codegen"
temp    = ".temp"
build   = "build"
docs    = "docs"
data    = "data"
