verbosity                = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"
subtask = { sleep = 1 }
batch   = { sleep = 1 }
notify  = { say-on-exit = false }

[logging]
stream  = { level="INFO", format  = "{levelname:<8} : {message}", filters = ["doot", "bkmkorg"] }
file    = { level="DEBUG", format = "{levelname:<8} : {message:<20} :|: (module:{module} line:{lineno} fn:{funcName})", filters =  ["doot", "bkmkorg"] }
printer = { level="INFO",    format="{message}", colour=true, target="stdout", filter=[] }

[logging.subprinters]
[logging.extra]

[globbing]
ignores  = ['.git', '.DS_Store', "__pycache__"]

[[directories]]
modules      = "modules"
packages     = "packages"
temp         = ".temp"
org          = "org"
tools        = "templates/tools/"
bash         = "bash"
man          = "man/main"
man_markdown = "man/markdown"
