;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el
;; (package! evil            :pin "6e30037fdc6a275d78d6b82d89bd8e47bcf4d4e3")

;; package disallowing
(package! org-brain       :disable t)
(package! org-cliplink    :disable t)
(package! org-contacts    :disable t)
(package! org-contrib     :disable t)
(package! org-crypt       :disable t)
(package! org-drill       :disable t)
(package! org-passwords   :disable t)
(package! org-pomodoro    :disable t)
(package! org-projectile  :disable t)
(package! org-tree-slide  :disable t)
(package! org-unit-test   :disable t)
(package! orgit-forge     :disable t)
(package! outline-toc     :disable t)
(package! server          :disable t)
(package! toc-org         :disable t)
(package! hydra :disable t)


;; recipes
(package! agda-input            :recipe (:host github :repo "agda/agda" :files ("src/data/emacs-mode/agda-input.el") :nonrecursive t))
(package! agda2-mode            :recipe (:host github :repo "agda/agda" :files ("src/data/emacs-mode/*.el" (:exclude "agda-input.el")) :nonrecursive t))
(package! code-review           :recipe (:files ("graphql" "code-review*.el")))
(package! company-graphql       :recipe (:host github :repo "thaenalpha/company-graphql"))
(package! company-mlton         :recipe (:host github :repo "MatthewFluet/company-mlton" :files ("*.el" "*.basis")))
(package! compat                :recipe (:host github :repo "emacs-compat/compat"))
(package! doom-snippets         :recipe (:host github :repo "doomemacs/snippets" :files (:defaults "*")))
(package! dune                  :recipe (:host github :repo "ocaml/dune" :files ("editor-integration/emacs/*.el")))
(package! evil-markdown         :recipe (:host github :repo "Somelauw/evil-markdown"))
(package! evil-org              :recipe (:host github :repo "hlissner/evil-org-mode"))
(package! evil-quick-diff       :recipe (:host github :repo "rgrinberg/evil-quick-diff"))
(package! evil-textobj-anyblock :recipe (:host github :repo "willghatch/evil-textobj-anyblock" :branch "fix-inner-block"))
(package! flycheck-moonscript   :recipe (:host github :repo "hlissner/emacs-flycheck-moonscript"))
(package! font-lock+            :recipe (:host github :repo "emacsmirror/font-lock-plus"))
(package! ghub                  :recipe (:host github :repo "magit/ghub"))
(package! git-timemachine       :recipe (:host github :repo "emacsmirror/git-timemachine"))
(package! ivy-taskrunner        :recipe (:host github :repo "emacs-taskrunner/ivy-taskrunner"))
(package! ob-fsharp             :recipe (:host github :repo "elken/ob-fsharp"))
(package! ob-racket             :recipe (:host github :repo "DEADB17/ob-racket"))
(package! ocamlformat           :recipe (:host github :repo "ocaml-ppx/ocamlformat" :files ("emacs/*.el")))
(package! org-contacts          :recipe (:host nil :type git :repo "https://repo.or.cz/org-contacts.git"))
(package! org-contrib           :recipe (:host github :repo "emacsmirror/org-contrib"))
(package! org-passwords         :recipe (:host github :repo "alfaromurillo/org-passwords.el"))
(package! org-yt                :recipe (:host github :repo "TobiasZawada/org-yt"))
(package! ox-hugo               :recipe (:host github :repo "kaushalmodi/ox-hugo" :nonrecursive t))
(package! python-mode           :recipe (:host gitlab :repo "python-mode-devs/python-mode" :branch "master"))
(package! sclang                :recipe `(:local-repo ,(expand-file-name "~/github/__libs/music/scel/el")))
(package! string-inflection     :recipe (:branch "main"))
(package! transient             :recipe (:host github :repo "magit/transient" :branch "main"))
(package! ts-fold               :recipe (:host github :repo "emacs-tree-sitter/ts-fold"))
(package! vertico               :recipe (:host github :repo "minad/vertico" :files ("*.el" "extensions/*.el")))
;; (package! chuck-mode
;;   :recipe `(:local-repo ,(expand-file-name "packages/chuck-mode" doom-user-dir)))

;; pins
(package! agda-input                   :pin "bb7603d19781e4da2dc702a5a1611fd59e5325f2")
(package! agda2-mode                   :pin "bb7603d19781e4da2dc702a5a1611fd59e5325f2")
(package! cond-let                     :pin "288b7d36563223ebaf64cb220a3b270bdffb63f1")
(package! doom-themes                  :pin "b5ff201f4bea4286e9ed015a2043cf2394182232")
(package! eglot-jl                     :pin "2e04597223553a369dd5b6520b6365b41e6ea508")
(package! evil-goggles                 :pin "8f20a16e74016f37ad76dc4f2230d9b00c6df3c2")
(package! evil-terminal-cursor-changer :pin "12ea9c0438c67e560b3866dc78b5c7d1d93f8cc5")
(package! fstar-mode                   :pin "ab0697b9474f36942a12a4b2a75251c247c18e9e")
(package! idris-mode                   :pin "c96f45d1b8fad193f09fb6139da17092003b5e74")
(package! julia-mode                   :pin "7aafa8e77df64a47fa4729a0c1ea572b5bc8e30e")
(package! julia-repl                   :pin "57a15dfafed680ad7d81f779d414e8cb6717417c")
(package! lsp-julia                    :pin "d6688bb131ff4a5a0201f6d3826ef0b018265389")
(package! minimap                      :pin "ed7490652a676c0510ed57d5366c445de20a370b")
(package! org                          :pin "3ff21c713851f1ecbbcdc80363f1449f43cff2fa")
(package! request                      :pin "01e338c335c07e4407239619e57361944a82cb8a")
(package! solaire-mode                 :pin "8af65fbdc50b25ed3214da949b8a484527c7cc14")
(package! tree-sitter-langs            :pin "213b1c4db852a97480e029453af869ff1a0764e0")
(package! ts-fold                      :pin "01c9ecaaa89966cdcd250ac37c24a9c9f530b725")
(package! ts-fold                      :pin "01c9ecaaa89966cdcd250ac37c24a9c9f530b725")
(package! xclip                        :pin "a1ac607f75a250dddf49866918bb493884451130")
(package! yaml-mode                    :pin "3fcb36d6039bef57e2a0f6e24c51f623c0bf5fb7")
(package! transient :pin "43cbef8539e3c7398d0280958b42f94dac7ea7b4")
(package! magit     :pin "f0ead86")
;; personal

(package! spec-handling          :recipe (:host github :repo "jgrey4296/spec-handling"))
;; (package! acab-ide               :recipe `(:local-repo ,(expand-file-name  "~/github/python/acab/emacs") :files ("*.el" "data-struct/*.el" "modes/*.el" "util/*.el")))
(package! agentspeak-mode        :recipe (:host github :repo "jgrey4296/agentspeak-mode"))
(package! blood-bind             :recipe (:host github :repo "jgrey4296/blood-bind" :branch "alt" :files ("src/*.el" "src/*/*.el" (:exclude "*/__tests/*")) :build (:not compile)))
(package! carousel-minor-mode    :recipe (:host github :repo "jgrey4296/carousel-minor-mode"))
(package! ceptre-mode            :recipe (:host github :repo "jgrey4296/misc-modes" :files ("major-modes/ceptre-mode/ceptre-mode.el") :local-repo "misc-modes"))
(package! ob-erlang             :recipe (:host github :repo "jgrey4296/misc-modes" :files ("org-babels/ob-erlang.el") :local-repo "misc-modes"))
(package! code-shy-minor-mode    :recipe (:host github :repo "jgrey4296/code-shy-minor-mode"))
(package! definition-lookup-mode :recipe (:host github :repo "jgrey4296/definition-lookup-mode"))
(package! evil-escape-hook       :recipe (:host github :repo "jgrey4296/evil-escape-hook"))
(package! evil-states-plus       :recipe (:host github :repo "jgrey4296/evil-states-plus" :includes (conflict-merge-state)))
(package! evil-states-plus       :recipe (:host github :repo "jgrey4296/evil-states-plus" :includes (mapspace-state spechar-state)))
(package! evil-states-plus       :recipe (:host github :repo "jgrey4296/evil-states-plus" :includes (move-states)))
(package! faster-whichkey        :recipe (:host github :repo "jgrey4296/faster-whichkey"))
(package! instal-mode            :recipe (:host github :repo "jgrey4296/instal-stable"))
(package! jacamo-mode            :recipe (:host github :repo "jgrey4296/jacamo-mode"))
(package! jg-company             :recipe (:host github :repo "jgrey4296/misc-modes" :files ("minor-modes/jg-company/*.el")))
(package! librarian              :recipe (:host github :repo "jgrey4296/librarian"))
(package! librarian-tag-helm     :recipe (:host github :repo "jgrey4296/misc-modes" :files ("minor-modes/librarian-tag-helm/*.el") :local-repo "misc-modes"))
(package! librarian-tag-ivy      :recipe (:host github :repo "jgrey4296/misc-modes" :files ("minor-modes/librarian-tag-ivy/*.el") :local-repo "misc-modes"))
(package! logview-mode           :recipe (:host github :repo "jgrey4296/misc-modes" :files ("major-modes/logview-mode/*.el")))
(package! macro-tools            :recipe (:host github :repo "jgrey4296/macro-tools"))
(package! music-minor-mode       :recipe (:host github :repo "jgrey4296/misc-modes" :files ("minor-modes/music-minor-mode/*.el")))
(package! ob-ceptre              :recipe (:host github :repo "jgrey4296/misc-modes" :files ("org-babels/ob-ceptre.el") :local-repo "misc-modes"))
(package! ob-clips               :recipe (:host github :repo "jgrey4296/misc-modes" :files ("org-babels/ob-clips.el") :local-repo "misc-modes"))
(package! ob-plantuml            :recipe (:host github :repo "jgrey4296/misc-modes" :files ("org-babels/ob-plantuml.el") :local-repo "misc-modes"))
(package! ob-z3                  :recipe (:host github :repo "jgrey4296/misc-modes" :files ("org-babels/ob-z3.el") :local-repo "misc-modes"))
(package! opa-mode               :recipe (:host github :repo "jgrey4296/opa-mode"))
(package! org-unit-test          :recipe (:host github :repo "jgrey4296/misc-modes" :files ("minor-mode/org-unit-test/*.el")))
(package! ox-epub                :recipe (:host github :repo "jgrey4296/misc-modes" :files ("ox-epub/*.el") :local-repo "misc-modes"))
(package! pdf-meta-mode          :recipe (:host github :repo "jgrey4296/misc-modes" :files ("major-modes/pdf-meta-mode/*.el") :local-repo "misc-modes"))
(package! project-zimmerframe    :recipe (:host github :repo "jgrey4296/project-zimmerframe"))
(package! quote-mode             :recipe (:host github :repo "jgrey4296/quote-mode"))
(package! rawtag-mode            :recipe (:host github :repo "jgrey4296/misc-modes" :files ("major-modes/tag-modes/rawtag-mode.el") :local-repo "misc-modes"))
(package! soar-mode              :recipe (:host github :repo "jgrey4296/soar-mode"))
(package! subfile-mode           :recipe (:host github :repo "jgrey4296/misc-modes" :files ("major-modes/tag-modes/subfile-mode.el") :local-repo "misc-modes"))
(package! timeline-mode          :recipe (:host github :repo "jgrey4296/timeline-mode"))
(package! flycheck-toml          :recipe (:host github :repo "jgrey4296/flycheck-toml"))
