;; -*- no-byte-compile: t; -*-
;;; editor/evil/packages.el

(package! evil)
(package! evil-anzu)
(package! evil-args)
(package! evil-easymotion)
(package! evil-embrace)
(package! evil-escape :recipe (:host github :repo "hlissner/evil-escape"))
(package! evil-exchange)
(package! evil-iedit-state)
(package! evil-indent-plus)
(package! evil-lion)
(package! evil-nerd-commenter)
(package! evil-numbers)
(package! evil-quick-diff :recipe (:host github :repo "rgrinberg/evil-quick-diff"))
(package! evil-quickscope)
(package! evil-snipe)
(package! evil-string-inflection)
(package! evil-surround)
(package! evil-textobj-anyblock :recipe (:host github :repo "willghatch/evil-textobj-anyblock" :branch "fix-inner-block"))
(package! evil-traces)
(package! evil-visual-mark-mode)
(package! evil-visualstar)

(package! exato)

(when (modulep! :ui neotree)
  (package! neotree)
  (autoload 'neotree-make-executor "neotree" nil nil 'macro)
  )
(package! evil-collection)
