(package! ob-prolog)
(package! ob-ccalc :recipe `(:local-repo ,(expand-file-name "~/.doom.d/packages/ob-ccalc")))
(package! ob-clingo :recipe `(:local-repo ,(expand-file-name "~/.doom.d/packages/ob-clingo")))
(package! proof-general)
(package! clips-mode)
