;; -*- no-byte-compile: t; -*-
;;; util/text/packages.el
(package! academic-phrases)
(package! adaptive-wrap)
(package! avy)
(package! exec-path-from-shell)
(package! f)
(package! flycheck)
(package! fsm)
(package! helm-wordnet)
(package! license-templates)
(package! lint-result-mode :recipe `(:local-repo ,(expand-file-name "packages/major-modes/lint-result-mode" doom-user-dir)))
(package! lorem-ipsum)
(package! neotree)
(package! origami)
(package! rotate-text)
(package! shell-pop)
(package! timeline-mode :recipe `(:local-repo ,(expand-file-name "packages/major-modes/timeline-mode" doom-user-dir)))
(package! undo-fu)
(package! vlf)
(package! vundo)

;; (package! objed)
