;;; emacs/jg-tag/+funcs.el -*- lexical-binding: t; -*-

(defun +jg-tag-open-random-untagged-twitter ()
  (interactive)
  (let* ((av-dirs (f-entries jg-tag-loc-twitter
                                   #'(lambda (x) (cond ((f-file? x) nil)
                                                  (t t)))))
         (chosen-dir (seq-random-elt av-dirs))
         (av-orgs (f-files chosen-dir #'(lambda (x) (f-ext? x "org"))))
         (chosen-org (seq-random-elt av-orgs))
        )
    (find-file chosen-org)
    )
  )
(defun +jg-tag-split-tags()
  (interactive)
  (goto-char (point-min))
  (let ((letter ?a)
        (end-letter (+ 1 ?z))
        (beg (point-min))
        (fst t)
        subs)
    (while (and (not (equal letter end-letter))
                (re-search-forward (format "^%s" (char-to-string letter)) nil nil))
      (setq subs (buffer-substring beg (- (point) 1)))
      (with-output-to-temp-buffer (if fst "misc.tags" (format "%s.tags" (char-to-string (- letter 1))))
        (princ subs)
        )
      (setq beg (- (point) 1)
            letter (+ letter 1)
            fst nil)
      )
    (setq subs (buffer-substring (- (point) 1) (point-max)))
    (with-output-to-temp-buffer "z.tags"
      (princ subs)
      )
    )
  )
