(package! helm)
(package! dash)
(package! org)
(package! evil)
(package! hydra)
(package! cl-lib :built-in t)
(package! ivy)
(package! rawtag-mode :recipe `(:local-repo ,(expand-file-name "packages/major-modes/rawtag-mode" doom-user-dir)))
