" https://www.freecodecamp.org/news/vimrc-configuration-guide-customize-your-vim-editor
" https://vimdoc.sourceforge.net/htmldoc/usr_41.html
" Disable compatibility with vi
set nocompatible

" from: https://stackoverflow.com/questions/23012391
set viminfo=%,<800,'10,/50,:100,h,f0,n~/.cache/.viminfo
"           | |    |   |   |    | |  + viminfo file path
"           | |    |   |   |    | + file marks 0-9,A-Z 0=NOT stored
"           | |    |   |   |    + disable 'hlsearch' loading viminfo
"           | |    |   |   + command-line history saved
"           | |    |   + search history saved
"           | |    + files marks saved
"           | + lines saved each register (old name for <, vi6.2)
"           + save/restore buffer list

" Enable type file detection
filetype on

" Enable plugins
filetype plugin on

" Load an indent file
filetype indent on

syntax on
set number
set cursorline
" set cursorcolumn
set shiftwidth=4
set tabstop=4
set expandtab
set scrolloff=10
set nowrap
set incsearch
set ignorecase
set showcmd
set showmode
set showmatch
set hlsearch
set wildmenu
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

noremap <LeftMouse>    <Nop>
noremap <RightMouse>   <Nop>
noremap <MiddleMouse>  <Nop>
noremap <LeftRelease>  <Nop>
noremap <RightRelease> <Nop>
noremap <LeftDrag>     <Nop>
noremap <RightDrag>    <Nop>
noremap <MiddleDrag>   <Nop>
noremap <2-LeftMouse>  <Nop>
noremap <2-RightMouse> <Nop>
noremap <3-LeftMouse>  <Nop>
noremap <3-RightMouse> <Nop>
noremap <4-LeftMouse>  <Nop>
noremap <4-RightMouse> <Nop>
noremap <X1Mouse>      <Nop>
noremap <X2Mouse>      <Nop>
noremap <X1Release>    <Nop>
noremap <X2Release>    <Nop>
noremap <X1Drag>       <Nop>
noremap <X2Drag>       <Nop>

imap jf <Esc>
imap jk <Esc>

function MaybeEnd()
   if col(".") == (col("$") - 1)
       echo "At end"
       exe ":normal 0"
   else
       echo "Not At End"
       exe ":normal $"
   endif
endfunction

nmap <Bslash> :call MaybeEnd()<CR>

let mapleader=" "
nmap <SPACE> <Nop>
nmap <SPACE>wj <C-W>j
nmap <SPACE>wk <C-W>k
nmap <SPACE>wl <C-W>l
nmap <SPACE>wh <C-W>h
nmap <SPACE>wd <C-W>q
nmap <SPACE>w<Bslash> :vsplit<CR>
nmap <SPACE>w<Bar> :split<CR>
