# -*- mode:conf-toml; -*-

[pelican]
DEFAULT_METADATA       = {}
DEFAULT_LANG           = 'en'
PORT                   =  8000
BIND                   =  '127.0.0.1'
# READERS                = { ".md"="MarkdownReader" }

[paths]
PATH                        = '.'
OUTPUT_PATH                 = '.site'
THEME                       = './_theme'
CACHE_PATH                  = 'cache'

##-- site.settings

[site.settings]
ARTICLE_PERMALINK_STRUCTURE = ''
DEFAULT_ORPHANS             = 0
DEFAULT_PAGINATION          = false
DOCUTILS_SETTINGS           = {}
EXTRA_PATH_METADATA         = {}
FILENAME_METADATA           = '(?P<date>\d{4}-\d{2}-\d{2}).*'
INDEX_SAVE_AS               = 'index.html'
LOCALE                      = []  # defaults to user locale
PAGE_TRANSLATION_ID         = 'slug'
ARTICLE_TRANSLATION_ID      = 'slug'
PATH_METADATA               = ''

[site.settings.datetime]
DATE_FORMATS                = {}
DEFAULT_DATE_FORMAT         = '%a %d %B %Y'
TIMEZONE                    = 'Europe/Rome'

[site.setup]
SITENAME                    = 'Mostly Harmless'
SITEURL                     = 'jgrey4296.github.io'
AUTHOR                      = 'john grey'
INTRASITE_LINK_REGEX        =  '[{|](?P<what>.*?)[|}]'
LINKS                       = []
SOCIAL                      = []

[site.static]
STATIC_PATHS                = ['images', 'bibliography']
STATIC_EXCLUDES             = []

[site.articles]
DEFAULT_CATEGORY       =  'misc'
ARTICLE_PATHS          =  ["_posts", "_resources"]
ARTICLE_EXCLUDES       =  []
FORMATTED_FIELDS       =  ['summary']
SUMMARY_END_SUFFIX     =  '…'
SUMMARY_MAX_LENGTH     =  50

[site.pages]
PAGE_EXCLUDES               =  ['_theme']
PAGE_PATHS                  =  ['pages']

##-- end site.settings

##-- text and templates
[site.theme]
THEME_STATIC_DIR       = 'theme'
THEME_STATIC_PATHS     = ['static']
CSS_FILE               = 'main.css'

[site.templates]
TEMPLATE_PAGES            = {}
TEMPLATE_EXTENSIONS       = ['.html']
THEME_TEMPLATES_OVERRIDES = []
DIRECT_TEMPLATES          = ['index', 'tags', 'categories', 'archives']
PAGINATED_TEMPLATES       = {'index' = false, 'tag' = false, 'category' = false,  'author' = false, 'resources'= true}

[rst]
PYGMENTS_RST_OPTIONS           =  {}

[markdown]
OUTPUT_FORMAT                  =  'html5'

[markdown.extension_configs]
markdown.extensions.codehilite = {'css_class' = 'highlight'}
markdown.extensions.extra      = {}
markdown.extensions.meta       = {}

##-- end text and templates

##-- build.config
[build.core]
OUTPUT_SOURCES_EXTENSION = '.text'
DISQUS_SITENAME          = ""
GOOGLE_ANALYTICS         = ""
OUTPUT_RETENTION         =  []
IGNORE_FILES             =  ['.#*']

[build.options]
OUTPUT_SOURCES                 = false
DELETE_OUTPUT_DIRECTORY        = false
STATIC_EXCLUDE_SOURCES         = true
FEED_ALL_ATOM                  = false
CATEGORY_FEED_ATOM             = false
TRANSLATION_FEED_ATOM          = false
AUTHOR_FEED_ATOM               = false
AUTHOR_FEED_RSS                = false
RELATIVE_URLS                  = true
RSS_FEED_SUMMARY_ONLY          = true
STATIC_CREATE_LINKS            = true
USE_FOLDER_AS_CATEGORY         = true
WITH_FUTURE_DATES              = true
NEWEST_FIRST_ARCHIVES          = true
REVERSE_CATEGORY_ORDER         = false
DISPLAY_PAGES_ON_MENU          = true
DISPLAY_CATEGORIES_ON_MENU     = true
STATIC_CHECK_IF_MODIFIED       = false

[feeds]
FEED_ALL_ATOM                  = 'feeds/all.atom.xml'
CATEGORY_FEED_ATOM             = 'feeds/{slug}.atom.xml'
AUTHOR_FEED_ATOM               = 'feeds/{slug}.atom.xml'
AUTHOR_FEED_RSS                = 'feeds/{slug}.rss.xml'
TRANSLATION_FEED_ATOM          = 'feeds/all-{lang}.atom.xml'
FEED_MAX_ITEMS                 = 100

##-- end build.config

##-- jinja
[jinja]
JINJA_FILTERS                          =  {}
JINJA_GLOBALS                          =  {}
JINJA_TESTS                            =  {}

[jinja.JINJA_ENVIRONMENT]
trim_blocks   = true
lstrip_blocks = true
extensions    = ['jinja2.ext.debug']

##-- end jinja

##-- pelican settings
[logging]
LOG_FILTER                             =  []

[typogrify]
TYPOGRIFY                              =  false
TYPOGRIFY_IGNORE_TAGS                  =  []
TYPOGRIFY_DASHES                       =  'default'

[slugify]
SLUG_REGEX_SUBSTITUTIONS               =  [
 ["[^\\w\\s-]", ''],  # remove non-alphabetical/whitespace/'-' chars
 ["(?u)\\A\\s*", ''], # strip leading whitespace
 ["(?u)\\s*\\Z", ''], # strip trailing whitespace
 ["[-\\s]+",    '-'],   # reduce multiple whitespace or '-' to single '-'
]
SLUGIFY_SOURCE                         =  'title'
SLUGIFY_USE_UNICODE                    =  false
SLUGIFY_PRESERVE_CASE                  =  false

[cache]
CACHE_CONTENT                          = false
LOAD_CONTENT_CACHE                     = false
GZIP_CACHE                             = true
CONTENT_CACHING_LAYER                  = 'reader'
CHECK_MODIFIED_METHOD                  = 'mtime'
WRITE_SELECTED                         = []

##-- end pelican settings

##-- urls
[[site.urls]]
ARTICLE_URL                            =  '{slug}.html'
ARTICLE_SAVE_AS                        =  '{slug}.html'
ARTICLE_ORDER_BY                       =  'reversed-date'
ARTICLE_LANG_URL                       =  '{slug}-{lang}.html'
ARTICLE_LANG_SAVE_AS                   =  '{slug}-{lang}.html'
DRAFT_URL                              =  'drafts/{slug}.html'
DRAFT_SAVE_AS                          =  'drafts/{slug}.html'
DRAFT_LANG_URL                         =  'drafts/{slug}-{lang}.html'
DRAFT_LANG_SAVE_AS                     =  'drafts/{slug}-{lang}.html'

[[site.urls]]
PAGE_URL                               =  'pages/{slug}.html'
PAGE_SAVE_AS                           =  'pages/{slug}.html'
PAGE_ORDER_BY                          =  'basename'
PAGE_LANG_URL                          =  'pages/{slug}-{lang}.html'
PAGE_LANG_SAVE_AS                      =  'pages/{slug}-{lang}.html'

[[site.urls]]
DRAFT_PAGE_URL                         =  'drafts/pages/{slug}.html'
DRAFT_PAGE_SAVE_AS                     =  'drafts/pages/{slug}.html'
DRAFT_PAGE_LANG_URL                    =  'drafts/pages/{slug}-{lang}.html'
DRAFT_PAGE_LANG_SAVE_AS                =  'drafts/pages/{slug}-{lang}.html'

[[site.urls]]
STATIC_URL                             =  '{path}'
STATIC_SAVE_AS                         =  '{path}'

[[site.urls]]
CATEGORY_URL                           =  'category/{slug}.html'
CATEGORY_SAVE_AS                       =  'category/{slug}.html'

[[site.urls]]
TAG_URL                                =  'tag/{slug}.html'
TAG_SAVE_AS                            =  'tag/{slug}.html'

[[site.urls]]
AUTHOR_URL                             =  'author/{slug}.html'
AUTHOR_SAVE_AS                         =  'author/{slug}.html'

[[site.urls]]
YEAR_ARCHIVE_URL                       =  ''
YEAR_ARCHIVE_SAVE_AS                   =  ''
MONTH_ARCHIVE_URL                      =  ''
MONTH_ARCHIVE_SAVE_AS                  =  ''
DAY_ARCHIVE_URL                        =  ''
DAY_ARCHIVE_SAVE_AS                    =  ''

##-- end urls
