## __sphinx.toml -*- mode: conf-toml -*-
[sphinx]

[sphinx.general]
project                           = ""                         # string
author                            = "jgrey"                    # string
copyright                         = ["2024, jgrey"]            # list<str>
version                           = "0.1"                      # str
release                           = "0.1"                      # str
# today                           = ""                         # str
today_fmt                         = "%B %d %Y"                 # the real default is locale-dependent
language                          = 'en'                       # str
needs_sphinx                      = "1.0"                      # str
extensions                        = ["sphinx.ext.duration"]

[sphinx.general.needs_extensions]


[sphinx.builder.html]
html_theme                            = "classic" # str
html_title                            = "test"
html_short_title                      = "test"
html_logo                             = ""
html_favicon                          = ""
html_last_updated_fmt                 = "%b %d %Y"
html_theme_paths                      = []
html_static_path                      = ["_static"]
html_extra_path                       = []
html_domain_indices                   = true
html_use_index                        = true
html_split_index                      = false
html_show_sourcelink                  = true
html_show_sphinx                      = true
html_show_copyright                   = false
html_use_opensearch                   = ""
html_file_suffix                      = ".html"
html_search_language                  = "en"
# html_search_scorer                    = "scorer.js"
html_help_basename                    = "testdoc"

[sphinx.builder.html.html_theme_options]
[sphinx.builder.html.html_search_options]
[sphinx.builder.html.html_sidebars]
[sphinx.builder.html.html_additional_pages]

[sphinx.paths]
sys_paths                        = ["."]                                   # list<str>
locale_dirs                      = ['locales']                          # list
figure_language_filename         = "{root}.{language}{ext}"             # str
templates_path                   = ["_templates"]                        # list<str>

[sphinx.templates]
root_doc                         = "index" # str
template_bridge                  = ""      # str

[sphinx.patterns]
exclude_patterns                = []     # list<str>
include_patterns                = ["**"] # list<Str>

[sphinx.parsing]
source_suffix                    = ['.rst'] # list<str>
source_encoding                  = 'utf-8-sig'                    # str
# source_parsers                   = []                             # TODO list<tuple[importStr, override]>
primary_domain                   = 'py'                           #
gettext_allow_fuzzy_translations = false # bool
translation_progress_classes     = false # ENUM(true, false, 'translated', 'untranslated'))

[sphinx.parsing.mapping]
# ".rst" = "restructuredtext"

[sphinx.options]
add_function_parentheses        = true     # bool
add_module_names                = true     # bool
keep_warnings                   = false    # bool
modindex_common_prefix          = []       # bool
option_emphasise_placeholders   = false    # bool
show_authors                    = false    # bool
suppress_warnings               = []       # bool
toc_object_entries              = true     # bool
toc_object_entries_show_parents = 'domain' # ENUM('domain', 'all', 'hide'))

[sphinx.highlight]
highlight_language              = 'default' # str
pygments_style                  = "sphinx"  # str

[sphinx.highlight.highlight_options]

[sphinx.reST]
# default_role                    = "" # str
maximum_signature_line_length   = -1    # int
trim_footnote_reference_space   = false # bool
trim_doctest_flags              = true  # bool

[sphinx.rst]
rst_epilog                      = "" # str
rst_prolog                      = "" # str

[sphinx.nitpicky]
nitpicky                        = false # bool
nitpick_ignore                  = [] # list
nitpick_ignore_regex            = [] # list

[sphinx.numfig]
numfig                          = false # list
numfig_secnum_depth             = 1    # int
[sphinx.numfig.numfig_format]

[sphinx.math]
math_number_all                 = false # bool
math_numfig                     = true  # bool
math_eqref_format               = ""    # str

[sphinx.web]
tls_verify                      = true                                       # bool
tls_cacerts                     = ""                                         # path
user_agent                      = "Sphinx.X.Y.Z requests.X.Y.Z python/X.Y.Z" # str

[sphinx.docutils]
smartquotes                     = true # bool
smartquotes_action              = "qDe" # str

[sphinx.docutils.smartquotes_excludes]
languages = ['ja']
builders  = ['man', 'text']

[sphinx.builder]

[sphinx.builder.latex]
papersize      = "letterpaper"
pointsize      = "10pt"
preamble       = ""
figure_align   = "htbp"

documents      = [] # list<tuple[source start target title author docclass]>
logo           = ""
show_pagerefs  = false
show_urls      = false
appendices     = []
domain_indices = true
[sphinx.builder.dirhtml]
[sphinx.builder.singlehtml]
[sphinx.builder.htmlhelp]
[sphinx.builder.epub]
[sphinx.builder.text]
[sphinx.builder.doctest]
[sphinx.builder.xml]

[sphinx.builder.man]
manpages_url                        = "" # str
man_pages                           = [] # list<tuple[source start name descrip authors section]>
man_show_urls                       = false

[sphinx.builder.texinfo]
texinfo_documents        = [] # list<tuple[source start target title author menu desc category]>
texinfo_appendices       = []
texinfo_domain_indices   = true
texinfo_show_urls        = 'footnote' # "no" | 'footnote' | 'inline'
texinfo_no_defaultmenu   = false
texinfo_cross_references = false

[sphinx.ext] # TODO extensions

[sphinx.ext.autodoc] # https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html
[sphinx.ext.autosectionlabel] # https://www.sphinx-doc.org/en/master/usage/extensions/autosectionlabel.html
[sphinx.ext.autosummary] # https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html
autosummary_generate = true

[sphinx.ext.coverage]            # https://www.sphinx-doc.org/en/master/usage/extensions/coverage.html
[sphinx.ext.doctest]             # https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html
[sphinx.ext.duration]            # https://www.sphinx-doc.org/en/master/usage/extensions/duration.html
[sphinx.ext.extlinks]            # https://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html
[sphinx.ext.githubpages]         # https://www.sphinx-doc.org/en/master/usage/extensions/githubpages.html
[sphinx.ext.graphviz]            # https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html
[sphinx.ext.ifconfig]            # https://www.sphinx-doc.org/en/master/usage/extensions/ifconfig.html
[sphinx.ext.imgconverter]        # https://www.sphinx-doc.org/en/master/usage/extensions/imgconverter.html
[sphinx.ext.inheritance_diagram] # https://www.sphinx-doc.org/en/master/usage/extensions/inheritance.html
[sphinx.ext.intersphinx]         # https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html
[sphinx.ext.linkcode]            # https://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html
[sphinx.ext.imgmath ]            # https://www.sphinx-doc.org/en/master/usage/extensions/math.html
[sphinx.ext.mathjax]
[sphinx.ext.napoleon] # https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html
[sphinx.ext.todo]
todo_include_todos = false
todo_emit_warnings = false
todo_link_only     = false
[sphinx.ext.viewcode] # https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html
