-*- mode: org; -*-
#+STARTUP: content
* Base Agenda
Death by Institution and the Harms of Abstraction.
** Main
*** [[/Volumes/documents/github/acab][Acab]]
**** 1: Test Semantics
**** 2: Create IDE
**** 3: Create Content

*** [[/Volumes/documents/github/code_analysis][Code Analysis]]
**** 1: Counts
Versu, Abl, Cif
**** 2: Democracy CSV formulae
**** 3: Patch Notes
*** [[~/.doom.d/setup_files/cron/crontab.backup][Cron Jobs]]
**** Tweet
***** Grammar

** Secondary
*** [[file:/Volumes/documents/github/writing/resources/quotes.org][Quotes]]
*** [[file:/Volumes/documents/github/writing/resources/taxonomies.org][Taxonomies]]
*** [[file:/Volumes/documents/github/writing/resources/DSLs.org][DSLs]]
*** [[file:~/github/writing/resources/bibliography][Bibliography]]
*** [[~/github/languageLearning][Misc Language Repo]]
*** [[file:~/Desktop/pdfs/Current][PDFs to integrate]]
*** [[~/.spacemacs.d/setup_files/pomodoro_log.org][Pomodoro Log]]
*** [[file:~/Mega/twitterthreads][Twitter Threads]]
*** TODO [[file:/Volumes/documents/github/corpora][Darius Kuzemi's Corpora]]
*** [[file:/Volumes/documents/github/otherLibs/data][538 Data]]
*** [[file:/Volumes/documents/github/writing/resources/research_questions.org][Research Questions]]

** Reminders
*** Definitions
**** Modalities
Alethic     - Possibility
Deontic     - Permission
Axiological - Value (intrinsic/extrinsic)
Epistemic   - Knowledge
Doxastic    - Belief
Boulomaic   - Desire

**** Binary Relations
Injective            -
Functional           -
Total                -
Surjective           -
Reflexive            -
Irreflexive          -
Associativity        -
Commutativity        -
Distributivity       -
Idempotence          -
Absorption           -
Monotonicity         -
Affinity             -
Duality              -

Symmetric            -
Antisymmetric        -
Asymmetric           -
Transitive           -
Connected            -
Strongly Connected   -
Pre-order            -
Poset                -
Partial Order        -
Strict Partial Order -
Total Order          -
Strict Total Order   -
Equivalence Relation -
Meet                 -
Join                 -
Lattice              -

Morphism             -
Isomorphic           -
Monad                -
Functor              -

**** Operators
∧ -
∨ -
⊢ -
⊫ - Satistifaction
⟘ -
⟙ -

⊂ -
⊃ -
∪ -
∩ -

**** Linguistics
Noun                    -
Pronoun                 -
Verb                    -
Adjective               -
Adverbs                 -
Preposition             -
Conjunction             -
Articles                -
Interjections           -

Open and Closed Classes -

**** Speech Acts
Illocutionary                   -
Perlocutionary                  -
Performative                    -
Indirect                        -

Direction of Fit                -
Components:
Illocutionary Point             -
Strength of Illocutionary Point -
Mode of Achievement             -
Content Conditions              -
Preparatory Conditions          -
Sincerity Conditions            -
Strength of Sincerity           -

Scorekeeping                    -

(Austin):
Verdictives                     -
Exercitives                     -
Commissives                     -
Behabitives                     -
Expositives                     -

(Searle):
Assertives                      -
Directives                      -
Commissives                     -
Expressives                     -
Declarations                    -

Pragmatics                      -

**** Answer Set Programming
Herbrand Base            -
Herbrand Universe        -
Interpretation           -

Minimal Model Semantics  -
Fixpoint                 -
Stratified Program       -
Dependency Graph         -
Stable Semantics         -
Gelfond-Lifschitz Reduct -

Brave Reasoning          -
Cautious Reasoning       -

**** Components of Logic
Term                                -
Signature                           -

Open World Assumption               -
Closed World Assumption             -

Satisfaction                        -

Valid                               -
Semantic Consequence                -
Bisimulation                        -
Hilbert Semantics                   -
Tarski Semantics                    -

Sequent                             -
Weakening                           -
Contraction                         -
Exchange                            -

α conversion                        -
β reduction                         -
η reduction                         -

Resolution                          -

Normal Form                         -

Hoar Triple                         -

law of excluded middle              -
double negation elimination         -
cut rule                            -
material implication                -
biconditional                       -


compactness property                -

first-order correspondence language -
**** Components of Modal Logic
Kripke Model -
□A = ~◇~A
□            -
◇            -

**** Logics
first-order logic  -
second-order logic -

constructive logic   -
classical logic      -
intuitionistic logic -
substructural logic  -

**** Modal Logics
K   -
K45 -
S   -
S5  -

**** Linear Logic
linear logic -

Multiplicative Conjunction - ⨂
Multiplicative Disjunction - ⅋
Additive Conjunction - &
Additive Disjunction - ⨁

*** Urls
https://github.com/mvcisback/hasse
https://github.com/mxgmn/MarkovJunior.git
[[http://waveform3d.com/][Waveform3d]]
[[https://en.wikipedia.org/wiki/Summa_Theologica][Summa Theologica]]
[[https://parl.ai/projects/light/][Parl.ai: NLP and dialogue]]
[[https://sketchfab.com/][Sketchfab]]
http://www.betsydisalvo.com/research.html
https://anarchopac.wordpress.com/2013/05/31/recommended-reading/amp/
https://andrebrock.academia.edu/
https://applyingml.com/
https://applyingml.com/resources/ml-design-docs/
https://applyingml.com/resources/personalization/
https://bpw1621.com/archive/ordained-the-python-project-template/
https://catlikecoding.com/unity/tutorials/
https://dev.to/matechs/building-custom-dsls-in-typescript-29el
https://developer.valvesoftware.com/wiki/Response_System
https://doc.rust-lang.org/book/title-page.html
https://economicsfromthetopdown.com/2020/12/10/why-and-how-i-write-scientific-documents-in-plain-text/
https://egap.org/resource/10-things-to-know-about-causal-inference/
https://eu4.paradoxwikis.com/Technology
https://floppy.foone.org/w/Main_Page
https://flowingdata.com/2015/12/15/a-day-in-the-life-of-americans/
https://ganelson.github.io/inform/index.html
https://generativist.falsifiable.com/
https://github.com/company-mode/company-mode/wiki/Writing-backends
https://github.com/fgregg/tax_extension/tree/master#code-for-calculation-tax-extensions-in-cook-county
https://graphics.stanford.edu/courses/cs348c-96-fall/resources.html
https://graphviz.org/theory/
https://logicmag.io/play/model-metropolis/
https://medium.com/fluxx-studio-notes/52-things-i-learned-in-2021-8481c4e0d409
https://patthomson.net/2017/01/23/managing-the-phd-keeping-a-journal/
https://pluralistic.net/
https://pybit.es/articles/ast-intro/
https://q.uiver.app/
https://refactoring.guru/
https://stackabuse.com/creating-pdf-invoices-in-python-with-borb/
https://strongtyping.readthedocs.io/en/latest/
https://tenthousandmeters.com/blog/python-behind-the-scenes-11-how-the-python-import-system-works/
https://torch.ox.ac.uk/ethicsai#/
https://transmediawatch.org/articles
https://twitter.com/WitchesFor/lists
https://wa.aws.amazon.com/wat.concept.coe.en.html
https://web.mit.edu/jemorris/humor/500-miles
https://www.alanzucconi.com/tutorials/
https://www.andrewheiss.com/blog/2021/08/21/r2-euler/
https://www.cc.gatech.edu/~isbell/pubs/
https://www.census.gov/quickfacts/fact/table/US/PST045219
https://www.micromacro-game.com/en/extracontent.html
https://www.nomisweb.co.uk/
https://www.sciencedirect.com/journal/artificial-intelligence/issues
https://www.taylorfrancis.com/books/edit/10.4324/9781315302430/organizational-space-beyond-sytze-kingma-karen-dale-varda-wasserman
https://www.uu.nl/en/research/game-research/research/publications
https://www.wzchen.com/data-science-books
https://www.youtube.com/watch?v=SfFh3rIjDME
https://www.youtube.com/watch?v=wfzSE4Hoxbc
*** Other
Killing the Black Body or Fatal Invention by @DorothyERoberts
Medical Apartheid by @haw95
Racecraft by Barbara and Karen Fields
Sister Citizen by @MHarrisPerry
The Pushout by @MoniqueWMorris
The Warmth of Other Suns by @Isabelwilkerson
foone - Infocom game by Douglas Adams: Bureaucracy

history of automated phone lines?

the eternal cyclinder, but personalities for the trebum.
Each is named, so if a trebum dies and is resurrected, blame
the one who was in control.
React to seeing/getting a mutation based on history. excited if completely new,
less so if you've seen it before.
greet resurrected friends, react to their deaths,
share food and water explicitly,
negotiate exchanges of inventory
changes when switching trunks

john wick hex - choreography simulator
index xkcd using explainxkcd

-from:quotedreplies url:1255330066151718912
fictional syllabi - both of actual papers, and lem-like

org - add a nav state for moving around headings and subtrees?

tag - amend mode

cron - look at dropbox/docs, mv any files into current_pdfs

** Exporting and scripts
*** Markdown html export
Add a local file to `markdown-css-paths`,
can use npm package `generate-github-markdown-css` as a start

*** Image Pdf calls
#+NAME: image to pdf generation
#+begin_src bash :results value
convert ? -alpha off ./temp/`?`
mogrify -orient bottom-left ?
img2pdf --output `?`.pdf --pagesize A4 --auto-orient ?
pdftk * cat output diagrams.pdf
#+end_src

#+NAME: text to pdf generation
#+begin_src bash :results value
pandoc ? -o output.pdf
#+end_src
https://pandoc.org/

*** Awk
#+begin_src awk
awk 'match($0, /HREF="(.+?)"/, a) {print a[1]}'

#+end_src awk

* TODO simulation sketches
