-*- mode: org; -*-
#+STARTUP: content
* Base Agenda
Death by Institution and the Harms of Abstraction.
** Main
*** [[/Volumes/documents/github/acab][Acab]]
**** 1: Test Semantics
**** 2: Create IDE
**** 3: Create Content

*** [[/Volumes/documents/github/code_analysis][Code Analysis]]
**** 1: Counts
Versu, Abl, Cif
**** 2: Democracy CSV formulae
**** 3: Patch Notes

** Secondary
*** [[file:/Volumes/documents/github/writing/orgfiles/listings/quotes.org][Quotes]]
*** [[file:/Volumes/documents/github/writing/orgfiles/listings/definitions.org::*Overview][Definitions]]
*** [[file:/Volumes/documents/github/writing/orgfiles/listings/taxonomies.org][Taxonomies]]
*** [[/Volumes/documents/github/writing/orgfiles/listings/DSLs.org][DSLs]]
*** [[file:~/github/writing/resources/bibliography][Bibliography]]
*** [[~/github/languageLearning][Misc Language Repo]]
*** [[~/.doom.d/setup_files/pomodoro_log.org][Pomodoro Log]]
*** [[file:/volumes/documents//twitterthreads][Twitter Threads]]
*** TODO [[file:/Volumes/documents/github/corpora][Darius Kuzemi's Corpora]]
*** [[file:/Volumes/documents/github/writing/orgfiles/primary/research_questions.org][Research Questions]]

** Other
https://cheapbotsdonequick.com/source/
https://botwiki.org/learn/#blogs-and-websites-accountable-algorithms
https://hyperpolyglot.org/
https://sites.ualberta.ca/~urban/Projects/English/Motif_Index.htm

Killing the Black Body or Fatal Invention by @DorothyERoberts
Medical Apartheid by @haw95
Racecraft by Barbara and Karen Fields
Sister Citizen by @MHarrisPerry
The Pushout by @MoniqueWMorris
The Warmth of Other Suns by @Isabelwilkerson
foone - Infocom game by Douglas Adams: Bureaucracy

history of automated phone lines?

the eternal cyclinder, but personalities for the trebum.
Each is named, so if a trebum dies and is resurrected, blame
the one who was in control.
React to seeing/getting a mutation based on history. excited if completely new,
less so if you've seen it before.
greet resurrected friends, react to their deaths,
share food and water explicitly,
negotiate exchanges of inventory
changes when switching trunks

john wick hex - choreography simulator
index xkcd using explainxkcd

-from:quotedreplies url:1255330066151718912
fictional syllabi - both of actual papers, and lem-like

tag - amend mode

** [[file:python_testbed.org][Testbed Notes]]
