#!/usr/bin/env python3
# mode:doit; -*-
# https://pydoit.org/

##-- imports
import pathlib as pl
from doit.action import CmdAction
from doit import create_after
from doit.tools import set_trace, Interactive, PythonInteractiveAction
from doit.task import clean_targets
import doot
##-- end imports

##-- config
data_toml    = doot.setup()

DOIT_CONFIG = {
    "default_tasks" : [],
    "action_string_formatting" : "new",
    }

##-- end config

##-- post-config doot imports
from doot.files.clean_cache import CleanCacheAction, py_cache_globs
from doot.files.checkdir import CheckDir
from doot.utils.dir_data import DootDirs

from doot.groups import *
# from doot.groups_secondary import *
##-- end post-config doot imports

##-- ifdodo
## Equivalent to if main
if __name__ == "dodo":
    all_checks = CheckDir.checkdir_group()
    all_dirs   = DootDirs.dir_group()
##-- end ifdodo
