#!/usr/bin/env python3
# mode:doot; -*-
# https://pydoit.org/

##-- imports
import pathlib as pl
from doit.action import CmdAction
from doit import create_after
from doit.tools import set_trace, Interactive, PythonInteractiveAction
from doit.task import clean_targets
import doot
##-- end imports

from doot.groups import *
# from doot.groups_secondary import *

##-- ifdoot
if __name__ == "doot":
    pass
##-- end ifdoot
