;;; ../../../Volumes/documents/github/emacs_files/packages/jg-themes/+colors.el -*- lexical-binding: t; -*-
(setq jg-color-groups '(:greys (darkslategrey                #2f4f4f
                                                             dimgrey        #696969
                                                             slategrey      #708090
                                                             lightslategrey #778899
                                                             grey           #bebebe
                                                             lightgrey      #d3d3d3
                                                             grey0                   #000000
                                                             grey1                   #030303
                                                             grey2                   #050505
                                                             grey3                   #080808
                                                             grey4                   #0a0a0a
                                                             grey5                   #0d0d0d
                                                             grey6                   #0f0f0f
                                                             grey7                   #121212
                                                             grey8                   #141414
                                                             grey9                   #171717
                                                             grey10                 #1a1a1a
                                                             grey11                 #1c1c1c
                                                             grey12                 #1f1f1f
                                                             grey13                 #212121
                                                             grey14                 #242424
                                                             grey15                 #262626
                                                             grey16                 #292929
                                                             grey17                 #2b2b2b
                                                             grey18                 #2e2e2e
                                                             grey19                 #303030
                                                             grey20                 #333333
                                                             grey21                 #363636
                                                             grey22                 #383838
                                                             grey23                 #3b3b3b
                                                             grey24                 #3d3d3d
                                                             grey25                 #404040
                                                             grey26                 #424242
                                                             grey27                 #454545
                                                             grey28                 #474747
                                                             grey29                 #4a4a4a
                                                             grey30                 #4d4d4d
                                                             grey31                 #4f4f4f
                                                             grey32                 #525252
                                                             grey33                 #545454
                                                             grey34                 #575757
                                                             grey35                 #595959
                                                             grey36                 #5c5c5c
                                                             grey37                 #5e5e5e
                                                             grey38                 #616161
                                                             grey39                 #636363
                                                             grey40                 #666666
                                                             grey41                 #696969
                                                             grey42                 #6b6b6b
                                                             grey43                 #6e6e6e
                                                             grey44                 #707070
                                                             grey45                 #737373
                                                             grey46                 #757575
                                                             grey47                 #787878
                                                             grey48                 #7a7a7a
                                                             grey49                 #7d7d7d
                                                             grey50                 #7f7f7f
                                                             grey51                 #828282
                                                             grey52                 #858585
                                                             grey53                 #878787
                                                             grey54                 #8a8a8a
                                                             grey55                 #8c8c8c
                                                             grey56                 #8f8f8f
                                                             grey57                 #919191
                                                             grey58                 #949494
                                                             grey59                 #969696
                                                             grey60                 #999999
                                                             grey61                 #9c9c9c
                                                             grey62                 #9e9e9e
                                                             grey63                 #a1a1a1
                                                             grey64                 #a3a3a3
                                                             grey65                 #a6a6a6
                                                             grey66                 #a8a8a8
                                                             grey67                 #ababab
                                                             grey68                 #adadad
                                                             grey69                 #b0b0b0
                                                             grey70                 #b3b3b3
                                                             grey71                 #b5b5b5
                                                             grey72                 #b8b8b8
                                                             grey73                 #bababa
                                                             grey74                 #bdbdbd
                                                             grey75                 #bfbfbf
                                                             grey76                 #c2c2c2
                                                             grey77                 #c4c4c4
                                                             grey78                 #c7c7c7
                                                             grey79                 #c9c9c9
                                                             grey80                 #cccccc
                                                             grey81                 #cfcfcf
                                                             grey82                 #d1d1d1
                                                             grey83                 #d4d4d4
                                                             grey84                 #d6d6d6
                                                             grey85                 #d9d9d9
                                                             grey86                 #dbdbdb
                                                             grey87                 #dedede
                                                             grey88                 #e0e0e0
                                                             grey89                 #e3e3e3
                                                             grey90                 #e5e5e5
                                                             grey91                 #e8e8e8
                                                             grey92                 #ebebeb
                                                             grey93                 #ededed
                                                             grey94                 #f0f0f0
                                                             grey95                 #f2f2f2
                                                             grey96                 #f5f5f5
                                                             grey97                 #f7f7f7
                                                             grey98                 #fafafa
                                                             grey99                 #fcfcfc
                                                             grey100               #ffffff
                                                             darkgrey             #a9a9a9
                                                             )
                        :misc ( darkblue                      #00008b
                                                              darkcyan                      #008b8b
                                                              darkmagenta                   #8b008b
                                                              darkred                       #8b0000
                                                              lightgreen                    #90ee90
                                                              )
                        :blues (midnightblue                  #191970
                                                              navy,navyblue                 #000080
                                                              cornflowerblue                #6495ed
                                                              darkslateblue                 #483d8b
                                                              slateblue                     #6a5acd
                                                              mediumslateblue               #7b68ee
                                                              lightslateblue                #8470ff
                                                              mediumblue                    #0000cd
                                                              royalblue                     #4169e1
                                                              dodgerblue                    #1e90ff
                                                              deepskyblue                   #00bfff
                                                              skyblue                       #87ceeb
                                                              lightskyblue                  #87cefa
                                                              steelblue                     #4682b4
                                                              lightsteelblue                #b0c4de
                                                              lightblue                     #add8e6
                                                              powderblue                    #b0e0e6
                                                              paleturquoise                 #afeeee
                                                              darkturquoise                 #00ced1
                                                              mediumturquoise               #48d1cc
                                                              turquoise                     #40e0d0
                                                              lightcyan                     #e0ffff
                                                              cadetblue                     #5f9ea0
                                                              mediumaquamarine              #66cdaa
                                                              aquamarine                    #7fffd4
                                                              slateblue1                    #836fff
                                                              slateblue2                    #7a67ee
                                                              slateblue3                    #6959cd
                                                              slateblue4                    #473c8b
                                                              royalblue1                    #4876ff
                                                              royalblue2                    #436eee
                                                              royalblue3                    #3a5fcd
                                                              royalblue4                    #27408b
                                                              blue1                         #0000ff
                                                              blue2                         #0000ee
                                                              blue3                         #0000cd
                                                              blue4                         #00008b
                                                              dodgerblue1                   #1e90ff
                                                              dodgerblue2                   #1c86ee
                                                              dodgerblue3                   #1874cd
                                                              dodgerblue4                   #104e8b
                                                              steelblue1                    #63b8ff
                                                              steelblue2                    #5cacee
                                                              steelblue3                    #4f94cd
                                                              steelblue4                    #36648b
                                                              deepskyblue1                  #00bfff
                                                              deepskyblue2                  #00b2ee
                                                              deepskyblue3                  #009acd
                                                              deepskyblue4                  #00688b
                                                              skyblue1                      #87ceff
                                                              skyblue2                      #7ec0ee
                                                              skyblue3                      #6ca6cd
                                                              skyblue4                      #4a708b
                                                              lightskyblue1                 #b0e2ff
                                                              lightskyblue2                 #a4d3ee
                                                              lightskyblue3                 #8db6cd
                                                              lightskyblue4                 #607b8b
                                                              slategray1                    #c6e2ff
                                                              slategray2                    #b9d3ee
                                                              slategray3                    #9fb6cd
                                                              slategray4                    #6c7b8b
                                                              lightsteelblue1               #cae1ff
                                                              lightsteelblue2               #bcd2ee
                                                              lightsteelblue3               #a2b5cd
                                                              lightsteelblue4               #6e7b8b
                                                              lightblue1                    #bfefff
                                                              lightblue2                    #b2dfee
                                                              lightblue3                    #9ac0cd
                                                              lightblue4                    #68838b
                                                              lightcyan1                    #e0ffff
                                                              lightcyan2                    #d1eeee
                                                              lightcyan3                    #b4cdcd
                                                              lightcyan4                    #7a8b8b
                                                              paleturquoise1                #bbffff
                                                              paleturquoise2                #aeeeee
                                                              paleturquoise3                #96cdcd
                                                              paleturquoise4                #668b8b
                                                              cadetblue1                    #98f5ff
                                                              cadetblue2                    #8ee5ee
                                                              cadetblue3                    #7ac5cd
                                                              cadetblue4                    #53868b
                                                              turquoise1                    #00f5ff
                                                              turquoise2                    #00e5ee
                                                              turquoise3                    #00c5cd
                                                              turquoise4                    #00868b
                                                              cyan1                         #00ffff
                                                              cyan2                         #00eeee
                                                              cyan3                         #00cdcd
                                                              cyan4                         #008b8b
                                                              darkslategray1                #97ffff
                                                              darkslategray2                #8deeee
                                                              darkslategray3                #79cdcd
                                                              darkslategray4                #528b8b
                                                              aquamarine1                   #7fffd4
                                                              aquamarine2                   #76eec6
                                                              aquamarine3                   #66cdaa
                                                              aquamarine4                   #458b74)
                        :greens (darkgreen                     #006400
                                                               darkolivegreen                #556b2f
                                                               darkseagreen                  #8fbc8f
                                                               seagreen                      #2e8b57
                                                               mediumseagreen                #3cb371
                                                               lightseagreen                 #20b2aa
                                                               palegreen                     #98fb98
                                                               springgreen                   #00ff7f
                                                               lawngreen                     #7cfc00
                                                               chartreuse                    #7fff00
                                                               mediumspringgreen             #00fa9a
                                                               greenyellow                   #adff2f
                                                               limegreen                     #32cd32
                                                               yellowgreen                   #9acd32
                                                               forestgreen                   #228b22
                                                               olivedrab                     #6b8e23
                                                               darkseagreen1                 #c1ffc1
                                                               darkseagreen2                 #b4eeb4
                                                               darkseagreen3                 #9bcd9b
                                                               darkseagreen4                 #698b69
                                                               seagreen1                     #54ff9f
                                                               seagreen2                     #4eee94
                                                               seagreen3                     #43cd80
                                                               seagreen4                     #2e8b57
                                                               palegreen1                    #9aff9a
                                                               palegreen2                    #90ee90
                                                               palegreen3                    #7ccd7c
                                                               palegreen4                    #548b54
                                                               springgreen1                  #00ff7f
                                                               springgreen2                  #00ee76
                                                               springgreen3                  #00cd66
                                                               springgreen4                  #008b45
                                                               green1                        #00ff00
                                                               green2                        #00ee00
                                                               green3                        #00cd00
                                                               green4                        #008b00
                                                               chartreuse1                   #7fff00
                                                               chartreuse2                   #76ee00
                                                               chartreuse3                   #66cd00
                                                               chartreuse4                   #458b00
                                                               olivedrab1                    #c0ff3e
                                                               olivedrab2                    #b3ee3a
                                                               olivedrab3                    #9acd32
                                                               olivedrab4                    #698b22
                                                               darkolivegreen1               #caff70
                                                               darkolivegreen2               #bcee68
                                                               darkolivegreen3               #a2cd5a
                                                               darkolivegreen4               #6e8b3d
                                                               )
                        :yellows (darkkhaki                     #bdb76b
                                                                khaki                         #f0e68c
                                                                palegoldenrod                 #eee8aa
                                                                lightgoldenrodyellow          #fafad2
                                                                lightyellow                   #ffffe0
                                                                gold                          #ffd700
                                                                lightgoldenrod                #eedd82
                                                                goldenrod                     #daa520
                                                                darkgoldenrod                 #b8860b
                                                                rosybrown                     #bc8f8f
                                                                khaki1                        #fff68f
                                                                khaki2                        #eee685
                                                                khaki3                        #cdc673
                                                                khaki4                        #8b864e
                                                                lightgoldenrod1               #ffec8b
                                                                lightgoldenrod2               #eedc82
                                                                lightgoldenrod3               #cdbe70
                                                                lightgoldenrod4               #8b814c
                                                                lightyellow1                  #ffffe0
                                                                lightyellow2                  #eeeed1
                                                                lightyellow3                  #cdcdb4
                                                                lightyellow4                  #8b8b7a
                                                                yellow1                       #ffff00
                                                                yellow2                       #eeee00
                                                                yellow3                       #cdcd00
                                                                yellow4                       #8b8b00
                                                                gold1                         #ffd700
                                                                gold2                         #eec900
                                                                gold3                         #cdad00
                                                                gold4                         #8b7500
                                                                goldenrod1                    #ffc125
                                                                goldenrod2                    #eeb422
                                                                goldenrod3                    #cd9b1d
                                                                goldenrod4                    #8b6914
                                                                darkgoldenrod1                #ffb90f
                                                                darkgoldenrod2                #eead0e
                                                                darkgoldenrod3                #cd950c
                                                                darkgoldenrod4                #8b6508
                                                                )
                        :reds (indianred                     #cd5c5c
                                                             saddlebrown                   #8b4513
                                                             sienna                        #a0522d
                                                             peru                          #cd853f
                                                             burlywood                     #deb887
                                                             beige                         #f5f5dc
                                                             wheat                         #f5deb3
                                                             sandybrown                    #f4a460
                                                             tan                           #d2b48c
                                                             chocolate                     #d2691e
                                                             firebrick                     #b22222
                                                             brown                         #a52a2a
                                                             darksalmon                    #e9967a
                                                             salmon                        #fa8072
                                                             lightsalmon                   #ffa07a
                                                             orange                        #ffa500
                                                             darkorange                    #ff8c00
                                                             coral                         #ff7f50
                                                             lightcoral                    #f08080
                                                             tomato                        #ff6347
                                                             orangered                     #ff4500
                                                             rosybrown1                    #ffc1c1
                                                             rosybrown2                    #eeb4b4
                                                             rosybrown3                    #cd9b9b
                                                             rosybrown4                    #8b6969
                                                             indianred1                    #ff6a6a
                                                             indianred2                    #ee6363
                                                             indianred3                    #cd5555
                                                             indianred4                    #8b3a3a
                                                             sienna1                       #ff8247
                                                             sienna2                       #ee7942
                                                             sienna3                       #cd6839
                                                             sienna4                       #8b4726
                                                             tan1                          #ffa54f
                                                             tan2                          #ee9a49
                                                             tan3                          #cd853f
                                                             tan4                          #8b5a2b
                                                             chocolate1                    #ff7f24
                                                             chocolate2                    #ee7621
                                                             chocolate3                    #cd661d
                                                             chocolate4                    #8b4513
                                                             firebrick1                    #ff3030
                                                             firebrick2                    #ee2c2c
                                                             firebrick3                    #cd2626
                                                             firebrick4                    #8b1a1a
                                                             brown1                        #ff4040
                                                             brown2                        #ee3b3b
                                                             brown3                        #cd3333
                                                             brown4                        #8b2323
                                                             salmon1                       #ff8c69
                                                             salmon2                       #ee8262
                                                             salmon3                       #cd7054
                                                             salmon4                       #8b4c39
                                                             lightsalmon1                  #ffa07a
                                                             lightsalmon2                  #ee9572
                                                             lightsalmon3                  #cd8162
                                                             lightsalmon4                  #8b5742
                                                             orange1                       #ffa500
                                                             orange2                       #ee9a00
                                                             orange3                       #cd8500
                                                             orange4                       #8b5a00
                                                             darkorange1                   #ff7f00
                                                             darkorange2                   #ee7600
                                                             darkorange3                   #cd6600
                                                             darkorange4                   #8b4500
                                                             coral1                        #ff7256
                                                             coral2                        #ee6a50
                                                             coral3                        #cd5b45
                                                             coral4                        #8b3e2f
                                                             tomato1                       #ff6347
                                                             tomato2                       #ee5c42
                                                             tomato3                       #cd4f39
                                                             tomato4                       #8b3626
                                                             orangered1                    #ff4500
                                                             orangered2                    #ee4000
                                                             orangered3                    #cd3700
                                                             orangered4                    #8b2500
                                                             red1                          #ff0000
                                                             red2                          #ee0000
                                                             red3                          #cd0000
                                                             red4                          #8b0000
                                                             )
                        :pinks (hotpink                       #ff69b4
                                                              deeppink                      #ff1493
                                                              pink                          #ffc0cb
                                                              lightpink                     #ffb6c1
                                                              palevioletred                 #db7093
                                                              maroon                        #b03060
                                                              mediumvioletred               #c71585
                                                              violetred                     #d02090
                                                              deeppink1                     #ff1493
                                                              deeppink2                     #ee1289
                                                              deeppink3                     #cd1076
                                                              deeppink4                     #8b0a50
                                                              hotpink1                      #ff6eb4
                                                              hotpink2                      #ee6aa7
                                                              hotpink3                      #cd6090
                                                              hotpink4                      #8b3a62
                                                              pink1                         #ffb5c5
                                                              pink2                         #eea9b8
                                                              pink3                         #cd919e
                                                              pink4                         #8b636c
                                                              lightpink1                    #ffaeb9
                                                              lightpink2                    #eea2ad
                                                              lightpink3                    #cd8c95
                                                              lightpink4                    #8b5f65
                                                              palevioletred1                #ff82ab
                                                              palevioletred2                #ee799f
                                                              palevioletred3                #cd6889
                                                              palevioletred4                #8b475d
                                                              maroon1                       #ff34b3
                                                              maroon2                       #ee30a7
                                                              maroon3                       #cd2990
                                                              maroon4                       #8b1c62
                                                              violetred1                    #ff3e96
                                                              violetred2                    #ee3a8c
                                                              violetred3                    #cd3278
                                                              violetred4                    #8b2252
                                                              )
                        :purples (violet                        #ee82ee
                                                                plum                          #dda0dd
                                                                orchid                        #da70d6
                                                                mediumorchid                  #ba55d3
                                                                darkorchid                    #9932cc
                                                                darkviolet                    #9400d3
                                                                blueviolet                    #8a2be2
                                                                purple                        #a020f0
                                                                mediumpurple                  #9370db

                                                                magenta1                      #ff00ff
                                                                magenta2                      #ee00ee
                                                                magenta3                      #cd00cd
                                                                magenta4                      #8b008b
                                                                orchid1                       #ff83fa
                                                                orchid2                       #ee7ae9
                                                                orchid3                       #cd69c9
                                                                orchid4                       #8b4789
                                                                plum1                         #ffbbff
                                                                plum2                         #eeaeee
                                                                plum3                         #cd96cd
                                                                plum4                         #8b668b
                                                                mediumorchid1                 #e066ff
                                                                mediumorchid2                 #d15fee
                                                                mediumorchid3                 #b452cd
                                                                mediumorchid4                 #7a378b
                                                                darkorchid1                   #bf3eff
                                                                darkorchid2                   #b23aee
                                                                darkorchid3                   #9a32cd
                                                                darkorchid4                   #68228b
                                                                purple1                       #9b30ff
                                                                purple2                       #912cee
                                                                purple3                       #7d26cd
                                                                purple4                       #551a8b
                                                                mediumpurple1                 #ab82ff
                                                                mediumpurple2                 #9f79ee
                                                                mediumpurple3                 #8968cd
                                                                mediumpurple4                 #5d478b
                                                                )
                        :monochrome (thistle                       #d8bfd8
                                                                   snow1                         #fffafa
                                                                   snow2                         #eee9e9
                                                                   snow3                         #cdc9c9
                                                                   snow4                         #8b8989
                                                                   seashell1                     #fff5ee
                                                                   seashell2                     #eee5de
                                                                   seashell3                     #cdc5bf
                                                                   seashell4                     #8b8682
                                                                   antiquewhite1                 #ffefdb
                                                                   antiquewhite2                 #eedfcc
                                                                   antiquewhite3                 #cdc0b0
                                                                   antiquewhite4                 #8b8378
                                                                   bisque1                       #ffe4c4
                                                                   bisque2                       #eed5b7
                                                                   bisque3                       #cdb79e
                                                                   bisque4                       #8b7d6b
                                                                   peachpuff1                    #ffdab9
                                                                   peachpuff2                    #eecbad
                                                                   peachpuff3                    #cdaf95
                                                                   peachpuff4                    #8b7765
                                                                   navajowhite1                  #ffdead
                                                                   navajowhite2                  #eecfa1
                                                                   navajowhite3                  #cdb38b
                                                                   navajowhite4                  #8b795e
                                                                   lemonchiffon1                 #fffacd
                                                                   lemonchiffon2                 #eee9bf
                                                                   lemonchiffon3                 #cdc9a5
                                                                   lemonchiffon4                 #8b8970
                                                                   cornsilk1                     #fff8dc
                                                                   cornsilk2                     #eee8cd
                                                                   cornsilk3                     #cdc8b1
                                                                   cornsilk4                     #8b8878
                                                                   ivory1                        #fffff0
                                                                   ivory2                        #eeeee0
                                                                   ivory3                        #cdcdc1
                                                                   ivory4                        #8b8b83
                                                                   honeydew1                     #f0fff0
                                                                   honeydew2                     #e0eee0
                                                                   honeydew3                     #c1cdc1
                                                                   honeydew4                     #838b83
                                                                   lavenderblush1                #fff0f5
                                                                   lavenderblush2                #eee0e5
                                                                   lavenderblush3                #cdc1c5
                                                                   lavenderblush4                #8b8386
                                                                   mistyrose1                    #ffe4e1
                                                                   mistyrose2                    #eed5d2
                                                                   mistyrose3                    #cdb7b5
                                                                   mistyrose4                    #8b7d7b
                                                                   azure1                        #f0ffff
                                                                   azure2                        #e0eeee
                                                                   azure3                        #c1cdcd
                                                                   azure4                        #838b8b
                                                                   burlywood1                    #ffd39b
                                                                   burlywood2                    #eec591
                                                                   burlywood3                    #cdaa7d
                                                                   burlywood4                    #8b7355
                                                                   wheat1                        #ffe7ba
                                                                   wheat2                        #eed8ae
                                                                   wheat3                        #cdba96
                                                                   wheat4                        #8b7e66
                                                                   thistle1                      #ffe1ff
                                                                   thistle2                      #eed2ee
                                                                   thistle3                      #cdb5cd
                                                                   thistle4                      #8b7b8b

                                                                   )
                        )
)
