;;; ../../../Volumes/documents/github/emacs_files/packages/jg-themes/+face-groups.el -*- lexical-binding: t; -*-

(setq-default jg-face-groups '(:modules ((+fold-hideshow-folded-face  )
                                         (+org-todo-active  )
                                         (+org-todo-onhold  )
                                         (+org-todo-project  )
                                         (+workspace-tab-face  )
                                         (+workspace-tab-selected-face  ))

                               :a-misc ((ac-completion-face)
                                        (ahs-face))
                               
                               :all-the-icons ((all-the-icons-blue  )
                                               (all-the-icons-blue-alt  )
                                               (all-the-icons-cyan  )
                                               (all-the-icons-cyan-alt  )
                                               (all-the-icons-dblue  )
                                               (all-the-icons-dcyan  )
                                               (all-the-icons-dgreen  )
                                               (all-the-icons-dmaroon  )
                                               (all-the-icons-dorange  )
                                               (all-the-icons-dpink  )
                                               (all-the-icons-dpurple  )
                                               (all-the-icons-dred  )
                                               (all-the-icons-dsilver  )
                                               (all-the-icons-dyellow  )
                                               (all-the-icons-green  )
                                               (all-the-icons-lblue  )
                                               (all-the-icons-lcyan  )
                                               (all-the-icons-lgreen  )
                                               (all-the-icons-lmaroon  )
                                               (all-the-icons-lorange  )
                                               (all-the-icons-lpink  )
                                               (all-the-icons-lpurple  )
                                               (all-the-icons-lred  )
                                               (all-the-icons-lsilver  )
                                               (all-the-icons-lyellow  )
                                               (all-the-icons-maroon  )
                                               (all-the-icons-orange  )
                                               (all-the-icons-pink  )
                                               (all-the-icons-purple  )
                                               (all-the-icons-purple-alt  )
                                               (all-the-icons-red  )
                                               (all-the-icons-red-alt  )
                                               (all-the-icons-silver  )
                                               (all-the-icons-yellow  )
                                               )
                               :anzu ((anzu-match-1  )
                                      (anzu-match-2  )
                                      (anzu-match-3  )
                                      (anzu-mode-line  )
                                      (anzu-mode-line-no-match  )
                                      (anzu-replace-highlight  )
                                      (anzu-replace-to  ))

                               :bold ((bold  )
                                      (bold-italic  ))
                               :bookmark-menu ((bookmark-menu-bookmark  )
                                               (bookmark-menu-heading  ))

                               :border ((border  ))
                               :b-misc ((browse-url-button  )
                                        (buffer-menu-buffer  )
                                        (button  ))

                               :calendar ((calendar-month-header  )
                                          (calendar-today  )
                                          (calendar-weekday-header  )
                                          (calendar-weekend-header  ))
                               :change-log ((change-log-acknowledgment  )
                                            (change-log-conditionals  )
                                            (change-log-date  )
                                            (change-log-email  )
                                            (change-log-file  )
                                            (change-log-function  )
                                            (change-log-list  )
                                            (change-log-name  ))

                               :comint ((comint-highlight-input  )
                                        (comint-highlight-prompt  ))

                               :compilation ((compilation-column-number  )
                                             (compilation-error  )
                                             (compilation-info  )
                                             (compilation-line-number  )
                                             (compilation-mode-line-exit  )
                                             (compilation-mode-line-fail  )
                                             (compilation-mode-line-run  )
                                             (compilation-warning  ))
                               :completions ((completions-annotations  )
                                             (completions-common-part  )
                                             (completions-first-difference  ))
                               :counsel ((counsel--mark-ring-highlight  )
                                         (counsel-active-mode  )
                                         (counsel-application-name  )
                                         (counsel-evil-register-face  )
                                         (counsel-key-binding  )
                                         (counsel-outline-1  )
                                         (counsel-outline-2  )
                                         (counsel-outline-3  )
                                         (counsel-outline-4  )
                                         (counsel-outline-5  )
                                         (counsel-outline-6  )
                                         (counsel-outline-7  )
                                         (counsel-outline-8  )
                                         (counsel-outline-default  )
                                         (counsel-variable-documentation  ))
                               :cursor ((cursor  ))
                               :custom ((custom-button  )
                                        (custom-button-mouse  )
                                        (custom-button-pressed  )
                                        (custom-button-pressed-unraised  )
                                        (custom-button-unraised  )
                                        (custom-changed  )
                                        (custom-comment  )
                                        (custom-comment-tag  )
                                        (custom-documentation  )
                                        (custom-face-tag  )
                                        (custom-group-subtitle  )
                                        (custom-group-tag  )
                                        (custom-group-tag-1  )
                                        (custom-invalid  )
                                        (custom-link  )
                                        (custom-modified  )
                                        (custom-rogue  )
                                        (custom-saved  )
                                        (custom-set  )
                                        (custom-state  )
                                        (custom-themed  )
                                        (custom-variable-button  )
                                        (custom-variable-obsolete  )
                                        (custom-variable-tag  )
                                        (custom-visibility  ))

                               :company ((company-echo-common  )
                                         (company-preview  )
                                         (company-preview-common  )
                                         (company-preview-search  )
                                         (company-scrollbar-bg  )
                                         (company-scrollbar-fg  )
                                         (company-template-field  )
                                         (company-tooltip  )
                                         (company-tooltip-annotation  )
                                         (company-tooltip-annotation-selection  )
                                         (company-tooltip-common  )
                                         (company-tooltip-common-selection  )
                                         (company-tooltip-selection  )
                                         (company-tooltip-selection  ))

                               :c-misc ((centaur-tabs-unselected ))
                               
                               :default ((default  ))
                               :diary ((diary  ))
                               :diff ((diff-added  )
                                      (diff-changed  )
                                      (diff-context  )
                                      (diff-file-header  )
                                      (diff-function  )
                                      (diff-header  )
                                      (diff-hl-change  )
                                      (diff-hl-delete  )
                                      (diff-hl-dired-change  )
                                      (diff-hl-dired-delete  )
                                      (diff-hl-dired-ignored  )
                                      (diff-hl-dired-insert  )
                                      (diff-hl-dired-unknown  )
                                      (diff-hl-insert  )
                                      (diff-hl-margin-change  )
                                      (diff-hl-margin-delete  )
                                      (diff-hl-margin-ignored  )
                                      (diff-hl-margin-insert  )
                                      (diff-hl-margin-unknown  )
                                      (diff-hl-reverted-hunk-highlight  )
                                      (diff-hunk-header  )
                                      (diff-index  )
                                      (diff-indicator-added  )
                                      (diff-indicator-changed  )
                                      (diff-indicator-removed  )
                                      (diff-nonexistent  )
                                      (diff-refine-added  )
                                      (diff-refine-changed  )
                                      (diff-refine-removed  )
                                      (diff-removed  ))
                               :dired ((dired-directory  )
                                       (dired-flagged  )
                                       (dired-header  )
                                       (dired-ignored  )
                                       (dired-mark  )
                                       (dired-marked  )
                                       (dired-perm-write  )
                                       (dired-set-id  )
                                       (dired-special  )
                                       (dired-symlink  )
                                       (dired-warning  )
                                       (diredfl-autofile-name  )
                                       (diredfl-compressed-file-name  )
                                       (diredfl-compressed-file-suffix  )
                                       (diredfl-date-time  )
                                       (diredfl-deletion  )
                                       (diredfl-deletion-file-name  )
                                       (diredfl-dir-heading  )
                                       (diredfl-dir-name  )
                                       (diredfl-dir-priv  )
                                       (diredfl-exec-priv  )
                                       (diredfl-executable-tag  )
                                       (diredfl-file-name  )
                                       (diredfl-file-suffix  )
                                       (diredfl-flag-mark  )
                                       (diredfl-flag-mark-line  )
                                       (diredfl-ignored-file-name  )
                                       (diredfl-link-priv  )
                                       (diredfl-no-priv  )
                                       (diredfl-number  )
                                       (diredfl-other-priv  )
                                       (diredfl-rare-priv  )
                                       (diredfl-read-priv  )
                                       (diredfl-symlink  )
                                       (diredfl-tagged-autofile-name  )
                                       (diredfl-write-priv  )
                                       (diredp-compressed-file-suffix  )
                                       (diredp-date-time  )
                                       (diredp-dir-exec-priv  )
                                       (diredp-dir-name  )
                                       (diredp-dir-priv  )
                                       (diredp-file-name  )
                                       (diredp-file-suffix  )
                                       (diredp-ignored-file-name  )
                                       (diredp-link-priv  )
                                       (diredp-no-priv  )
                                       (diredp-number  )
                                       (diredp-other-priv  )
                                       (diredp-rare-priv  )
                                       (diredp-symlink  ))

                               :doom ((doom-dashboard-banner  )
                                      (doom-dashboard-footer  )
                                      (doom-dashboard-footer-icon  )
                                      (doom-dashboard-loaded  )
                                      (doom-dashboard-menu-desc  )
                                      (doom-dashboard-menu-title  )
                                      (doom-modeline-bar  )
                                      (doom-modeline-bar-inactive  )
                                      (doom-modeline-battery-charging  )
                                      (doom-modeline-battery-critical  )
                                      (doom-modeline-battery-error  )
                                      (doom-modeline-battery-full  )
                                      (doom-modeline-battery-normal  )
                                      (doom-modeline-battery-warning  )
                                      (doom-modeline-buffer-file  )
                                      (doom-modeline-buffer-major-mode  )
                                      (doom-modeline-buffer-minor-mode  )
                                      (doom-modeline-buffer-modified  )
                                      (doom-modeline-buffer-path  )
                                      (doom-modeline-buffer-timemachine  )
                                      (doom-modeline-debug  )
                                      (doom-modeline-debug-visual  )
                                      (doom-modeline-evil-emacs-state  )
                                      (doom-modeline-evil-insert-state  )
                                      (doom-modeline-evil-motion-state  )
                                      (doom-modeline-evil-normal-state  )
                                      (doom-modeline-evil-operator-state  )
                                      (doom-modeline-evil-replace-state  )
                                      (doom-modeline-evil-visual-state  )
                                      (doom-modeline-highlight  )
                                      (doom-modeline-host  )
                                      (doom-modeline-info  )
                                      (doom-modeline-input-method  )
                                      (doom-modeline-input-method-alt  )
                                      (doom-modeline-lsp-error  )
                                      (doom-modeline-lsp-running  )
                                      (doom-modeline-lsp-success  )
                                      (doom-modeline-lsp-warning  )
                                      (doom-modeline-panel  )
                                      (doom-modeline-persp-buffer-not-in-persp  )
                                      (doom-modeline-persp-name  )
                                      (doom-modeline-project-dir  )
                                      (doom-modeline-project-parent-dir  )
                                      (doom-modeline-project-root-dir  )
                                      (doom-modeline-repl-success  )
                                      (doom-modeline-repl-warning  )
                                      (doom-modeline-spc-face  )
                                      (doom-modeline-unread-number  )
                                      (doom-modeline-urgent  )
                                      (doom-modeline-vspc-face  )
                                      (doom-modeline-warning  ))
                               :doom-themes ((doom-themes-neotree-data-file-face  )
                                             (doom-themes-neotree-dir-face  )
                                             (doom-themes-neotree-executable-file-face  )
                                             (doom-themes-neotree-file-face  )
                                             (doom-themes-neotree-hidden-file-face  )
                                             (doom-themes-neotree-media-file-face  )
                                             (doom-themes-neotree-text-file-face  ))

                               :edebug ((edebug-disabled-breakpoint  )
                                        (edebug-enabled-breakpoint  ))

                               :eldoc ((eldoc-highlight-function-argument  ))
                               :embrace ((embrace-help-key-face  )
                                         (embrace-help-mark-func-face  )
                                         (embrace-help-pair-face  )
                                         (embrace-help-separator-face  ))
                               :epa ((epa-field-body  )
                                     (epa-field-name  )
                                     (epa-mark  )
                                     (epa-string  )
                                     (epa-validity-disabled  )
                                     (epa-validity-high  )
                                     (epa-validity-low  )
                                     (epa-validity-medium  ))

                               :e-misc((eros-result-overlay-face  )
                                       (error  )
                                       (escape-glyph  )
                                       (eshell-prompt  )
                                       (ediff-current-diff-A  )
                                       (ediff-current-diff-Ancestor  )
                                       (ediff-current-diff-B  )
                                       (ediff-current-diff-C  )
                                       (elscreen-tab-other-screen-face  ))

                               :evil ((evil-emacs-state  )
                                      (evil-embrace-section-title-face  )
                                      (evil-evilified-state  )
                                      (evil-ex-commands  )
                                      (evil-ex-info  )
                                      (evil-ex-lazy-highlight  )
                                      (evil-ex-search  )
                                      (evil-ex-substitute-matches  )
                                      (evil-ex-substitute-replacement  )
                                      (evil-goggles--pulse-face  )
                                      (evil-goggles-change-face  )
                                      (evil-goggles-commentary-face  )
                                      (evil-goggles-default-face  )
                                      (evil-goggles-delete-face  )
                                      (evil-goggles-fill-and-move-face  )
                                      (evil-goggles-indent-face  )
                                      (evil-goggles-join-face  )
                                      (evil-goggles-nerd-commenter-face  )
                                      (evil-goggles-paste-face  )
                                      (evil-goggles-record-macro-face  )
                                      (evil-goggles-replace-with-register-face  )
                                      (evil-goggles-set-marker-face  )
                                      (evil-goggles-shift-face  )
                                      (evil-goggles-surround-face  )
                                      (evil-goggles-yank-face  )
                                      (evil-hybrid-state  )
                                      (evil-iedit-insert-state  )
                                      (evil-iedit-state  )
                                      (evil-insert-state  )
                                      (evil-lisp-state  )
                                      (evil-motion-state  )
                                      (evil-normal-state  )
                                      (evil-replace-state  )
                                      (evil-snipe-first-match-face  )
                                      (evil-snipe-matches-face  )
                                      (evil-traces-change  )
                                      (evil-traces-copy-preview  )
                                      (evil-traces-copy-range  )
                                      (evil-traces-default  )
                                      (evil-traces-delete  )
                                      (evil-traces-global-match  )
                                      (evil-traces-global-range  )
                                      (evil-traces-join-indicator  )
                                      (evil-traces-join-range  )
                                      (evil-traces-move-preview  )
                                      (evil-traces-move-range  )
                                      (evil-traces-normal  )
                                      (evil-traces-shell-command  )
                                      (evil-traces-sort  )
                                      (evil-traces-substitute-range  )
                                      (evil-traces-yank  )
                                      (evil-visual-state  ))

                               :f-misc ((ffap  )
                                        (file-name-shadow  )
                                        (fill-column-indicator  )
                                        (fixed-pitch  )
                                        (fixed-pitch-serif  )
                                        (flx-highlight-face  ))

                               :flycheck ((flycheck-delimited-error  )
                                          (flycheck-error  )
                                          (flycheck-error-delimiter  )
                                          (flycheck-error-list-checker-name  )
                                          (flycheck-error-list-column-number  )
                                          (flycheck-error-list-error  )
                                          (flycheck-error-list-error-message  )
                                          (flycheck-error-list-filename  )
                                          (flycheck-error-list-highlight  )
                                          (flycheck-error-list-id  )
                                          (flycheck-error-list-id-with-explainer  )
                                          (flycheck-error-list-info  )
                                          (flycheck-error-list-line-number  )
                                          (flycheck-error-list-warning  )
                                          (flycheck-fringe-error  )
                                          (flycheck-fringe-info  )
                                          (flycheck-fringe-warning  )
                                          (flycheck-info  )
                                          (flycheck-verify-select-checker  )
                                          (flycheck-warning  )
                                          (flyspell-duplicate  )
                                          (flyspell-incorrect  ))

                               :font-lock ((font-lock-builtin-face  )
                                           (font-lock-comment-delimiter-face  )
                                           (font-lock-comment-face  )
                                           (font-lock-constant-face  )
                                           (font-lock-doc-face  )
                                           (font-lock-function-name-face  )
                                           (font-lock-keyword-face  )
                                           (font-lock-negation-char-face  )
                                           (font-lock-preprocessor-face  )
                                           (font-lock-regexp-grouping-backslash  )
                                           (font-lock-regexp-grouping-construct  )
                                           (font-lock-string-face  )
                                           (font-lock-type-face  )
                                           (font-lock-variable-name-face  )
                                           (font-lock-warning-face  ))

                               :fringe ((fringe  ))

                               :git-commit ((git-commit-comment-action  )
                                            (git-commit-comment-branch-local  )
                                            (git-commit-comment-branch-remote  )
                                            (git-commit-comment-detached  )
                                            (git-commit-comment-file  )
                                            (git-commit-comment-heading  )
                                            (git-commit-keyword  )
                                            (git-commit-known-pseudo-header  )
                                            (git-commit-nonempty-second-line  )
                                            (git-commit-overlong-summary  )
                                            (git-commit-pseudo-header  )
                                            (git-commit-summary  )
                                            (git-gutter:added  )
                                            (git-gutter:deleted  )
                                            (git-gutter:modified  )
                                            (git-gutter:separator  )
                                            (git-gutter:unchanged  ))

                               :glyph ((glyphless-char  ))

                               :haskell ((haskell-constructor-face  )
                                         (haskell-debug-heading-face  )
                                         (haskell-debug-keybinding-face  )
                                         (haskell-debug-muted-face  )
                                         (haskell-debug-newline-face  )
                                         (haskell-debug-trace-number-face  )
                                         (haskell-debug-warning-face  )
                                         (haskell-error-face  )
                                         (haskell-hole-face  )
                                         (haskell-interactive-face-compile-error  )
                                         (haskell-interactive-face-compile-warning  )
                                         (haskell-interactive-face-garbage  )
                                         (haskell-interactive-face-prompt  )
                                         (haskell-interactive-face-prompt-cont  )
                                         (haskell-interactive-face-result  )
                                         (haskell-keyword-face  )
                                         (haskell-liquid-haskell-annotation-face  )
                                         (haskell-literate-comment-face  )
                                         (haskell-operator-face  )
                                         (haskell-pragma-face  )
                                         (haskell-type-face  )
                                         (haskell-warning-face  ))

                               :header-line ((header-line  )
                                             (header-line-highlight  ))

                               :helm ((helm-action  )
                                      (helm-buffer-archive  )
                                      (helm-buffer-directory  )
                                      (helm-buffer-file  )
                                      (helm-buffer-modified  )
                                      (helm-buffer-not-saved  )
                                      (helm-buffer-process  )
                                      (helm-buffer-saved-out  )
                                      (helm-buffer-size  )
                                      (helm-candidate-number  )
                                      (helm-candidate-number-suspended  )
                                      (helm-delete-async-message  )
                                      (helm-eob-line  )
                                      (helm-etags-file  )
                                      (helm-ff-backup-file  )
                                      (helm-ff-denied  )
                                      (helm-ff-directory  )
                                      (helm-ff-dirs  )
                                      (helm-ff-dotted-directory  )
                                      (helm-ff-dotted-symlink-directory  )
                                      (helm-ff-executable  )
                                      (helm-ff-file  )
                                      (helm-ff-file-extension  )
                                      (helm-ff-invalid-symlink  )
                                      (helm-ff-pipe  )
                                      (helm-ff-prefix  )
                                      (helm-ff-rsync-progress  )
                                      (helm-ff-socket  )
                                      (helm-ff-suid  )
                                      (helm-ff-symlink  )
                                      (helm-ff-truename  )
                                      (helm-grep-cmd-line  )
                                      (helm-grep-file  )
                                      (helm-grep-finish  )
                                      (helm-grep-lineno  )
                                      (helm-grep-match  )
                                      (helm-header  )
                                      (helm-header-line-left-margin  )
                                      (helm-helper  )
                                      (helm-history-deleted  )
                                      (helm-history-remote  )
                                      (helm-locate-finish  )
                                      (helm-match  )
                                      (helm-match-item  )
                                      (helm-minibuffer-prompt  )
                                      (helm-moccur-buffer  )
                                      (helm-mode-prefix  )
                                      (helm-non-file-buffer  )
                                      (helm-prefarg  )
                                      (helm-resume-need-update  )
                                      (helm-selection  )
                                      (helm-selection-line  )
                                      (helm-separator  )
                                      (helm-source-header  )
                                      (helm-visible-mark  )
                                      (helm-xref-file-name  )
                                      (helm-xref-line-number  )
                                      (helm-action  )
                                      (helm-bookmark-addressbook  )
                                      (helm-bookmark-directory  )
                                      (helm-bookmark-file  )
                                      (helm-bookmark-gnus  )
                                      (helm-bookmark-info  )
                                      (helm-bookmark-man  )
                                      (helm-bookmark-w3m  ))

                               :help ((help-argument-name  )
                                      (helpful-heading  ))

                               :higlight ((hi-aquamarine  )
                                          (hi-black-b  )
                                          (hi-black-hb  )
                                          (hi-blue  )
                                          (hi-blue-b  )
                                          (hi-green  )
                                          (hi-green-b  )
                                          (hi-pink  )
                                          (hi-red-b  )
                                          (hi-salmon  )
                                          (hi-yellow  )
                                          (highlight  )
                                          (highlight-indent-guides-character-face  )
                                          (highlight-indent-guides-even-face  )
                                          (highlight-indent-guides-odd-face  )
                                          (highlight-indent-guides-stack-character-face  )
                                          (highlight-indent-guides-stack-even-face  )
                                          (highlight-indent-guides-stack-odd-face  )
                                          (highlight-indent-guides-top-character-face  )
                                          (highlight-indent-guides-top-even-face  )
                                          (highlight-indent-guides-top-odd-face  )
                                          (highlight-numbers-number  )
                                          (highlight-quoted-quote  )
                                          (highlight-quoted-symbol  )
                                          (hl-fill-column-face  )
                                          (hl-line  )
                                          (hl-paren-face  )
                                          (hl-todo  ))

                               :h-misc ((holiday  )
                                        (homoglyph  )
                                        (hes-escape-backslash-face  )
                                        (hes-escape-sequence-face  ))

                               :hydra ((hydra-face-amaranth  )
                                       (hydra-face-blue  )
                                       (hydra-face-pink  )
                                       (hydra-face-red  )
                                       (hydra-face-teal  ))

                               :ibuffer ((ibuffer-locked-buffer  ))

                               :info ((info-header-node  )
                                      (info-header-xref  )
                                      (info-index-match  )
                                      (info-menu-header  )
                                      (info-menu-star  )
                                      (info-node  )
                                      (Info-quoted  )
                                      (info-title-1  )
                                      (info-title-2  )
                                      (info-title-3  )
                                      (info-title-4  )
                                      (info-xref  )
                                      (info-xref-visited  ))

                               :i-misc ((internal-border  )
                                        (isearch  )
                                        (isearch-fail  )
                                        (italic  ))

                               :ivy ((ivy-action  )
                                     (ivy-completions-annotations  )
                                     (ivy-confirm-face  )
                                     (ivy-current-match  )
                                     (ivy-cursor  )
                                     (ivy-grep-info  )
                                     (ivy-grep-line-number  )
                                     (ivy-highlight-face  )
                                     (ivy-match-required-face  )
                                     (ivy-minibuffer-match-face-1  )
                                     (ivy-minibuffer-match-face-2  )
                                     (ivy-minibuffer-match-face-3  )
                                     (ivy-minibuffer-match-face-4  )
                                     (ivy-minibuffer-match-highlight  )
                                     (ivy-modified-buffer  )
                                     (ivy-modified-outside-buffer  )
                                     (ivy-org  )
                                     (ivy-prompt-match  )
                                     (ivy-remote  )
                                     (ivy-separator  )
                                     (ivy-subdir  )
                                     (ivy-virtual  )
                                     (ivy-yanked-word  ))

                               :l-misc ((lazy-highlight  )
                                        (linum  )
                                        (linum-highlight-face  )
                                        (linum-relative-current-face  )
                                        (line-number  )
                                        (line-number-current-line  )
                                        (line-number-major-tick  )
                                        (line-number-minor-tick  )
                                        (link  )
                                        (link-visited  )
                                        (log-edit-header  )
                                        (log-edit-summary  )
                                        (log-edit-unknown-header  )
                                        (lv-separator  ))

                               :magit ((magit-bisect-bad  )
                                       (magit-bisect-good  )
                                       (magit-bisect-skip  )
                                       (magit-blame-date  )
                                       (magit-blame-dimmed  )
                                       (magit-blame-hash  )
                                       (magit-blame-heading  )
                                       (magit-blame-highlight  )
                                       (magit-blame-margin  )
                                       (magit-blame-name  )
                                       (magit-blame-summary  )
                                       (magit-branch-current  )
                                       (magit-branch-local  )
                                       (magit-branch-remote  )
                                       (magit-branch-remote-head  )
                                       (magit-branch-upstream  )
                                       (magit-cherry-equivalent  )
                                       (magit-cherry-unmatched  )
                                       (magit-diff-added  )
                                       (magit-diff-added-highlight  )
                                       (magit-diff-base  )
                                       (magit-diff-base-highlight  )
                                       (magit-diff-conflict-heading  )
                                       (magit-diff-context  )
                                       (magit-diff-context-highlight  )
                                       (magit-diff-file-heading  )
                                       (magit-diff-file-heading-highlight  )
                                       (magit-diff-file-heading-selection  )
                                       (magit-diff-hunk-heading  )
                                       (magit-diff-hunk-heading-highlight  )
                                       (magit-diff-hunk-heading-selection  )
                                       (magit-diff-hunk-region  )
                                       (magit-diff-lines-boundary  )
                                       (magit-diff-lines-heading  )
                                       (magit-diff-our  )
                                       (magit-diff-our-highlight  )
                                       (magit-diff-removed  )
                                       (magit-diff-removed-highlight  )
                                       (magit-diff-revision-summary  )
                                       (magit-diff-revision-summary-highlight  )
                                       (magit-diff-their  )
                                       (magit-diff-their-highlight  )
                                       (magit-diff-whitespace-warning  )
                                       (magit-diffstat-added  )
                                       (magit-diffstat-removed  )
                                       (magit-dimmed  )
                                       (magit-filename  )
                                       (magit-hash  )
                                       (magit-head  )
                                       (magit-header-line  )
                                       (magit-header-line-key  )
                                       (magit-header-line-log-select  )
                                       (magit-keyword  )
                                       (magit-keyword-squash  )
                                       (magit-log-author  )
                                       (magit-log-date  )
                                       (magit-log-graph  )
                                       (magit-mode-line-process  )
                                       (magit-mode-line-process-error  )
                                       (magit-popup-argument  )
                                       (magit-popup-disabled-argument  )
                                       (magit-popup-heading  )
                                       (magit-popup-key  )
                                       (magit-popup-option-value  )
                                       (magit-process-ng  )
                                       (magit-process-ok  )
                                       (magit-reflog-amend  )
                                       (magit-reflog-checkout  )
                                       (magit-reflog-cherry-pick  )
                                       (magit-reflog-commit  )
                                       (magit-reflog-merge  )
                                       (magit-reflog-other  )
                                       (magit-reflog-rebase  )
                                       (magit-reflog-remote  )
                                       (magit-reflog-reset  )
                                       (magit-refname  )
                                       (magit-refname-pullreq  )
                                       (magit-refname-stash  )
                                       (magit-refname-wip  )
                                       (magit-section-heading  )
                                       (magit-section-heading-selection  )
                                       (magit-section-highlight  )
                                       (magit-section-secondary-heading  )
                                       (magit-sequence-done  )
                                       (magit-sequence-drop  )
                                       (magit-sequence-exec  )
                                       (magit-sequence-head  )
                                       (magit-sequence-onto  )
                                       (magit-sequence-part  )
                                       (magit-sequence-pick  )
                                       (magit-sequence-stop  )
                                       (magit-signature-bad  )
                                       (magit-signature-error  )
                                       (magit-signature-expired  )
                                       (magit-signature-expired-key  )
                                       (magit-signature-good  )
                                       (magit-signature-revoked  )
                                       (magit-signature-untrusted  )
                                       (magit-tag  ))

                               :m-misc ((match  )
                                        (menu  )
                                        (mouse  )
                                        (mouse-drag-and-drop-region  ))

                               :message ((message-cited-text-1  )
                                         (message-cited-text-2  )
                                         (message-cited-text-3  )
                                         (message-cited-text-4  )
                                         (message-header-cc  )
                                         (message-header-name  )
                                         (message-header-newsgroups  )
                                         (message-header-other  )
                                         (message-header-subject  )
                                         (message-header-to  )
                                         (message-header-xheader  )
                                         (message-mml  )
                                         (message-separator  )
                                         (minibuffer-prompt  )
                                         (mm-command-output  ))

                               :mode-line ((mode-line  )
                                           (mode-line-buffer-id  )
                                           (mode-line-emphasis  )
                                           (mode-line-highlight  )
                                           (mode-line-inactive  ))

                               :n-misc ((next-error  )
                                        (nobreak-hyphen  )
                                        (nobreak-space  ))

                               :org ((org-agenda-calendar-event  )
                                     (org-agenda-calendar-sexp  )
                                     (org-agenda-clocking  )
                                     (org-agenda-column-dateline  )
                                     (org-agenda-current-time  )
                                     (org-agenda-date  )
                                     (org-agenda-date-today  )
                                     (org-agenda-date-weekend  )
                                     (org-agenda-diary  )
                                     (org-agenda-dimmed-todo-face  )
                                     (org-agenda-done  )
                                     (org-agenda-filter-category  )
                                     (org-agenda-filter-effort  )
                                     (org-agenda-filter-regexp  )
                                     (org-agenda-filter-tags  )
                                     (org-agenda-restriction-lock  )
                                     (org-agenda-structure  )
                                     (org-archived  )
                                     (org-block  )
                                     (org-block-begin-line  )
                                     (org-block-end-line  )
                                     (org-checkbox  )
                                     (org-checkbox-statistics-done  )
                                     (org-checkbox-statistics-todo  )
                                     (org-clock-overlay  )
                                     (org-code  )
                                     (org-column  )
                                     (org-column-title  )
                                     (org-date  )
                                     (org-date-selected  )
                                     (org-default  )
                                     (org-document-info  )
                                     (org-document-info-keyword  )
                                     (org-document-title  )
                                     (org-done  )
                                     (org-drawer  )
                                     (org-ellipsis  )
                                     (org-footnote  )
                                     (org-formula  )
                                     (org-headline-done  )
                                     (org-headline-todo  )
                                     (org-hide  )
                                     (org-indent  )
                                     (org-latex-and-related  )
                                     (org-level-1  )
                                     (org-level-2  )
                                     (org-level-3  )
                                     (org-level-4  )
                                     (org-level-5  )
                                     (org-level-6  )
                                     (org-level-7  )
                                     (org-level-8  )
                                     (org-link  )
                                     (org-list-dt  )
                                     (org-macro  )
                                     (org-meta-line  )
                                     (org-mode-line-clock  )
                                     (org-mode-line-clock-overrun  )
                                     (org-priority  )
                                     (org-property-value  )
                                     (org-quote  )
                                     (org-scheduled  )
                                     (org-scheduled-previously  )
                                     (org-scheduled-today  )
                                     (org-sexp-date  )
                                     (org-special-keyword  )
                                     (org-table  )
                                     (org-table-header  )
                                     (org-tag  )
                                     (org-tag-group  )
                                     (org-target  )
                                     (org-time-grid  )
                                     (org-todo  )
                                     (org-upcoming-deadline  )
                                     (org-upcoming-distant-deadline  )
                                     (org-verbatim  )
                                     (org-verse  )
                                     (org-warning  )
                                     (org-habit-alert-face  )
                                     (org-habit-alert-future-face  )
                                     (org-habit-clear-face  )
                                     (org-habit-clear-future-face  )
                                     (org-habit-overdue-face  )
                                     (org-habit-overdue-future-face  )
                                     (org-habit-ready-face  )
                                     (org-habit-ready-future-face  ))

                               :outline ((outline-1  )
                                         (outline-2  )
                                         (outline-3  )
                                         (outline-4  )
                                         (outline-5  )
                                         (outline-6  )
                                         (outline-7  )
                                         (outline-8  ))

                               :package ((package-description  )
                                         (package-help-section-name  )
                                         (package-name  )
                                         (package-status-avail-obso  )
                                         (package-status-available  )
                                         (package-status-built-in  )
                                         (package-status-dependency  )
                                         (package-status-disabled  )
                                         (package-status-external  )
                                         (package-status-held  )
                                         (package-status-incompat  )
                                         (package-status-installed  )
                                         (package-status-new  )
                                         (package-status-unsigned  ))

                               :persp ((persp-face-lighter-buffer-not-in-persp  )
                                       (persp-face-lighter-default  )
                                       (persp-face-lighter-nil-persp  ))

                               :popup ((popup-face  )
                                       (popup-isearch-match  )
                                       (popup-menu-face  )
                                       (popup-menu-mouse-face  )
                                       (popup-menu-selection-face  )
                                       (popup-menu-summary-face  )
                                       (popup-scroll-bar-background-face  )
                                       (popup-scroll-bar-foreground-face  )
                                       (popup-summary-face  )
                                       (popup-tip-face  ))

                               :pulse ((pulse-highlight-face  )
                                       (pulse-highlight-start-face  ))

                               :p-misc ((powerline-active1  )
                                        (powerline-inactive0  )
                                        (powerline-inactive1  )
                                        (powerline-inactive2  ))

                               :query ((query-replace  ))

                               :rainbow ((rainbow-delimiters-base-error-face  )
                                         (rainbow-delimiters-base-face  )
                                         (rainbow-delimiters-depth-1-face  )
                                         (rainbow-delimiters-depth-2-face  )
                                         (rainbow-delimiters-depth-3-face  )
                                         (rainbow-delimiters-depth-4-face  )
                                         (rainbow-delimiters-depth-5-face  )
                                         (rainbow-delimiters-depth-6-face  )
                                         (rainbow-delimiters-depth-7-face  )
                                         (rainbow-delimiters-depth-8-face  )
                                         (rainbow-delimiters-depth-9-face  )
                                         (rainbow-delimiters-mismatched-face  )
                                         (rainbow-delimiters-unmatched-face  )
                                         (rainbox-delimiters-depth-12-face  )
                                         (rainbox-delimiters-depth-8-face  ))

                               :r-misc ((read-multiple-choice-face  )
                                        (reb-match-0  )
                                        (reb-match-1  )
                                        (reb-match-2  )
                                        (reb-match-3  )
                                        (reb-regexp-grouping-backslash  )
                                        (reb-regexp-grouping-construct  )
                                        (rectangle-preview  )
                                        (region  )
                                        (rmail-header-name  )
                                        (rmail-highlight  )
                                        (rxt-highlight-face  ))

                               :s-misc ((scroll-bar  )
                                        (secondary-selection  )
                                        (shadow  )
                                        (solaire-mode-line-face  )
                                        (solaire-mode-line-inactive-face  )
                                        (solaire-org-hide-face  ))

                               :show-paren ((show-paren-match  )
                                            (show-paren-match-expression  )
                                            (show-paren-mismatch  ))

                               :smerge ((smerge-base  )
                                        (smerge-lower  )
                                        (smerge-markers  )
                                        (smerge-refined-added  )
                                        (smerge-refined-changed  )
                                        (smerge-refined-removed  )
                                        (smerge-upper  ))

                               :so-long ((so-long-mode-line-active  )
                                         (so-long-mode-line-inactive  ))

                               :sp-pair ((sp-pair-overlay-face  )
                                         (sp-show-pair-enclosing  )
                                         (sp-show-pair-match-content-face  )
                                         (sp-show-pair-match-face  )
                                         (sp-show-pair-mismatch-face  )
                                         (sp-wrap-overlay-closing-pair  )
                                         (sp-wrap-overlay-face  )
                                         (sp-wrap-overlay-opening-pair  )
                                         (sp-wrap-tag-overlay-face  ))

                               :success ((success  ))

                               :swipe ((swiper-background-match-face-1  )
                                       (swiper-background-match-face-2  )
                                       (swiper-background-match-face-3  )
                                       (swiper-background-match-face-4  )
                                       (swiper-line-face  )
                                       (swiper-match-face-1  )
                                       (swiper-match-face-2  )
                                       (swiper-match-face-3  )
                                       (swiper-match-face-4  ))

                               :tab-bar ((tab-bar  )
                                         (tab-bar-tab  )
                                         (tab-bar-tab-inactive  )
                                         (tab-line  )
                                         (tabulated-list-fake-header  ))

                               :t-misc ((tool-bar  )
                                        (tooltip  )
                                        (trailing-whitespace  ))

                               :transient ((transient-active-infix  )
                                           (transient-amaranth  )
                                           (transient-argument  )
                                           (transient-blue  )
                                           (transient-disabled-suffix  )
                                           (transient-enabled-suffix  )
                                           (transient-heading  )
                                           (transient-inactive-argument  )
                                           (transient-inactive-value  )
                                           (transient-inapt-suffix  )
                                           (transient-key  )
                                           (transient-mismatched-key  )
                                           (transient-nonstandard-key  )
                                           (transient-pink  )
                                           (transient-red  )
                                           (transient-separator  )
                                           (transient-teal  )
                                           (transient-unreachable  )
                                           (transient-unreachable-key  )
                                           (transient-value  ))

                               :tty ((tty-menu-disabled-face  )
                                     (tty-menu-enabled-face  )
                                     (tty-menu-selected-face  ))

                               :u-misc ((underline  ))

                               :undo-tree ((undo-tree-visualizer-active-branch-face  )
                                           (undo-tree-visualizer-current-face  )
                                           (undo-tree-visualizer-default-face  )
                                           (undo-tree-visualizer-register-face  )
                                           (undo-tree-visualizer-unmodified-face  ))

                               :v-misc ((variable-pitch  )
                                        (vertical-border  )
                                        (vi-tilde-fringe-face  ))

                               :vc ((vc-conflict-state  )
                                    (vc-edited-state  )
                                    (vc-locally-added-state  )
                                    (vc-locked-state  )
                                    (vc-missing-state  )
                                    (vc-needs-update-state  )
                                    (vc-removed-state  )
                                    (vc-state-base  )
                                    (vc-up-to-date-state  ))

                               :w-misc ((w3m-haddock-heading-face  )
                                        (warning  )
                                        (which-func  ))

                               :which-key ((which-key-command-description-face  )
                                           (which-key-docstring-face  )
                                           (which-key-group-description-face  )
                                           (which-key-highlighted-command-face  )
                                           (which-key-key-face  )
                                           (which-key-local-map-description-face  )
                                           (which-key-note-face  )
                                           (which-key-separator-face  )
                                           (which-key-special-key-face  ))

                               :whitespace ((whitespace-big-indent  )
                                            (whitespace-empty  )
                                            (whitespace-hspace  )
                                            (whitespace-indentation  )
                                            (whitespace-line  )
                                            (whitespace-newline  )
                                            (whitespace-space  )
                                            (whitespace-space-after-tab  )
                                            (whitespace-space-before-tab  )
                                            (whitespace-tab  )
                                            (whitespace-trailing  ))

                               :widget ((widget-button  )
                                        (widget-button-pressed  )
                                        (widget-documentation  )
                                        (widget-field  )
                                        (widget-inactive  )
                                        (widget-single-line-field  ))

                               :window ((window-divider  )
                                        (window-divider-first-pixel  )
                                        (window-divider-last-pixel  ))

                               :xref ((xref-file-header  )
                                      (xref-line-number  )
                                      (xref-match  ))

                               :yas ((yas--field-debug-face  )
                                     (yas-field-highlight-face  ))
                               )
              )
