;;; ../../../Volumes/documents/github/emacs_files/packages/jg-themes/template-theme2.el -*- lexical-binding: t; -*-

;;; doom-acario-light-theme.el --- Acario light theme -*- no-byte-compile: t; -*-
(require 'doom-themes)

;;; Variables

;;; Theme definition
(def-doom-theme jg
  "A light theme inspired by Acario light"

;;;; Colors
  ;; name        default   256         16
  ((bg         '("#F5F5F9" "color-255" "black"        ))
   (bg-alt     '("#E9E9F2" "color-254" "brightblack"  ))
   (base0      '("#D0D0E3" "color-188" "black"        ))
   (base1      '("#D0D0E3" "color-188" "brightblack"  ))
   (base2      '("#C0CCD0" "color-152" "brightblack"  ))
   (base3      '("#9EA6B0" "color-103" "brightblack"  ))
   (base4      '("#585C6C" "color-60"  "brightblack"  ))
   (base5      '("#4E4E4E" "color-239" "brightblack"  ))
   (base6      '("#3A3A3A" "color-237" "white"        ))
   (base7      '("#303030" "color-236" "white"        ))
   (base8      '("#1E1E33" "color-236" "brightwhite"  ))
   (fg         '("#0F1019" "color-234" "brightwhite"  ))
   (fg-alt     '("#0D0E16" "color-233" "brightwhite"  ))

   (grey       base5)

   (red        '("#D70000" "color-160" "red"          ))
   (green      '("#005F00" "color-22"  "green"        ))
   (yellow     '("#AF8700" "color-136" "yellow"       ))
   (blue       '("#1F55A0" "color-25"  "blue"         ))
   (magenta    '("#AF005F" "color-125" "magenta"      ))
   (cyan       '("#007687" "color-30"  "cyan"         ))

   (orange     '("#D75F00" "color-166" "brightred"    ))
   (teal       '("#009B7C" "color-36"  "brightgreen"  ))
   (violet     '("#8700AF" "color-91"  "brightmagenta"))

   (bg-blue    '("#DEEAF8" "color-189"   "blue"         ))
   (dark-blue  bg-blue)
   (bg-cyan    '("#D5FAFF" "color-195"   "cyan"         ))
   (dark-cyan  bg-cyan)

;;;; face categories -- required for all themes
   (highlight      teal)
   (vertical-bar   base0)
   (selection      bg-blue)
   (builtin        blue)
   (comments       cyan )
   (doc-comments   cyan)
   (constants      magenta)
   (functions      yellow)
   (keywords       green)
   (methods        cyan)
   (operators      blue)
   (type           blue)
   (strings        green)
   (variables      (doom-darken cyan 0.4))
   (numbers        orange)
   (region         base2)
   (error          red)
   (warning        orange)
   (success        green)
   (vc-modified    yellow)
   (vc-added       green)
   (vc-deleted     red)

;;;; custom categories
   (hidden bg)
   (-modeline-dark doom-acario-light-brighter-modeline)
   (-modeline-bright -modeline-dark)
   (-modeline-pad
    (when doom-acario-light-padded-modeline
      (if (integerp doom-acario-light-padded-modeline) doom-acario-light-padded-modeline 4)))

   (modeline-fg     red)
   (modeline-fg-alt red)

   (modeline-bg red)
   (modeline-bg-l red)
   (modeline-bg-inactive   red)
   (modeline-bg-inactive-l red))

;;;; --- extra faces ------------------------
  (
   ((company-tooltip-selection &override) :foreground iopink)
   ((diredp-dir-exec-priv &inherit diredp-dir-priv))
   ((hes-escape-backslash-face &override) :inherit 'normal :foreground red)
   ((hes-escape-sequence-face &override) :inherit 'normal :foreground red)
   ((highlight-numbers-number &override) :inherit 'normal :foreground numbers)
   ((lazy-highlight &override) :background iocyan  :foreground bg :distant-foreground base0 :weight 'bold)
   ((line-number &override) :foreground base4 :background base1)
   ((line-number-current-line &override) :foreground fg)
   ((nav-flash-face &override) :background bg-alt :foreground iopink)
   ((org-block &override) :background bg-alt)
   ((org-block-begin-line &override) :foreground comments :background bg)
   ((org-quote &override) :background bg-alt)
   ((outline-1 &override) :foreground blue)
   ((outline-2 &override) :foreground magenta)
   ((outline-3 &override) :foreground dark-cyan)
   ((outline-6 &override) :foreground (doom-lighten dark-cyan 0.2))
   ((outline-7 &override) :foreground (doom-lighten blue 0.4))
   ((outline-8 &override) :foreground (doom-lighten magenta 0.4))
   ((paren-face-match &override) :foreground iopink :background bg :weight 'ultra-bold)
   ((tooltip &override) :background bg)
   ((whitespace-tab &override) :background bg)
   (anzu-match-1           :background green)
   (anzu-match-2           :background faded-yellow)
   (anzu-match-3           :background aquamarine4)
   (anzu-mode-line         :foreground yellow :weight 'bold)
   (anzu-replace-highlight :inherit 'isearch)
   (anzu-replace-to        :foreground yellow)
   (centaur-tabs-unselected :background bg-alt :foreground base4)
   (company-echo-common                       :foreground faded-red)
   (company-preview                           :background lightblue4)
   (company-preview-common                    :foreground base7)
   (company-preview-search                    :background turquoise4)
   (company-scrollbar-bg                      :background base1)
   (company-scrollbar-fg                      :background bg-alt)
   (company-template-field                    :foreground "black" :background yellow)
   (company-tooltip                           :background bg-alt)
   (company-tooltip-annotation                :foreground green)
   (company-tooltip-annotation-selection      :inherit 'company-tooltip-annotation)
   (company-tooltip-common                    :foreground blue :underline t)
   (company-tooltip-common-selection          :foreground blue :underline t)
   (company-tooltip-selection                 :foreground violet :background base2)
   (cursor    :foreground fg)
   (diff-changed                   :background nil :foreground base6)
   (diff-indicator-added           :inherit 'diff-added)
   (diff-indicator-changed         :inherit 'diff-changed)
   (diff-indicator-removed         :inherit 'diff-removed)
   (diff-removed                   :background nil :foreground red)
   (diredfl-autofile-name :foreground base5)
   (diredfl-compressed-file-name :foreground base5)
   (diredfl-compressed-file-suffix :foreground faded-blue)
   (diredfl-dir-priv :foreground blue :backgtround dark-blue)
   (diredfl-exec-priv :foreground blue :backgrond dark-blue)
   (diredfl-file-name :foreground base5)
   (diredfl-file-suffix :foreground light4)
   (diredfl-link-priv :foreground magenta)
   (diredfl-no-priv :foreground base5)
   (diredfl-number :foreground yellow)
   (diredfl-other-priv :foreground violet)
   (diredfl-rare-priv :foreground base5)
   (diredp-compressed-file-suffix :foreground faded-blue)
   (diredp-date-time :foreground light3)
   (diredp-dir-name :foreground faded-blue)
   (diredp-dir-priv :foreground faded-blue :background dark-blue)
   (diredp-file-name :foreground base5)
   (diredp-file-suffix :foreground light4)
   (diredp-ignored-file-name :foreground base5)
   (diredp-link-priv :foreground faded-aqua)
   (diredp-no-priv :foreground base4)
   (diredp-number :foreground faded-blue)
   (diredp-other-priv :foreground base2)
   (diredp-rare-priv :foreground base4)
   (diredp-symlink :foreground orange)
   (doom-dashboard-banner      :foreground (doom-darken base4 0.3))
   (doom-dashboard-footer-icon :foreground (doom-darken yellow 0.4))
   (doom-dashboard-loaded      :foreground yellow)
   (doom-dashboard-menu-desc   :foreground green)
   (doom-dashboard-menu-title  :foreground green)
   (doom-modeline-bar :background (if -modeline-bright modeline-bg highlight))
   (doom-modeline-buffer-file :inherit 'mode-line-buffer-id :weight 'bold)
   (doom-modeline-buffer-path :inherit 'mode-line-emphasis :weight 'bold)
   (doom-modeline-buffer-project-root :foreground green :weight 'bold)
   (ediff-current-diff-A        :foreground red   :background (doom-lighten red 0.8))
   (ediff-current-diff-Ancestor :foreground teal  :background (doom-lighten teal 0.8))
   (ediff-current-diff-B        :foreground green :background (doom-lighten green 0.8))
   (ediff-current-diff-C        :foreground blue  :background (doom-lighten blue 0.8))
   (elscreen-tab-other-screen-face :background "#353a42" :foreground "#1e2022")
   (evil-goggles-default-face :inherit 'region :background (doom-blend region bg 0.5))
   (flycheck-info :underline `(:style wave :color ,blue))
   (font-latex-math-face :foreground green)
   (font-lock-comment-face :foreground comments :background (if doom-Iosvkem-comment-bg (doom-lighten bg 0.05)) :slant 'italic)
   (font-lock-doc-face :inherit 'font-lock-comment-face :foreground doc-comments :slant 'italic)
   (font-lock-function-name-face :foreground functions :weight 'bold)
   (git-gutter+-added    :foreground faded-green :background green)
   (git-gutter+-deleted  :foreground faded-red :backgrond red)
   (git-gutter+-modified :foreground faded-blue :background blue)
   (git-gutter:added    :foreground faded-green :background green)
   (git-gutter:deleted  :foreground faded-red :backgrond red)
   (git-gutter:modified :foreground faded-blue :background blue)
   (helm-M-x-key                :foreground orange)
   (helm-action                 :foreground base8 :underline t)
   (helm-bookmark-addressbook   :foreground red)
   (helm-bookmark-directory     :foreground violet)
   (helm-bookmark-file          :foreground faded-blue)
   (helm-bookmark-gnus          :foreground magenta)
   (helm-bookmark-info          :foreground turquoise4)
   (helm-bookmark-man           :foreground sienna)
   (helm-bookmark-w3m           :foreground yellow)
   (helm-buffer-directory       :foreground "white" :background blue)
   (helm-buffer-not-saved       :foreground red)
   (helm-buffer-process         :foreground burlywood4)
   (helm-buffer-saved-out       :foreground red)
   (helm-buffer-size            :foreground violet)
   (helm-candidate-number       :background blue :foreground bg)
   (helm-ff-directory           :foreground violet)
   (helm-ff-executable          :foreground turquoise4)
   (helm-ff-file                :foreground sienna)
   (helm-ff-invalid-symlink     :foreground "white" :background red)
   (helm-ff-prefix              :foreground "black" :background yellow)
   (helm-ff-symlink             :foreground orange)
   (helm-grep-cmd-line          :foreground green)
   (helm-grep-file              :foreground magenta)
   (helm-grep-finish            :foreground turquoise4)
   (helm-grep-lineno            :foreground orange)
   (helm-grep-match             :foreground yellow)
   (helm-grep-running           :foreground red)
   (helm-header                 :foreground aquamarine4)
   (helm-helper                 :foreground aquamarine4)
   (helm-history-deleted        :foreground "black" :background red)
   (helm-history-remote         :foreground faded-red)
   (helm-lisp-completion-info   :foreground faded-orange)
   (helm-lisp-show-completion   :foreground red)
   (helm-locate-finish          :foreground "white" :background aquamarine4)
   (helm-match                  :foreground orange)
   (helm-moccur-buffer          :foreground cyan :underline t)
   (helm-prefarg                :foreground turquoise4)
   (helm-selection              :foreground "white" :background base2)
   (helm-selection-line         :foreground "white" :background base2)
   (helm-separator              :foreground faded-red)
   (helm-source-header          :foreground base5)
   (helm-visible-mark           :foreground "black" :background light3)
   (isearch           :foreground "black" :background orange)
   (isearch-fail      :foreground fg :background red)
   (ivy-current-match :background dark-blue :distant-foreground base0 :weight 'normal)
   (ivy-minibuffer-match-face-1     :foreground orange)
   (ivy-minibuffer-match-face-2     :foreground yellow)
   (ivy-minibuffer-match-face-3     :foreground faded-orange)
   (ivy-minibuffer-match-face-4     :foreground faded-yellow)
   (ivy-posframe               :background bg-alt)
   (lazy-highlight    :background base2  :foreground base8 :distant-foreground base0 :weight 'bold)
   (linum     :foreground base4 :background base2)
   (linum-highlight-face :foreground orange :background base2)
   (linum-relative-current-face :foreground orange :background base2)
   (magit-bisect-bad                      :foreground faded-red)
   (magit-bisect-good                     :foreground faded-green)
   (magit-bisect-skip                     :foreground faded-yellow)
   (magit-blame-heading                   :foreground base7 :background base2)
   (magit-branch-current                  :underline blue :inherit 'magit-branch-local)
   (magit-branch-local                    :foreground blue)
   (magit-branch-remote                   :foreground green)
   (magit-cherry-equivalent               :foreground violet)
   (magit-cherry-unmatched                :foreground cyan)
   (magit-diff-added                      :foreground green)
   (magit-diff-added-highlight            :foreground green :inherit 'magit-diff-context-highlight)
   (magit-diff-base                       :background faded-yellow :foreground base5)
   (magit-diff-base-highlight             :background faded-yellow :foreground base7)
   (magit-diff-context                    :foreground base1  :foreground base6)
   (magit-diff-context-highlight          :background base1 :foreground base7)
   (magit-diff-hunk-heading               :background base3 :foreground base5)
   (magit-diff-hunk-heading-highlight     :background base2 :foreground base7)
   (magit-diff-hunk-heading-selection     :background base2 :foreground orange)
   (magit-diff-lines-heading              :background faded-orange :foreground base7)
   (magit-diff-removed                    :foreground red)
   (magit-diff-removed-highlight          :foreground red :inherit 'magit-diff-context-highlight)
   (magit-diffstat-added                  :foreground faded-green)
   (magit-diffstat-removed                :foreground faded-red)
   (magit-dimmed                          :foreground base4)
   (magit-hash                            :foreground blue)
   (magit-log-author                      :foreground red)
   (magit-log-date                        :foreground cyan)
   (magit-log-graph                       :foreground base4)
   (magit-process-ng                      :foreground red :weight 'bold)
   (magit-process-ok                      :foreground green :weight 'bold)
   (magit-reflog-amend                    :foreground violet)
   (magit-reflog-checkout                 :foreground blue)
   (magit-reflog-cherry-pick              :foreground green)
   (magit-reflog-commit                   :foreground green)
   (magit-reflog-merge                    :foreground green)
   (magit-reflog-other                    :foreground cyan)
   (magit-reflog-rebase                   :foreground violet)
   (magit-reflog-remote                   :foreground blue)
   (magit-reflog-reset                    :foreground red)
   (magit-refname                         :foreground light4)
   (magit-section-heading                 :foreground yellow :weight 'bold)
   (magit-section-heading-selection       :foreground faded-yellow)
   (magit-section-highlight               :background base1)
   (magit-sequence-drop                   :foreground faded-yellow)
   (magit-sequence-head                   :foreground cyan)
   (magit-sequence-part                   :foreground yellow)
   (magit-sequence-stop                   :foreground green)
   (magit-signature-bad                   :foreground red :weight 'bold)
   (magit-signature-error                 :foreground red)
   (magit-signature-expired               :foreground orange)
   (magit-signature-good                  :foreground green)
   (magit-signature-revoked               :foreground violet)
   (magit-signature-untrusted             :foreground blue)
   (magit-tag                             :foreground yellow)
   (message-cited-text :inherit 'font-lock-comment-face)
   (message-header-cc :inherit 'font-lock-variable-name-face)
   (message-header-name :inherit 'font-lock-keyword-face)
   (message-header-other :inherit 'font-lock-variable-name-face)
   (message-header-subject :foreground orange :weight 'bold)
   (message-mml :foregrond faded-green :weight 'bold)
   (mmm-default-submode-face :background base1)
   (mode-line :background modeline-bg :foreground modeline-fg :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg)))
   (mode-line-emphasis :foreground (if -modeline-bright base8 highlight))
   (mode-line-inactive :background modeline-bg-inactive :foreground modeline-fg-alt :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-inactive)))
   (org-agenda-date-today       :foreground base7 :weight 'bold :italic t)
   (org-agenda-done             :foreground cyan)
   (org-agenda-structure        :inherit 'font-lock-comment-face)
   (org-archived                :foreground base7 :weight 'bold)
   (org-block                   :background base1 :extend t)
   (org-block-begin-line        :background base2 :extend t)
   (org-block-end-line          :background base2 :extend t)
   (org-date                    :foreground blue :underline t)
   (org-deadline-announce       :foreground faded-red)
   (org-document-info           :foreground faded-blue)
   (org-document-title          :foreground faded-blue)
   (org-done                    :foreground cyan :weight 'bold :bold t)
   (org-drawer                  :inherit 'font-lock-function-name-face)
   (org-ellipsis                :foreground light4)
   (org-footnote                :foreground cyan :underline t)
   (org-formula                 :foreground yellow)
   (org-habit-alert-face          :background faded-yellow)
   (org-habit-alert-future-face   :background yellow)
   (org-habit-clear-face          :background faded-blue)
   (org-habit-clear-future-face   :background blue)
   (org-habit-overdue-face        :background faded-red)
   (org-habit-overdue-future-face :background red)
   (org-habit-ready-face          :background faded-green)
   (org-habit-ready-future-face   :background green)
   (org-headline-done           :foreground cyan)
   (org-hide :foreground hidden)
   (org-hide :foreground hidden)
   (org-latex-and-related       :foreground blue)
   (org-level-1                 :foreground blue)
   (org-level-2                 :foreground yellow)
   (org-level-3                 :foreground violet)
   (org-level-4                 :foreground red)
   (org-level-5                 :foreground green)
   (org-level-6                 :foreground cyan)
   (org-level-7                 :foreground faded-blue)
   (org-level-8                 :foreground orange)
   (org-link                    :foreground faded-aqua :underline t)
   (org-scheduled               :foreground yellow)
   (org-scheduled-previously    :foreground faded-red)
   (org-scheduled-today         :foreground blue)
   (org-sexp-date               :foreground faded-blue :underline t)
   (org-table                   :foreground blue)
   (org-tag                     :bold t :weight 'bold)
   (org-time-grid               :foreground faded-orange)
   (org-todo                    :foreground red :weight 'bold :bold t)
   (org-upcoming-deadline       :inherit 'font-lock-keyword-face)
   (org-warning                 :foreground red :weight 'bold :bold t)
   (popup-face :foreground base6  :background base1)
   (popup-menu-mouse-face :foreground fg :background faded-green)
   (popup-menu-selection-face :foreground fg :background faded-green)
   (popup-tip-face :foreground base5 :background base2)
   (rainbow-delimiters-depth-11-face :foreground delimiter-3)
   (rainbow-delimiters-depth-3-face :foreground delimiter-3)
   (rainbow-delimiters-depth-4-face :foreground faded-orange)
   (rainbow-delimiters-depth-7-face :foreground delimiter-3)
   (rainbow-delimiters-unmatched-face: :foreground fg :background 'nil)
   (rainbox-delimiters-depth-12-face :foreground faded-orange)
   (rainbox-delimiters-depth-8-face :foreground faded-orange)
   (solaire-mode-line-face :inherit 'mode-line :background modeline-bg-l :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-l)))
   (solaire-mode-line-inactive-face :inherit 'mode-line-inactive :background modeline-bg-inactive-l :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-inactive-l)))
   (solaire-org-hide-face :foreground hidden)
   (swiper-background-match-face-1 :inherit 'unspecified :background base2)
   (swiper-background-match-face-2 :inherit 'unspecified :background base3)
   (swiper-background-match-face-3 :inherit 'unspecified :background base4)
   (swiper-background-match-face-4 :inherit 'unspecified :background base5)
   (swiper-line-face    :background base3 :foreground base0)
   (swiper-match-face-1 :inherit 'unspecified :background base1   :foreground base5)
   (swiper-match-face-2 :inherit 'unspecified :background orange  :foreground base0 :weight 'bold)
   (swiper-match-face-3 :inherit 'unspecified :background violet :foreground base1 :weight 'bold)
   (swiper-match-face-4 :inherit 'unspecified :background green   :foreground base2 :weight 'bold)
   (tooltip :background base1 :foreground base6)
   (web-mode-current-element-highlight-face :background dark-blue :foreground bg)
   (whitespace-empty :foreground 'nil :background 'nil)
   (whitespace-indentation :foreground base4 :background bg)
   (whitespace-line :foreground red :background base1)
   (whitespace-trailing :foreground red :background base1)
   )
;;;; --- extra variables ---------------------
  ;; ()
  )
)
        ;;; doom-acario-light-theme.el ends here
