verbosity                = 2
default_tasks            = []
action_string_formatting = "new"
notify                   = { say-on-exit = false }
globbing                 = { ignores = ['.git', '.DS_Store', "__pycache__"] }
subtask                  = { sleep = 1 }
batch                    = { sleep = 1 }
zip                      = { level = 5 }

[logging]
stream = { level = "INFO", format  = "{levelname:<8} : {message}", filters = ["doot"] }
file   = { level = "DEBUG", format = "{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})", filters =  ["doot"] }

[[directories]] # Core
src         = "src"
codegen     = "src/_codegen"
temp        = ".temp"
build       = "build"

[[directories]] # github pages / pelican
site             = "src"
site_build       = "build/{{cookiecutter.proj_name}}"
pelican_settings = "pelican.toml"

[group.epub]
