(deftheme jgTheme
  "Created 2017-01-14.")

(custom-theme-set-variables
 'jgTheme
 '(auto-save-file-name-transforms (quote ((".*" "~/.emacs.d/autosaves/`" t))))
 '(backup-directory-alist (quote ((".*" . "~/.emacs.d/backups/"))))
 '(dired-use-ls-dired nil)
 '(display-buffer-alist (quote (("*shell*" display-buffer-same-window (nil)))))
 '(flycheck-disabled-checkers (quote (emacs-lisp-checkdoc javascript-eslint)))
 '(icicle-Completions-text-scale-decrease 0)
 '(org-agenda-files (quote ("~/github/jg_shell/ShellNotes.org" "/Users/jgrey/scripts/orgFiles/myMasterOrg.org")))
 '(org-fast-tag-selection-single-key nil)
 '(org-from-is-user-regexp "\\<John Grey\\>")
 '(org-group-tags nil)
 '(org-use-fast-tag-selection t)
 '(package-selected-packages (quote (kooten-theme danneskjold-theme darcula-theme blackboard-theme atom-dark-theme alect-themes afternoon-theme abyss-theme org org-bookmark-heading org-agenda-property org-ac etags-table etags-select ac-etags slime folding scala-mode evil code-library cmake-font-lock cmake-project cmake-mode sclang-snippets sclang-extensions multi-web-mode web-mode multi-term mmm-mode pony-mode python-django zones writegood-mode smooth-scrolling rust-mode rainbow-mode rainbow-delimiters rainbow-blocks racket-mode popup-kill-ring osc markdown-mode magit-filenotify lua-mode lorem-ipsum json-mode js3-mode js2-highlight-vars js-doc jedi go-mode fsharp-mode flyparens flymake-rust flymake-json flymake-jshint flymake-go flycheck-haskell elpy doremi-mac doremi-frm doremi-cmd d-mode csharp-mode context-coloring color-theme browse-kill-ring apples-mode anaconda-mode)))
 '(sclang-auto-scroll-post-buffer t)
 '(sclang-eval-line-forward t)
 '(sclang-help-path (quote ("/Applications/SuperCollider/Help")))
 '(sclang-library-configuration-file "~/.emacs.setup/lisp/scel/sclang.yaml")
 '(sclang-program "sclang")
 '(sclang-rtf-editor-program "emacs")
 '(sclang-runtime-directory "./")
 '(sclang-show-workspace-on-startup nil)
 '(show-paren-mode t))

(custom-theme-set-faces
 'jgTheme
 '(bold ((t (:foreground "purple" :weight bold))))
 '(context-coloring-level-0-face ((t (:foreground "white"))))
 '(context-coloring-level-1-face ((t (:foreground "white"))))
 '(cursor ((t (:background "black" :inverse-video t))))
 '(custom-variable-tag ((t (:foreground "cyan" :weight bold))))
 '(diff-added ((t (:inherit diff-changed :background "green" :foreground "black"))))
 '(diff-file-header ((t (:foreground "white" :weight bold))))
 '(diff-header ((t (:background "color-24" :foreground "black"))))
 '(diff-indicator-removed ((t (:inherit diff-removed :foreground "black"))))
 '(diff-removed ((t (:inherit diff-changed :background "red" :foreground "black"))))
 '(flyspell-incorrect ((t (:inherit error))))
 '(font-lock-comment-delimiter-face ((t (:background "red"))))
 '(font-lock-comment-face ((t (:foreground "#AA0223"))))
 '(font-lock-function-name-face ((t (:foreground "color-28"))))
 '(header-line ((t (:inherit mode-line :foreground "blue" :inverse-video nil :underline t))))
 '(minibuffer-prompt ((t (:foreground "cyan"))))
 '(org-agenda-clocking ((t (:inherit secondary-selection :foreground "black"))))
 '(org-agenda-column-dateline ((t (:inherit org-column :foreground "black"))))
 '(org-agenda-restriction-lock ((t (:background "#eeeeee" :foreground "black"))))
 '(org-agenda-structure ((t (:foreground "bright green"))))
 '(org-clock-overlay ((t (:background "yellow25"))))
 '(org-column ((t (:background "grey90" :foreground "black" :strike-through nil :underline nil :slant normal :weight normal))))
 '(org-column-title ((t (:background "grey90" :foreground "black" :underline t :weight bold))))
 '(org-document-info ((t (:foreground "color-38"))))
 '(org-document-title ((t (:foreground "color-39" :weight bold))))
 '(org-tag ((t (:inverse-video t))))
 '(secondary-selection ((t (:background "color-90"))))
 '(show-paren-match ((t (:background "green"))))
 '(show-paren-mismatch ((t (:background "red" :foreground "black"))))
 '(warning ((t (:foreground "darkred" :weight bold))))
 '(window-divider ((t (:foreground "color-19"))))
 '(window-divider-first-pixel ((t (:foreground "color-19"))))
 '(hl-line ((t (:background "white" :foreground "black")))))

(provide-theme 'jgTheme)
