(package! helm)
(package! dash)
(package! org)
(package! evil)
(package! tag-clean-minor-mode :recipe '(:local-repo "~/.doom.d/packages/tag-clean-minor-mode"))
(package! tag-mode :recipe '(:local-repo "~/.doom.d/packages/tag-mode"))
(package! hydra)
(package! cl-lib :built-in t)
(package! ivy)
