;; Lower Greek Letters
(defun alpha-char  () "Insert Greek Lower Alpha"  (interactive) (insert "α"))
(defun beta-char   () "Insert Greek Lower Beta"  (interactive) (insert "β"))
(defun gamma-char  () "Insert lower greek gamma" (interactive) (insert "γ"))
(defun delta-char  () "Insert lower greek delta" (interactive) (insert "δ"))
(defun epsilon-char() "Insert lower greek epsilon" (interactive) (insert "ε"))
(defun zeta-char   () "Insert lower greek zeta" (interactive) (insert "ζ"))
(defun eta-char    () "Insert lower greek eta" (interactive) (insert "η"))
(defun theta-char  () "Insert lower greek theta" (interactive) (insert "θ"))
(defun iota-char   () "Insert lower greek iota" (interactive) (insert "ι"))
(defun kappa-char  () "Insert lower greek kappa" (interactive) (insert "κ"))
(defun lambda-char () "Insert lower greek lambda" (interactive) (insert "λ"))
(defun mu-char     () "Insert lower greek mu" (interactive) (insert "μ"))
(defun nu-char     () "Insert lower greek nu" (interactive) (insert "ν"))
(defun xi-char     () "Insert lower greek xi" (interactive) (insert "ξ"))
(defun omicron-char() "Insert lower greek omicron" (interactive) (insert "ο"))
(defun pi-char     () "Insert lower greek pi" (interactive) (insert "π"))
(defun rho-char    () "Insert lower greek rho" (interactive) (insert "ρ"))
(defun sigma-char  () "Insert lower greek sigma" (interactive) (insert "σ"))
(defun tau-char    () "Insert lower greek tau" (interactive) (insert "τ"))
(defun upsilon-char() "Insert lower greek upsilon" (interactive) (insert "υ"))
(defun phi-char    () "Insert lower greek phi" (interactive) (insert "φ"))
(defun chi-char    () "Insert lower greek chi" (interactive) (insert "χ"))
(defun psi-char    () "Insert lower greek psi" (interactive) (insert "ψ"))
(defun omega-char  () "Insert lower greek omega" (interactive) (insert "ω"))

;; Upper Greek letters
(defun ualpha-char  () "Insert Greek Lower Alpha"  (interactive) (insert "Α"))
(defun ubeta-char   () "Insert Greek Lower Beta"  (interactive) (insert "Β"))
(defun ugamma-char  () "Insert lower greek gamma" (interactive) (insert "Γ"))
(defun udelta-char  () "Insert lower greek delta" (interactive) (insert "Δ"))
(defun uepsilon-char() "Insert lower greek epsilon" (interactive) (insert "Ε"))
(defun uzeta-char   () "Insert lower greek zeta" (interactive) (insert "Ζ"))
(defun ueta-char    () "Insert lower greek eta" (interactive) (insert "Η"))
(defun utheta-char  () "Insert lower greek theta" (interactive) (insert "Θ"))
(defun uiota-char   () "Insert lower greek iota" (interactive) (insert "Ι"))
(defun ukappa-char  () "Insert lower greek kappa" (interactive) (insert "Κ"))
(defun ulambda-char () "Insert lower greek lambda" (interactive) (insert "Λ"))
(defun umu-char     () "Insert lower greek mu" (interactive) (insert "Μ"))
(defun unu-char     () "Insert lower greek nu" (interactive) (insert "Ν"))
(defun uxi-char     () "Insert lower greek xi" (interactive) (insert "Ξ"))
(defun uomicron-char() "Insert lower greek omicron" (interactive) (insert "Ο"))
(defun upi-char     () "Insert lower greek pi" (interactive) (insert "Π"))
(defun urho-char    () "Insert lower greek rho" (interactive) (insert "Ρ"))
(defun usigma-char  () "Insert lower greek sigma" (interactive) (insert "Σ"))
(defun utau-char    () "Insert lower greek tau" (interactive) (insert "Τ"))
(defun uupsilon-char() "Insert lower greek upsilon" (interactive) (insert "Υ"))
(defun uphi-char    () "Insert lower greek phi" (interactive) (insert "Φ"))
(defun uchi-char    () "Insert lower greek chi" (interactive) (insert "Χ"))
(defun upsi-char    () "Insert lower greek psi" (interactive) (insert "Ψ"))
(defun uomega-char  () "Insert lower greek omega" (interactive) (insert "Ω"))

;; Subcripts
(defun sub-1-char    () "Insert Subscript 1" (interactive) (insert "₁"))
(defun sub-2-char    () "Insert Subscript 2" (interactive) (insert "₂"))
(defun sub-3-char    () "Insert Subscript 3" (interactive) (insert "₃"))
(defun sub-4-char    () "Insert Subscript 4" (interactive) (insert "₄"))
(defun sub-5-char    () "Insert Subscript 5" (interactive) (insert "₅"))
(defun sub-6-char    () "Insert Subscript 6" (interactive) (insert "₆"))
(defun sub-7-char    () "Insert Subscript 7" (interactive) (insert "₇"))
(defun sub-8-char    () "Insert Subscript 8" (interactive) (insert "₈"))
(defun sub-9-char    () "Insert Subscript 9" (interactive) (insert "₉"))
(defun sub-0-char    () "Insert Subscript 0" (interactive) (insert "₀"))
(defun sub-n-char    () "Insert Subscript n" (interactive) (insert "ₙ"))
(defun sub-j-char    () "Insert Subscript j" (interactive) (insert "ⱼ"))
(defun sub-i-char    () "Insert Subscript i" (interactive) (insert "ᵢ"))
(defun sub-k-char    () "Insert Subscript k" (interactive) (insert "ₖ"))
(defun sub-m-char    () "Insert Subscript m " (interactive) (insert "ₘ"))
(defun sub-plus-char () "Insert Subscript +" (interactive) (insert "₊"))
(defun sub-minus-char() "Insert Subscript -" (interactive) (insert "₋"))

;; Set Notation
(defun subset-char     () "Insert Subset symbol" (interactive) (insert "⊂"))
(defun superset-char   () "Insert Superset symbol" (interactive) (insert "⊃"))
(defun subset-eq-char  () "Insert Subset or equal symbol" (interactive) (insert "⊆"))
(defun superset-eq-char() "Insert Superset or equal symbol" (interactive) (insert "⊇"))
(defun null-char       () "Insert Null Set Symbol" (interactive) (insert "∅"))
(defun intersect-char  () "Insert Intersection Symbol" (interactive) (insert "∩"))
(defun union-char      () "Insert Union Symbol" (interactive) (insert "∪"))

;; Misc Math
(defun sqroot-char     () "Insert Square Root Symbol" (insert "√"))
(defun infinity-char   () "insert Infinity Symbol"    (insert "∞"))

;; Logic
(defun forall-char         () "Insert Forall Symbol" (interactive) (insert  "∀"))
(defun exists-char         () "Insert exists Symbol" (interactive) (insert  "∃"))
(defun not-exists-char     () "Insert not-exists Symbol" (interactive) (insert  "∄"))
(defun element-char        () "Insert element Symbol" (interactive) (insert  "∈"))
(defun not-char            () "Insert not Symbol" (interactive) (insert  "¬"))
(defun or-char             () "Insert or Symbol" (interactive) (insert  "∨"))
(defun and-char            () "Insert and Symbol" (interactive) (insert  "∧"))
(defun l-angle-bracket-char() "Insert l-angle-bracket Symbol" (interactive) (insert  "⧼"))
(defun r-angle-bracket-char() "Insert r-angle-bracket Symbol" (interactive) (insert  "⧽"))
(defun implies-char        () "Insert implies Symbol" (interactive) (insert  "⇒"))
(defun bi-condition-char   () "Insert bi-condition Symbol" (interactive) (insert  "⇔ "))
(defun top-char            () "Insert top Symbol" (interactive) (insert  "⟙"))
(defun bottom-char         () "Insert bottom Symbol" (interactive) (insert  "⟘"))
(defun turnstile-char      () "Insert turnstile Symbol" (interactive) (insert  "⊢"))
(defun satisfies-char      () "Insert satisfies Symbol" (interactive) (insert  "⊨"))
(defun therefore-char      () "Insert therefore Symbol" (interactive) (insert  "∴"))
(defun box-char            () "Insert box Symbol" (interactive) (insert  "□"))
(defun diamond-char        () "Insert diamond Symbol" (interactive) (insert  "◇"))
(defun circle-char         () "Insert circle Symbol" (interactive) (insert "⚬"))
