## docs.toml -*- mode: conf-toml -*-

# autodoc : https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html
# apidoc  : https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html
# autogen : https://www.sphinx-doc.org/en/master/man/sphinx-autogen.html


[[locations]]
doc_src = "docs"
doc_out = "{temp}/docs"

[[tasks.docs]]
name       = "export"
depends_on = [{task="docs::build", inject={warn=false}}]

[[tasks.docs]]
name        = "build"
doc         = ["build sphinx"]
cli         = [{name="warn", type="bool", default=true},]
ctor        = "task"
doc_builder = "html"
env_name    = "default"
depends_on  = []
setup       = [
    { do="dootle.python.mamba:MambaEnv", env_="env_name", update_="env"},
    { do="installed?", args=["sphinx-build"], env_="env"},
    { do="exists?", args=["{doc_src!p}/conf.py"] },
]
actions = [
    { do="shell", env_="env", args=["sphinx-build",
    # "--verbose", "--verbose", "--nitpicky",
    "--write-all",
    "--keep-going", "--show-traceback",
    "--warning-file", "{logs!p}/sphinx.log",
    "--builder", "{doc_builder}",
    "{doc_src!p}", "{doc_out!p}",
    ]},

    # {do="taskcode.refresher:refresh_firefox"},
    ]
cleanup = []

[[tasks.docs]]
name        = "build.file"
doc         = ["build sphinx project documentation"]
cli         = [{name="fpath", type="str", default="", positional=true}]
ctor        = "task"
doc_builder = "html"
env_name    = "doot-dev"
setup       = [
    { do="dootle.python.mamba:MambaEnv", env_="env_name", update_="env"},
    { do="installed?", args=["sphinx-build"], env_="env"},
    { do="exists?", args=["{doc_src!p}/conf.py"] },
]
actions = [
    {do="log", msg="Building for: {fpath}"},
    {do="log", msg="sphinx-build --builder {doc_builder} --warning-file {logs!p}/sphinx.log --keep-going --show-traceback {doc_src!p} {doc_out!p} {fpath}"},
    { do="shell", env_="env", args=["sphinx-build",
     "--builder", "{doc_builder}",
    "--warning-file", "{logs!p}/sphinx.log",
    "--keep-going", "--show-traceback",
     "{doc_src!p}", "{doc_out!p}",
     "{fpath}"]},

     # {do="taskcode.refresher:refresh_firefox"},

     ]
cleanup = []
