#!/usr/bin/env python3
"""
This hook is invoked by git-commit(1) and git-merge(1), and
can be bypassed with the --no-verify option.

It takes a single parameter, the name of the file that holds the
proposed commit log message. Exiting with a non-zero status
causes the command to abort.

The hook is allowed to edit the message file in place, and
can be used to normalize the message into some project
standard format. It can also be used to refuse the commit
after inspecting the message file.

The default commit-msg hook, when enabled, detects duplicate
Signed-off-by trailers, and aborts the commit if one is
found.

"""
##-- imports
import argparse
import pathlib as pl
import re
import sys
##-- end imports

##-- argparse
parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
                                 epilog = "\n".join([""]))
parser.add_argument('commitfile')
##-- end argparse

##-- ifmain
if __name__ == "__main__":
    args = parser.parse_args()
    with open(pl.Path(args.commitfile), 'r') as f:
        line = f.readline()

    match_re = re.compile(r"^\[\w+\]")
    if not match_re.match(line):
        print("Commit Messages need to have a [tag] at the start")
        exit(1)

##-- end ifmain
