#!/usr/bin/env python3
"""
This hook is invoked by git-commit(1), and can be bypassed
with the --no-verify option. It takes no parameters, and is
invoked before obtaining the proposed commit log message and
making a commit. Exiting with a non-zero status from this
script causes the git commit command to abort before
creating a commit.

The default pre-commit hook, when enabled, catches
introduction of lines with trailing whitespaces and aborts
the commit when such a line is found.

All the git commit hooks are invoked with the environment
variable GIT_EDITOR=: if the command will not bring up an
editor to modify the commit message.

The default pre-commit hook, when enabled--and with the
hooks.allownonascii config option unset or set to
false--prevents the use of non-ASCII filenames.
"""

##-- imports
import sys
import pathlib as pl
import re
import subprocess
##-- end imports

##-- ifmain
if __name__ == "__main__":
    changes = subprocess.run(["git", "status", "-z"], shell=False, capture_output=True).stdout.decode().split("\x00")
    print("Changed: ")
    for line in changes:
        print(line)


##-- end ifmain
