#!/usr/bin/env python3
#
# Takes no parameters,
# invoked before obtaining commit message
# exit(1) to abort commit
#
# To check for whitespace errors:
# exec git diff-index --check --cached $against --

##-- imports
import sys
import pathlib as pl
import re
##-- end imports

##-- ifmain
if __name__ == "__main__":
    pass

##-- end ifmain
