#!/usr/bin/env python3
"""
An basic hook script to check the commit log message.
Called by "git commit" with one argument, the name of the file
that has the commit message.  The hook should exit with non-zero
status after issuing an appropriate message if it wants to stop the
commit.  The hook is allowed to edit the commit message file.
"""
##-- imports
import argparse
import pathlib as pl
import re
import sys
##-- end imports

##-- argparse
parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
                                 epilog = "\n".join([""]))
parser.add_argument('commitfile', required=True)
##-- end argparse

##-- ifmain
if __name__ == "__main__":
    args = parser.parse_args()
    with open(pl.Path(args.commitfile), 'r') as f:
        line = f.readline()

    match_re = re.compile(r"^\[\w+\]")
    if not match_re.match(line):
        print("Commit Messages need to have a [tag] at the start")
        exit(1)

##-- end ifmain
