(package! helm-cscope :disable t)
(package! xcscope :disable t)
(package! ruby-test-mode :disable t)
(package! pyenv :disable t)
;; (package! git-gutter :disable t)
;; (package! git-gutter+ :disable t)
;; (package! smartparens :disable t)
;; (package! smartparens-mode :disable t)
;; (package! show-paren-mode :disable t)
(package! erc :disable t)
(package! jabber :disable t)
(package! rcirc :disable t)
(package! slack :disable t)
(package! ido :disable t)
(package! ido-vertical-mode :disable t)
(package! ace-link :disable t)
(package! desktop :disable t)
(package! doc-view :disable t)
(package! flx-ido :disable t)
(package! open-junk-file :disable t)
(package! paradox :disable t)
(package! fancy-battery :disable t)
(package! golden-ratio :disable t)
(package! zoom-frm :disable t)
(package! company :disable t)
(package! smex :disable t)
(package! 2048-game :disable t)
(package! tetris :disable t)
(package! sudoku :disable t)
(package! helm-games :disable t)
(package! typit :disable t)
(package! selectric-mode :disable t)
(package! xkcd :disable t)
