;; Test Parsing
(defun jg-org-test-parse-tests (data)
  ;; split text into tests by full stops, defined groups,
  ;; and their originating heading
  (cl-assert (jg-org-test-extracts-p data))
  (if (not (string-empty-p (string-trim (jg-org-test-extracts-text data))))
      (let ((testgroups (parsec-with-input (jg-org-test-extracts-text data)
                          (parsec-many-till (jg-org-test-parse-group) (parsec-eof))))
            (link (jg-org-test-extracts-link data))
            (bound (jg-org-test-extracts-end data))
            (start (jg-org-test-extracts-start data))
            )
        (mapc (lambda (x)
                (cl-assert (jg-org-test-group-p x) t)
                (setf (jg-org-test-group-link x) link
                      (jg-org-test-group-bound x) bound
                      (jg-org-test-group-start x) start)) testgroups)
        testgroups
        )
    nil)
  )

(defun jg-org-test-parse-space ()
  (parsec-optional* (parsec-re "[[:blank:]]*")))
(defun jg-org-test-parse-word ()
  (parsec-return (parsec-re "[[:alnum:]]+")
    (jg-org-test-parse-space))
  )
(defun jg-org-test-parse-sword (word &optional retval)
  (let ((val (parsec-return (parsec-string word)
               (jg-org-test-parse-space))))
    (if retval retval val))
  )
(defun jg-org-test-parse-quote-string ()
  (mapconcat 'identity (parsec-between (parsec-ch ?\")
                                       (parsec-ch ?\")
                                       (parsec-many1 (jg-org-test-parse-word)))
             " ")
  )

(defun jg-org-test-parse-group-name ()
  (if (parsec-peek-p (parsec-re "[^:]+:\n"))
      (mapconcat 'identity
                 (parsec-many-till (jg-org-test-parse-word) (parsec-re ":"))
                 " ")
    "Anon Group")
  )

(defun jg-org-test-parse-group ()
  (jg-org-test-parse-space)
  (let* ((groupname (jg-org-test-parse-group-name))
         (tests (parsec-many-till (jg-org-test-parse-test) (parsec-or (parsec-eof) (parsec-re "\n\n"))))
        )
    (make-jg-org-test-group :name groupname :tests tests)
    )
  )
(defun jg-org-test-parse-test ()
  (parsec-re "\n?")
  (jg-org-test-parse-space)
  (let ((locator (parsec-or (jg-org-test-parse-quote-string)
                            (jg-org-test-parse-sword "Document" :document)
                            (jg-org-test-parse-sword "A section" :section)))
        keyword test
        )
    (jg-org-test-parse-space)
    (jg-org-test-parse-sword "should")
    (setq keyword (jg-org-test-parse-word)
          test (cond
                ((equal "have" keyword) (jg-org-test-parse-ownership-test))
                ((equal "be" keyword)   (jg-org-test-parse-existence-test))
                (t                      (jg-org-test-parse-misc-test keyword) )
                ))
    (setf (jg-org-test-locator test) locator)
    test))

(defun jg-org-test-parse-ownership-test ()
  ;; section/tag/codeblock
  (parsec-or (jg-org-test-parse-section-check)
             (jg-org-test-parse-tag-check)
             (jg-org-test-parse-codeblock-check)
             )
  )
(defun jg-org-test-parse-existence-test ()
  ;; length
  (jg-org-test-parse-length-check)
  )
(defun jg-org-test-parse-misc-test (keyword)
  ;; precede/cite/mention
  (cond
   ((equal keyword "precede") (jg-org-test-parse-order-check))
   ((equal keyword "cite") (jg-org-test-parse-citation-check))
   ((equal keyword "mention") (jg-org-test-parse-mention-check))
   )
  )

(defun jg-org-test-parse-section-check()
  (let ((test-type :section-check) subsection)
    (jg-org-test-parse-sword "section")
    (setq subsection (jg-org-test-parse-quote-string))
    (parsec-ch ?.)
    (make-jg-org-test :type test-type :value (downcase subsection))
    )
  )
(defun jg-org-test-parse-length-check ()
  (let ((test-type :length-check) dir length counter)
    (setq dir (parsec-or (jg-org-test-parse-sword "larger" :larger) (jg-org-test-parse-sword "smaller" :smaller)))
    (jg-org-test-parse-sword "than")
    (setq length (string-to-number (parsec-return (parsec-re "[[:digit:]]+") (jg-org-test-parse-space)))
          counter (parsec-or (jg-org-test-parse-sword "words" :words) (jg-org-test-parse-sword "paragraphs" :paras) (jg-org-test-parse-sword "sections" :sects))
          )
    (parsec-ch ?.)
    (make-jg-org-test :type test-type :value `(,dir ,length ,counter))
    )
  )
(defun jg-org-test-parse-order-check ()
  ;; locator should precede heading
  (let ((test-type :order-check) second)
    (setq second (jg-org-test-parse-quote-string))
    (parsec-ch ?.)
    (make-jg-org-test :type test-type :value second)
    )
  )
(defun jg-org-test-parse-citation-check ()
  ;; locator should cite citelist
  (let ((test-type :citation-check) citations)
    (parsec-ch ?:)
    (setq citations (parsec-sepby (parsec-re "[[:alnum:]]+") (parsec-ch ?,)))
    (parsec-ch ?.)
    (make-jg-org-test :type test-type :value citations)
    )
  )
(defun jg-org-test-parse-mention-check ()
  ;; locator should mention string
  (let ((test-type :mention-check) mention)
    (setq mention (jg-org-test-parse-quote-string))
    (parsec-ch ?.)
    (make-jg-org-test :type test-type :locator locator :value mention)
    )
  )
(defun jg-org-test-parse-codeblock-check ()
  ;; locator should have a codeblock
  (let ((test-type :codeblock-check) language)
    (jg-org-test-parse-sword "codeblock")
    (setq language (parsec-optional (parsec-and (jg-org-test-parse-sword "in") (jg-org-test-parse-quote-string))))
    (parsec-ch ?.)
    (make-jg-org-test :type test-type :value language)
    )
  )
(defun jg-org-test-parse-tag-check ()
  ;; locator should have tag x
  (let ((test-type :tag-check) mention)
    (jg-org-test-parse-sword "tag")
    (setq mention (jg-org-test-parse-quote-string))
    (parsec-ch ?.)
    (make-jg-org-test :type test-type :locator locator :value mention)
    )
  )

