;; Test Execution
(defun jg-org-test-forward-to (locator bound)
  (cond
   ((eq :document locator) nil)
   ((eq :section locator) nil)
   (t (re-search-forward (format jg-org-test-heading-regexp locator) bound))
   )
  )
(defun jg-org-test-forward-past-tests (locator bound)
  (jg-org-test-forward-to locator bound)
  (let ((orig (point)))
    (re-search-forward org-drawer-regexp bound)
    (if (s-equals? "__org-unit-test-layer__" (match-string 1))
        (re-search-forward org-drawer-regexp bound)
      (goto-char orig))
    )
  )

(defun jg-org-test-run-tests (testgroups)
  (mapcar 'jg-org-test-run-test-group testgroups)
  )
(defun jg-org-test-run-test-group (testgroup)
  (cl-assert (jg-org-test-group-p testgroup) t)
  (goto-char (jg-org-test-group-start testgroup))
  (let* ((name (jg-org-test-group-name testgroup))
         (bound (jg-org-test-group-bound testgroup))
         (results (mapcar (lambda (x) `(,(jg-org-test-to-string x) . ,(jg-org-test-run-test x bound))) (jg-org-test-group-tests testgroup)))
         )
    (make-jg-org-test-results :name name :results results :link (jg-org-test-group-link testgroup)))
  )
(defun jg-org-test-run-test (test bound)
  (cl-assert (jg-org-test-p test))
  (save-excursion
    (condition-case e
        (let ((type (jg-org-test-type test)))
          (cond
           ((eq type :section-check )   (jg-org-test-run-test-section test bound))
           ((eq type :length-check )    (jg-org-test-run-test-length test bound))
           ((eq type :order-check )     (jg-org-test-run-test-order test bound))
           ((eq type :citation-check )  (jg-org-test-run-test-citation test bound))
           ((eq type :mention-check )    (jg-org-test-run-test-mention test bound))
           ((eq type :codeblock-check ) (jg-org-test-run-test-codeblock test bound))
           ((eq type :tag-check)        (jg-org-test-run-test-tag test bound))
           (t (error "Unrecognized test type"))
           )
          )
      (search-failed nil)
      )
    )
  )

(defun jg-org-test-run-test-section (test bound)
  ;;go to the locator
  (jg-org-test-forward-past-tests (jg-org-test-locator test) bound)
  ;; get subheadings
  (let ((subheadings (org-map-entries
                      (lambda () (downcase (substring-no-properties (org-get-heading)))) nil 'tree)))
    ;; is the section value in the subheadings?
    (-contains? subheadings (jg-org-test-value test))
    )
  )
(defun jg-org-test-run-test-length (test bound)
  (jg-org-test-forward-past-tests (jg-org-test-locator test) bound)
  (let* ((vals (jg-org-test-value test))
         (dir (car vals))
         (length (cadr vals))
         (counter (caddr vals))
         (test (if (eq :larger dir) '> '<))
         )
    (cond
     ((eq counter :words) (funcall test (count-words (point)
                                                     (plist-get (cadr (org-element-at-point)) :contents-end))
                                   length))
     ;; ((eq counter :paras) (funcall test (count-paragraphs (point)
     ;;                                                      (plist-get (cadr (org-element-at-point)) :contents-end))
     ;;                               length)
     ((eq counter :sects)  (funcall test (- (reduce '+ (org-map-entries (lambda () 1) nil 'tree)) 1) length))
     (t (error "Unrecognized test-length counter"))
     )
    )
  )
(defun jg-org-test-run-test-order (test bound)
  (let* ((tree (org-map-entries (lambda () (substring-no-properties (org-get-heading))) nil 'tree))
         (locator (-elem-index (jg-org-test-locator test) tree))
         (section (-elem-index (jg-org-test-value test) tree))
         )
    (if (and locator section)
        (< locator section)
      nil)
    )
  )
(defun jg-org-test-run-test-citation (test bound)
  (jg-org-test-forward-past-tests (jg-org-test-locator test) bound)
  (let ((citations (jg-org-test-value test)) curr-line)
    (while citations
      (re-search-forward "cite:" bound)
      (setq curr-line (buffer-substring-no-properties (line-beginning-position) (line-end-position)))
      (setq citations (remove-if (lambda (x) (s-contains? x curr-line)) citations))
      )
    )
  )
(defun jg-org-test-run-test-mention (test bound)
  (jg-org-test-forward-past-tests (jg-org-test-locator test) bound)
  (search-forward (jg-org-test-value test) bound)
  )
(defun jg-org-test-run-test-codeblock (test bound)
  (jg-org-test-forward-past-tests (jg-org-test-locator test) bound)
  (re-search-forward (format "%s %s" jg-org-test-src-block-regexp
                             (if (jg-org-test-value test) (jg-org-test-value test) "")) bound)
  )
(defun jg-org-test-run-test-tag (test bound)
  (jg-org-test-forward-to (jg-org-test-locator test) bound)
  (let ((tags (plist-get (cadr (org-element-at-point)) :tags)))
    (-contains? tags (jg-org-test-value test))
    )
  )
