# https://pre-commit.com
# https://pre-commit.com/hooks.html
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: ["--fix", "auto"]
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: ["--autofix"]
# - repo: local
#   hooks:
#     - id: pylint
#       name: pylint
#       entry: pylint
#       language: system
#       types: [python]
#       args:
#         [
#           "-rn", # Only display messages
#           # "-sn", # Don't display the score
#           # "--rcfile=pylint.toml", # Link to your config file
#           # "--exit-zero",
#         ]
