verbosity                = 2
default_tasks            = []
action_string_formatting = "new"
subtask                  = { sleep = 1 }
batch                    = { sleep = 1 }
notify                   = { say-on-exit = false }

[globbing]
ignores  = ['.git', '.DS_Store', "__pycache__"]

[logging]
stream = { level = "INFO", format  = "{levelname:<8} : {message}", filters = ["doot"] }
file   = { level = "DEBUG", format = "{levelname:<8} : {message:<20} :|: (module:{module} line:{lineno} fn:{funcName})", filters =  ["doot"] }

[[directories]]
src    = "{{cookiecutter.proj_name}}"
python = "{{cookiecutter.proj_name}}"
rust   = "{{cookiecutter.proj_name}}"
temp   = ".temp"
build  = "build"
docs   = "docs"

[group.python]
[group.py]
[group.pip]
[group.rust]
