(package! instal-mode     :recipe `(:local-repo ,(expand-file-name "~/github/python/instal/instal-mode")))
(package! agentspeak-mode :recipe `(:local-repo ,(expand-file-name "packages/major-modes/agentspeak-mode" doom-user-dir)))
(package! jacamo-mode     :recipe `(:local-repo ,(expand-file-name "packages/major-modes/jacamo-mode" doom-user-dir)))
(package! soar-mode       :recipe `(:local-repo ,(expand-file-name "packages/major-modes/soar-mode" doom-user-dir)))
(package! clips-mode)
(package! pasp-mode)
(package! z3-mode)

(package! ob-ccalc        :recipe `(:local-repo ,(expand-file-name "packages/org-babel-ext" doom-user-dir) :files ( "ob-ccalc.el" )))
(package! ob-ceptre       :recipe `(:local-repo ,(expand-file-name "packages/org-babel-ext" doom-user-dir) :files ( "ob-ceptre.el" )))
(package! ob-clingo       :recipe `(:local-repo ,(expand-file-name "packages/org-babel-ext" doom-user-dir) :files ( "ob-clingo.el" )))
(package! ob-clips        :recipe `(:local-repo ,(expand-file-name "packages/org-babel-ext" doom-user-dir) :files ( "ob-clips.el" )))
(package! ob-instal       :recipe `(:local-repo ,(expand-file-name "packages/org-babel-ext" doom-user-dir) :files ( "ob-instal.el" )))
(package! ob-prolog)
(package! ob-soar         :recipe `(:local-repo ,(expand-file-name "packages/org-babel-ext" doom-user-dir) :files ( "ob-soar.el" )))
(package! ob-z3           :recipe `(:local-repo ,(expand-file-name "packages/org-babel-ext" doom-user-dir) :files ( "ob-z3.el" )))
