(defconst jg_layer
  '(
    (git-gutter :excluded t)
    (git-gutter+ :excluded t)
    (smartparens :excluded t)
    (show-paren-mode :excluded t)
    (erc :excluded t)
    (jabber :excluded t)
    (rcirc :excluded t)
    (slack :excluded t)
    (default-ivy-config :excluded t)
    (ido :excluded t)
    (ido-vertical-mode :excluded t)
    (eyebrowse :excluded t)
    (ivy :excluded t)
    (persp-mode :excluded t)
    (swiper :excluded t)
    (ace-link :excluded t)
    (desktop :excluded t)
    (doc-view :excluded t)
    (flx-ido :excluded t)
    (open-junk-file :excluded t)
    (paradox :excluded t)
    (fancy-battery :excluded t)
    (golden-ratio :excluded t)
    (zoom-frm :excluded t)
    (company :excluded t)
    (projectile :excluded t)
    (smex :excluded t)
    (2048-game :excluded t)
    (tetris :excluded t)
    (sudoku :excluded t)
    (helm-games :excluded t)
    (typit :excluded t)
    (selectric-mode :excluded t)
    (xkcd :excluded t)
    )
  )
