# Add to .github/workflows
# https://www.sphinx-doc.org/en/master/tutorial/deploying.html
# https://github.com/ammaraskar/sphinx-action
# put dependencies into docs/requirements.txt
name: Sphinx build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Starting Sphinx Documentation Update"
    - uses: actions/checkout@v2
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
