;; (package! fci)
(package! avy)
(package! cedet :built-in 'prefer)
(package! dired-quick-sort)
(package! evil)
(package! evil-iedit-state)
(package! evil-iedit-state)
(package! evil-quickscope)
(package! evil-snipe)
(package! exec-path-from-shell)
(package! f)
(package! flycheck)
(package! free-keys)
(package! fsm)
(package! neotree)
(package! origami)
(package! semantic)
(package! shell-pop)
(package! timeline-mode :recipe `(:local-repo ,(expand-file-name "packages/major-modes/timeline-mode" doom-user-dir)))
(package! vlf)

;; Disables
(package! undo-tree       :disable t)
(package! 2048-game       :disable t)
(package! ace-link        :disable t)
(package! desktop         :disable t)
(package! doc-view        :disable t)
(package! erc             :disable t)
(package! fancy-battery   :disable t)
(package! golden-ratio    :disable t)
(package! helm-cscope     :disable t)
(package! helm-games      :disable t)
(package! jabber          :disable t)
(package! open-junk-file  :disable t)
(package! paradox         :disable t)
(package! rcirc           :disable t)
(package! ruby-test-mode  :disable t)
(package! selectric-mode  :disable t)
(package! slack           :disable t)
(package! smex            :disable t)
(package! sudoku          :disable t)
(package! tetris          :disable t)
(package! typit           :disable t)
(package! xcscope         :disable t)
(package! xkcd            :disable t)
(package! zoom-frm        :disable t)
(package! evil-easymotion :disable t)
(package! xt-mouse        :disable t)
(package! mouse           :disable t)
(package! undo-fu-session :disable t)
