verbosity                = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"

[tool.doot]
subtask = { sleep = 1 }
batch   = { sleep = 1 }
notify  = { say-on-exit = false }

[tool.doot.globbing]
ignores  = ['.git', '.DS_Store', "__pycache__"]

[[tool.doot.directories]]
data    = "."
