verbosity                = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"
subtask                  = { sleep = 1 }
batch                    = { sleep = 1, size=100}
notify                   = { say-on-exit = false }

[logging]
stream = { level = "INFO", format  = "-- {message}", filters = ["doot"] }
file   = { level = "DEBUG", format = "{levelname:<8} : {message:<20} : ({module}.{lineno}.{funcName})", filters =  ["doot"] }

[globbing]
ignores  = ['.git', '.DS_Store', "__pycache__"]

[[directories]]
data    = "."
build   = ".processes"
temp    = ".processes"
backup  = "/Volumes/BackupSD/Pictures"
