verbosity                = 1
default_tasks            = ["locs::report"]
action_string_formatting = "new"
notify                   = { sleep = false, say-on-exit = false }
subtask                  = { sleep = 2 }
batch                    = { sleep = 0, size = 1000 }

# [plugins.reporter]
# custom = "doot.utils.reporter:DootReporter"

# [plugins.command]
# run    = "doot.utils.custom_run:DootRun"

[globbing]
ignores = ['.git', '.DS_Store', "__pycache__"]

[logging]
stream = { level = "INFO", format  = "-- {message}", filters = ["doot", "doit"] }
file   = { level = "DEBUG", format = "{levelname:<8} : {message:<20} : ({module}.{lineno}.{funcName})", filters =  ["doot", "doit"] }

[[directories]] # Core
temp               = ".temp"
logs               = ".logs"
bots               = ".bots"
build              = "doot_build"

[[directories]] # Backup
backup_root        = "/Volumes/BackupSD/"
images_backup      = "/Volumes/BackupSD/Pictures"
movies_backup      = "/Volumes/BackupSD/Movies"
pdf_backup         = "/Volumes/BackupSD/Library/pdf_library"
pdf_summary_backup = "/Volumes/BackupSD/Library/summary"
thread_backup      = "/Volumes/BackupSD/Library/twitter_threads"

[[directories]] # Watch Directories
bibtex             = "~/github/jgrey4296.github.io/resources/bibliography"
downloads          = "~/Downloads"
desktop            = "~/Desktop"
dropbox            = "~/Dropbox/docs"
bibtex_working     = "/Volumes/documents/in_progress_pdfs/Current/"
firefox            = "~/Library/ApplicationSupport/Firefox"

[[directories]] # libraries
bookmarks          = "~/github/jgrey4296.github.io/resources/bookmarks"
tags               = "~/github/jgrey4296.github.io/resources/tags"
orgs               = "~/github/jgrey4296.github.io/orgfiles"
thread_library     = "/Volumes/documents/twitter_threads"
pdfs               = "/Volumes/documents/pdf_library"
movies             = "/Users/johngrey/Movies"
images             = "/Volumes/documents/DCIM"
github             = "~/github"
git_libs           = "~/github/_libs"

[[files]] # library files
bookmarks_total = "~/github/jgrey4296.github.io/resources/bookmarks/total.bookmarks"

[[directories]] # output
pdf_summary        = "/Volumes/documents/in_progress_pdfs/pdflib_automations/total_bib"
maintain           = "/Volumes/documents/github/__configs/terminal/maintenance"
listings_out       = "doot_build"

[[directories]] # Android
local_push         = "/volumes/documents/pdf_library"
local_pull         = "/volumes/documents/android_test_pull"

[[files]] # bibtex bot files
bib_blacklist   = ".bots/bibtex_blacklist"
bib_compile_tex = ".bots/bib_compile_template.tex"
bib_success     = ".bots/log.bib_success"
bib_fail        = ".bots/log.bib_fail"
bib_style       = ".bots/jg_custom.bst"

[[files]] # image bot files
image_whitelist = ".bots/dcim_whitelist"
image_blacklist = ".bots/resolution_blacklist"
image_temp      = ".bots/conversion_temp"
bib_stub_file   = "~/github/jgrey4296.github.io/resources/todo.bib"
secrets         = "~/.secrets/bkmkorg.toml"

[group.maintain]
