verbosity                = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"

[tool.doot]
subtask  = { sleep = 1 }
batch    = { sleep = 1 }
notify   = { say-on-exit = false }
globbing = { ignores = ['.git', '.DS_Store', "__pycache__"] }

[tool.doot.logging]
log_format    = "{levelname} : {name} : {lineno} : {funcName} : {message}"
log_filters   = ["bkmkorg", "doot"]

[tool.doot.directories]
temp    = ".temp"
build   = "build"
data    = "."
