verbosity                = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"
subtask                  = { sleep = 1 }
batch                    = { sleep = 1 }
notify                   = { say-on-exit = false }

[logging]
stream = { level = "INFO", format  = "{levelname:<8} : {message}", filters = ["doot", "bkmkorg"] }
file   = { level = "DEBUG", format = "{levelname:<8} : {message:<20} : ({module}.{lineno}.{funcName})", filters =  ["doot", "bkmkorg"] }

[globbing]
ignores  = ['.git', '.DS_Store', "__pycache__"]

[[directories]]
home       = "/Users/johngrey"
github     = ""
emacs_d    = ""
doom_d     = ""
mega       = ""
pdfs       = ""
# terminal = ""
