#+TITLE: Latex Package Reference

* Overview
http://en.wikibooks.org/wiki/LaTeX/
https://www.tug.org/texlive/doc/tlmgr.html
http://www.tug.org/mactex/
https://ctan.org/
https://www.luatex.org/
https://www.overleaf.com/learn/how-to/Creating_a_document_in_Overleaf
https://tug.org/xetex/

* Main
** Proofs
Bussproofs                                                  # Proof Trees. https://mathweb.ucsd.edu/~sbuss/ResearchWeb/bussproofs/
ebproof                                                     # Proof trees
fitch                                                       # Natural Deduction
prftree                                                     # Proof trees
prooftrees                                                  # actual branching trees with angles
prooftree                                                   #
ND                                                          #
nd3                                                         # Natural Deduction
semantic                                                    # programming language semantics

** Quotes
csquotes                                                    # provides \begin{displayquote} for non-inline
dirtytalk                                                   # provides \say{[text]}

** Fonts
microtype                                                   # typewriting
mhchem
fontenc                                                     # fonts
babel                                                       # fonts
lettrine
amsmath
mathtools
amssymb
fontspec

** Links
[colorlinks=true,urlcolor=blue,pdfstartview=FitH]{hyperref} # hyperlinks
doi
hyperref
url

** Headers / Footers / Margins
sidecap                                                     # side captions for figures.
mparhack                                                    # for fixing margin notes
fancyhdr                                                    # headers and footers
footmisc                                                    # footnotes at bottom of page
marginnote
sidecap
marginal                                                    # margin notes
marginnote                                                  # alternative margin notes.
marginpar                                                   # margin notes

** Page Style
titlesec                                                    # customize chapter/section styles
geometry                                                    # Page control
layout                                                      # layout control
lscape                                                      # landscape
multicol                                                    # columns for when \documentclass{\twocolumn} isnt enough
picinpar
longtable                                                   #

** Appendices
nomencl                                                     # nomenclature
glossaries                                                  # glossary creation. uses makeindex
imakeidx                                                    # index creation
makeindex                                                   #

** Graphics
graphicx                                                    # for images with \includegraphics{img} and \graphicspath{path}
tikz
pgfgantt                                                    # gant charts
chemfig
ochem
qtree

** Text
lipsum
minted                                                      # code highlighting
pygments                                                    # also has code highlighting output
listings                                                    # code listings
algorithmic
algorithm2e
algorithmicx

** Bibliography
natbib

** Document Styles
https://ctan.org/pkg/newspaper
https://www.ctan.org/pkg/komacv

** Music: Lilypond
http://lilypond.org/doc/v2.12/Documentation/user/lilypond-program/
* Links
http://en.wikibooks.org/wiki/LaTeX/Importing_Graphics
http://en.wikibooks.org/wiki/LaTeX/Lengths
http://en.wikibooks.org/wiki/LaTeX/Lengths#Length_manipulation
http://tex.stackexchange.com/questions/16942/difference-between-textwidth-linewidth-and-hsize
http://tex.stackexchange.com/questions/23078/how-can-i-automatically-center-an-image
http://tex.stackexchange.com/questions/31339/setting-environment-variables-for-latex-and-bibtex-in-bashrc
http://tex.stackexchange.com/questions/53377/inspirational-quote-at-start-of-chapter
http://www.latex-community.org/forum/viewtopic.php?t=3078&f=21&p=12189
http://www.volkerschatz.com/tex/tpacks.html
http://yabas.net/blog/install-latex-on-mac-with-brew/
https://bilalakil.me/getting-started-and-productive-with-latex-basictex-on-os-x-terminal/
https://docs.latexbase.com/
https://en.wikibooks.org/wiki/LaTeX/Special_Characters#Escaped_codes
https://en.wikibooks.org/wiki/LaTeX/Text_Formatting#Line_Spacing
https://github.com/TeX-Live
https://github.com/hmemcpy/milewski-ctfp-pdf
https://github.com/plk/biblatex
https://github.com/typst/typst
https://gitlab.com/susurrus/ucsc-dissertation
https://it.slashdot.org/story/13/02/14/1814217/collaborative-latex-editor-with-preview-in-your-web-browser
https://latex-programming.fandom.com/wiki/Tabular_(LaTeX_environment)
https://latex-tutorial.com/
https://latex2e.org/
https://latexref.xyz/index.html#SEC_Contents
https://linuxconfig.org/how-to-install-latex-on-ubuntu-20-04-focal-fossa-linux
https://mathweb.ucsd.edu/~sbuss/ResearchWeb/bussproofs/
https://tech.slashdot.org/story/13/04/07/1614209/extended-tex-past-present-and-future
https://tex.stackexchange.com/questions/12806/guidelines-for-customizing-biblatex-styles
https://tex.stackexchange.com/questions/12887/is-there-a-list-available-for-all-tex-fonts
https://tex.stackexchange.com/questions/200807/insert-a-figure-on-the-corner-of-the-page
https://tex.stackexchange.com/questions/297004/tlmgr-open-documentation-for-package-basictex
https://tex.stackexchange.com/questions/4327/where-do-i-find-out-how-a-command-environment-is-defined
https://tex.stackexchange.com/questions/801/what-is-the-easiest-way-to-get-borders-around-a-page-in-latex
https://texample.net/tikz/examples/all/
https://tikz.dev/
https://trac.macports.org/wiki/TeXLivePackages
https://web.archive.org/web/20180721043841/https://www.cl.cam.ac.uk/~rf10/pstex/latexcommands.htm
https://www.overleaf.com/latex/templates/newspaper-slash-news-letter-template/wjxxhkxdjxhw#.Wt-T6LjLfz0
https://www.overleaf.com/learn/how-to/Creating_a_document_in_Overleaf
https://www.overleaf.com/learn/latex/TikZ_package
https://www.tug.org/texlive/doc/tlmgr.html
