## android.toml<2> -*- mode: conf-toml -*-
[[locations]]
push_pdfs = "{pdf_source}"
# data_drive   = "/media/john/data"
# pdf_source   = "{data_drive}/library/pdfs"

[[tasks.android]]
name                 = "device.find"
version              = "0.1"                # <str>
ctor                 = "task"               # <type>
doc                  = ["Run Find On the Device, write the results locally"] # <list[str]>
android_root         = "/storage/6331-3162"
actions              = [
                     { do="dootle.android.actions:AndroidRunning"} ,
                     { do="dootle.android.actions:AndroidRemoteCmd", cmd="find", args=["{android_root}/Library/pdf_library", "-type", "f"] },
                     { do="write!", from_="adb_result", to="{temp}/adb_files" }
]


# TODO
[[tasks.android]]
name                   = "push.pdfs"
version                = "0.1"
ctor                   = "job"
mixins                 = ["job:walker", "job:terse"]
doc                    = ["Push pdfs to device"]
filter_fn              = "tasks_code.android:select_dirs"
roots                  = ["{push_pdfs}"]
print_level            = { head="INFO", action="DEBUG" }
android_root           = "/storage/6331-3162"
sub_actions                = [
        { do="log", msg="Pushing: {fname} to {android_root}/Library/pdf_library/{lpath}"},
        { do="dootle.android.actions:AndroidRunning" },
        { do="dootle.android.actions:AndroidPush", local="{fpath}", remote="{android_root}/Library/pdf_library/" },
]
