## backup.toml<2> -*- mode: conf-toml -*-

[[locations]]
backup       = "{temp}/backup"
data_drive   = "/media/john/data"
backup_drive = "/media/john/big_ex"
pdf_source   = "{data_drive}/library/pdfs"
pdf_bkup     = "{backup_drive}/library/pdfs"

# TODO movies
# TODO images

##-- pdfs
[[tasks.backup]]
name                       = "pdfs"
version                    = "0.1"                                                       # <str>
doc                        = ["Backup pdf library"]
ctor                       = "tasker"             # <type>
mixins                     = ["walker", "terse"]
clean_locs                 = ["{pdf_bkup}"]
exts                       = []                                  # <list[str]>
recursive                  = true                                # <bool>
roots                      = ["{pdf_source}"]                    # <list[str|pl.Path]>  Places the globber will start
shadow_root                = "{pdf_bkup}"
head_actions               = [{do="doot.actions.postbox:SummarizePostAction", full=false}]
sub_actions                = [
                     {do="dir!", args=["{shadow_path}"] },
                     {do="backup!", from_="fpath", to="{shadow_path}/{fname}"}
]
##-- end pdfs
