[[locations]]
bib = "~/github/bibliography/main"

# TODO Stubber
# TODO cleaner
# TODO summaries

##-- walker
[[tasks.bib]]
name                 = "walker"
version              = "0.1"                                              # <str>
ctor                 = "walker"                                           # <type>
doc                  = ["A walker entry point for loading bibtex files"] # <list[str]>
head_task            = "bib::_walk_collect"                               # <task_iden>
sub_task              = "bib::_walk_bib"                                  # <task_iden>
exts                 = [".bib"]                                           # <list[str]>
roots                = ["{bib}"]                                          # <list[str|pl.Path]>  Places the globber will start
recursive            = false                                              # <bool>

[[tasks.bib]]
name                 = "_walk_bib"
version              = "0.1"                                                                                                        # <str>
ctor                 = "task"                                                                                                       # <type>
doc                  = ["An example bibtex load task for the globber", "writes out the loaded file, and merges it with the others"] # <list[str]>
sleep                = 0.1
actions              = [
                     { do="dir!", args=["{temp}/bib"] },
                     { do= "dootle.bibtex.actions:BibtexInitAction", update="bib_db"},
                     { do= "dootle.bibtex.actions:BibtexLoadAction",  from_="fpath",    db_key="bib_db" },
                     { do= "dootle.bibtex.actions:BibtexToStrAction", from_="bib_db",   update_="bib_text" },
                     { do= "write!",                                  from_="bib_text", to="{temp}/bib/{fstem}_b.bib" },
                     { do= "dootle.bibtex.actions:BibtexMergeAction", from_="bib_db"},
                     ]                       # <list[Any]>

[[tasks.bib]]
name                 = "_walk_collect"
version              = "0.1"                                                                             # <str>
ctor                 = "task"                                                    # <type>
doc                  = ["the head of the bibtex globber, writing the merged database to a single file "] # <list[str]>
actions              = [
                     { do= "dootle.bibtex.actions:BibtexMergeAction", from_="bib_db",   update_="bib_db" },
                     { do= "dootle.bibtex.actions:BibtexToStrAction", from_="bib_db",   update_="bib_text" },
                     { do= "write!",                                  from_="bib_text", to="{temp}/collected.bib" },
                     ]                       # <list[Any]>

##-- end walker

# [[tasks.bib]]
# name                 = "basic.load"
# version              = "0.1"                                                     # <str>
# ctor                 = "task"                                                    # <type>
# doc                  = ["a basic bibtex load task with explicit file specified"] # <list[str]>
# bib_files            = ["{bib}/1637.bib", "{bib}/1773.bib"]
# actions              = [
#                      # { do= "doot.actions.state:AddStateAction", bib_files=["{bib}/1637.bib"]},
#                      { do= "dootle.bibtex.actions:BibtexInitAction",  bib_uniq=false,    update_="bib_db"},
#                      { do= "dootle.bibtex.actions:BibtexLoadAction",  from_="bib_files", update_="bib_db" },
#                      { do= "dootle.bibtex.actions:BibtexToStrAction", from_="bib_db",    update_="bib_text" },
#                      { do= "write!", from_="bib_text", to="{temp}/out.bib" },
#                      ]                       # <list[Any]>
