;;; main/jg-personal/+helm-funcs.el -*- lexical-binding: t; -*-


(after! helm
  (defun +jg-personal-helm-open-random-action (candidate)
    """ Helm Action that opens files randomly, by prompting for a file extension
   searching as necessary, and keeping a log of files opened before """
    (let* ((candidates (helm-marked-candidates))
           (file_ext (read-string "File Extension: "))
           (log_file (f-join (if (f-dir? (car candidates)) (car candidates) (f-dirname (car candidates))) ".emacs_rand_file_log"))
           )
      (if (-all-p 'f-file-p candidates)
          ;; if given files, open randomly
          (find-file (seq-random-elt candidates))
        ;; if given directories, search them
        (let ((all_files (-flatten (seq-map (lambda (x) (directory-files-recursively x file_ext)) candidates)))
              (already_used_files (if (f-exists? log_file) (with-temp-buffer
                                                             (insert-file-contents log_file)
                                                             (let ((uf (make-hash-table :test 'equal)))
                                                               (seq-each (lambda (x) (puthash (downcase x) 't uf)) (split-string (buffer-string) "\n"))
                                                               uf))
                                    (progn (message "Making new hash table")
                                           (make-hash-table :test 'equal))))
              (stay_looping 't)
              )
          (while (and stay_looping (> (length all_files) (length (hash-table-keys already_used_files))))
            (let ((the_choice (seq-random-elt all_files)))
              (message "Checking for: %s" the_choice)
              (message "Result: %s" (gethash (downcase the_choice) already_used_files))
              (if (not (gethash (downcase the_choice) already_used_files))
                  (progn
                    (write-region the_choice nil log_file 'append)
                    (write-region "\n" nil log_file 'append)
                    (setq stay_looping nil)
                    (find-file the_choice)
                    )
                )
              )
            )
          )
        )
      )
    )
  (defun +jg-personal-helm-describe-random-action (candidate)
    "Helm action to describt how many of a directory's files have been randomly opened,
versus not"
    (let* ((candidates (helm-marked-candidates))
           (file_ext (read-string "File Extension: "))
           (log_file (f-join (if (f-dir? (car candidates)) (car candidates) (f-dirname (car candidates))) ".emacs_rand_file_log"))
           (used-files (if (f-exists? log_file) (with-temp-buffer
                                                  (insert-file-contents log_file)
                                                  (let ((uf (make-hash-table :test 'equal)))
                                                    (seq-each (lambda (x) (puthash (downcase x) 't uf)) (split-string (buffer-string) "\n"))
                                                    uf))
                         (make-hash-table :test 'equal)))
           (all-files (-flatten (seq-map (lambda (x) (directory-files-recursively x file_ext)) candidates)))
           (count 0)
           (unopened '())
           )
      (mapc (lambda (x) (if (not (gethash (downcase x) used-files)) (progn (incf count) (push x unopened)))) all-files)
      (with-current-buffer (messages-buffer)
        (message "%s" (mapconcat 'identity unopened "\n"))
        )
      (message "Files not opened randomly: %s" count)
      )
    )
  (defun +jg-personal-bookmark-load-random ()
    """ Open a random bookmark, log it, and provide a
      temp buffer to edit tags in """
    (interactive)
    (widen)
    (let* ((location (f-dirname (buffer-file-name)))
           (log_file (f-join location ".emacs_rand_bookmark_log"))
           (log_hash (if (f-exists? log_file) (with-temp-buffer
                                                (insert-file-contents log_file)
                                                (let ((uf (make-hash-table :test 'equal)))
                                                  (seq-each (lambda (x) (puthash x 't uf)) (split-string (buffer-string) "\n"))
                                                  uf))
                       (make-hash-table :test 'equal)))
           )
      ;; go to random line
      ;;(alist-get 'HREF (cadr data)) = href/tags
      ;;caddr data = name
      (goto-char (random (point-max)))
      (goto-char (line-beginning-position))
      (forward-char 4)
      (let ((entry (xml-parse-tag)))
        (while entry
          (if (gethash (alist-get 'HREF (cadr entry) nil nil 'equal) log_hash)
              (progn (goto-char (random (point-max)))
                     (goto-char (line-beginning-position))
                     (forward-char 4)
                     (setq entry (xml-parse-tag)))
            (progn
              (write-region (alist-get 'HREF (cadr entry) nil nil 'equal)
                            nil log_file 'append)
              (write-region "\n" nil log_file 'append)
              (narrow-to-region (line-beginning-position) (line-end-position))
              (goto-char (point-min))
              (org-open-link-from-string (message "[[%s]]" (alist-get 'HREF (cadr entry))))
              (setq entry nil)
              )
            )
          )
        )
      )
    )
  (defun +jg-personal-helm-open-random-external-action (candidate)
    " Open a random file in an external program, optionally specifying wildcard "
    (interactive)
    (let* ((pattern (car (last (f-split candidate))))
           (pattern-r (wildcard-to-regexp pattern))
           (files (helm-get-candidates (helm-get-current-source)))
           (all_matches (if (string-match-p "\*\." pattern)
                            (seq-filter (lambda (x) (string-match-p pattern-r x)) files)
                          (f-files candidate)))
           (selected (seq-random-elt all_matches)))
      (debug)
      ;; TODO (spacemacs//open-in-external-app selected)
      ))
  (defun +jg-personal-helm-open-random-exploration-action (candidate)
    " Randomly choose a directory until an openably file is found (wildcard optional)"
    ;; TODO
    (interactive)
    (let* ((pattern (car (last (f-split candidate))))
           (pattern-r (wildcard-to-regexp pattern))
           (files (helm-get-candidates (helm-get-current-source)))
           (all_matches (if (string-match-p "\*\." pattern)
                            (seq-filter
                             (lambda (x) (string-match-p pattern-r x))
                             files)
                          (f-files candidate)))
           (selected (seq-random-elt all_matches)))
      (debug)
      ;; TODO (spacemacs//open-in-external-app selected)
      ))
  (defun +jg-personal-switch-major-mode ()
    (interactive)
    (let ((major-modes +jg-personal-major-modes))
      (helm
       :sources '((name . "Major modes")
                  (candidates . major-modes)
                  (action . (lambda (mode) (funcall (intern mode))))
                  (persistent-action . (lambda (mode) (describe-function (intern mode)))))))

    )
  )
